#####################################################################
### Set Away Mode when weather is Awesome
#####################################################################
automation:
  - alias: Climate Downstairs Away if Awesome Weather
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Awesome'

    condition:
      - condition: template
        value_template: "{{ states.climate.downstairs.attributes.current_temperature <= 80 }}"

      - condition: template
        value_template: "{{ states.climate.upstairs.attributes.current_temperature <= 82 }}"

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'away'

      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'away'



#      ### changed to simple hold_mode instead of away on; preserving previous config here while testing...
#      - service: climate.set_away_mode
#        data:
#          entity_id: climate.downstairs
#          away_mode: 'on'
#
#      - service: climate.set_away_mode
#        data:
#          entity_id: climate.upstairs
#          away_mode: 'on'






