#####################################################################
### Set Climate to Sleep Mode at bedtime
#####################################################################
automation:
  - alias: Climate Sleep Mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: script.bedtime
        from: 'off'
        to: 'on'

      - platform: state
        entity_id: input_boolean.after_hours
        from: 'off'
        to: 'on'

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'sleep'

      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'sleep'