#####################################################################
### Set Climate to Resume when we return home
#####################################################################
automation:
  - alias: Climate Resume
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
      for:
        minutes: 2

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'home'

      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'home'

      - delay:
          minutes: 30

      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.downstairs
          resume_all: 'true'

      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.upstairs
          resume_all: 'true'