#####################################################################
### Automations to control Ecobee theromstat downstairs
### 
### 
###
automation:
#####################################################################
### Set Climate on away
#####################################################################
  - alias: Climate Downstairs Away Mode
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.away_mode

      - platform: state
        entity_id: group.door_sensors
        from: 'closed'
        to: 'open'
        for:
          minutes: 10

    condition:
      - condition: state
        entity_id: input_boolean.visitor_mode
        state: 'off'

    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.downstairs
          away_mode: 'on'


#####################################################################
### Sleep Mode On
#####################################################################
  - alias: Climate Downstairs Sleep Schedule
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: script.bedtime
        from: 'off'
        to: 'on'

    condition:
      - condition: template
        value_template: "{{ states.climate.downstairs.attributes.hold_mode != 'sleep' }}"

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'sleep'


#####################################################################
### Set Temperature upon return
#####################################################################
  - alias: Climate Downstairs Resume
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
      for:
        minutes: 2

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'home'

      - delay:
          minutes: 30

      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.downstairs
          resume_all: 'true'


#####################################################################
### Door held open too long
#####################################################################
  - alias: Climate Downstairs Door Held Open
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_held_open
        to: 'on'
        for:
          minutes: 5

    condition:
      - condition: template
        value_template: "{{ states.climate.downstairs.attributes.hold_mode != 'away' }}"

      - condition: state
        entity_id: binary_sensor.hvac_running
        state: 'on'

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'away'

      - service: script.tts_door_held_open


#####################################################################
### Door Held Restore
#####################################################################
  - alias: Door Held Restore Climate
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.door_held_open
        to: 'off'
        for:
          minutes: 1

    action:
      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.upstairs
          resume_all: 'true'

      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.downstairs
          resume_all: 'true'


#####################################################################
### Set min fan time for Summer
#####################################################################
  - alias: Set HVAC fan runtime summer
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Summer'

    action:
      - service: climate.ecobee_set_fan_min_on_time
        data:
          entity_id: climate.downstairs
          fan_min_on_time: '15'


#####################################################################
### Set min fan time for Winter
#####################################################################
  - alias: Set HVAC fan runtime winter
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Winter'

      - platform: state
        entity_id: sensor.season
        to: 'Awesome'

    action:
      - service: climate.ecobee_set_fan_min_on_time
        data:
          entity_id: climate.downstairs
          fan_min_on_time: '5'


#####################################################################
### Set away mode when weather is awesome
#####################################################################
  - alias: Climate Downstairs Away if Awesome Weather
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Awesome'

    condition:
      - condition: template
        value_template: "{{ states.climate.downstairs.attributes.current_temperature <= 80 }}"

    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.downstairs
          away_mode: 'on'




