#####################################################################
### Set min fan time for Summer
#####################################################################
automation:
  - alias: Set HVAC fan runtime summer
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Summer'

    action:
      - service: climate.ecobee_set_fan_min_on_time
        data:
          entity_id: climate.downstairs
          fan_min_on_time: '15'

      - service: climate.ecobee_set_fan_min_on_time
        data:
          entity_id: climate.upstairs
          fan_min_on_time: '30'


#####################################################################
### Set min fan time for Winter
#####################################################################
  - alias: Set HVAC fan runtime winter
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Winter'

      - platform: state
        entity_id: sensor.season
        to: 'Awesome'

    action:
      - service: climate.ecobee_set_fan_min_on_time
        data:
          entity_id: climate.downstairs
          fan_min_on_time: '5'

      - service: climate.ecobee_set_fan_min_on_time
        data:
          entity_id: climate.upstairs
          fan_min_on_time: '5'

