#####################################################################
### Game Room Lights
#####################################################################
automation:
  ### Trigger the game room lights on motion
  - alias: Game Room Lights On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_game_room
        to: 'on'

    condition:
      - condition: or
        conditions:
          - condition: time
            after: '16:30:00'
            before: '08:00:00'
          
          - condition: state
            entity_id: input_boolean.rain
            state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.billiards
          brightness: 185
          transition: 5


  ### Turn off the game room lights when no motion
  - alias: Game Room Lights Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_game_room
        to: 'off'
        for:
          minutes: 7

    condition:
      - condition: state
        entity_id: group.game_room_lights
        state: 'on'

    action:
      - service: homeassistant.turn_off
        entity_id: group.game_room_lights
