#####################################################################
### This automation protects the kid's car from over-charging
#####################################################################
automation:
  - alias: Car Charger Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.switch_four
        to: 'on'
        for:
          hours: 9

    action:
      - service: switch.turn_off
        entity_id: switch.switch_four
