#####################################################################
### Game Room Lights
#####################################################################
automation:
  ### Turn off the kid car charger to prevent over charging
  - alias: Car Charger Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.switch_four
        to: 'on'
        for:
          minutes: 60

    action:
      - service: switch.turn_off
        entity_id: switch.switch_four
