####################################################################
## Downstairs Bathroom Lights
####################################################################
automation:
  ### Set Presence Detection to ON
  - alias: Downstairs Bathroom Presence Detected
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_downstairs_bath
        to: 'on'

    mode: restart
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.downstairs_bath_presence


  ### Turn on the bathroom lights
  - alias: Downstairs Bathroom Lights On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_downstairs_bath
        to: 'on'

      - platform: state
        entity_id: sensor.bathroom_door_state
        to: 'Open'

    condition:
      - condition: or
        conditions:
          - condition: time
            after: '17:00:00'
            before: '08:30:00'
          
          - condition: state
            entity_id: input_boolean.rain
            state: 'on'

      - condition: state
        entity_id: switch.downstairs_bathroom_light
        state: 'off'

    action:
      - service: switch.turn_on
        data:
          entity_id: switch.downstairs_bathroom_light


  ### Set Presence Detection to OFF
  - alias: Downstairs Bathroom Vacant
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.downstairs_bath_presence
        to: 'off'
        for:
          minutes: 2

      - platform: state
        entity_id: switch.downstairs_bathroom_light
        to: 'off'

    condition:
      - condition: state
        entity_id: input_boolean.downstairs_bath_presence
        state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.downstairs_bath_presence


  ### Turn off the downstairs bathroom lights
  - alias: Downstairs Bathroom Lights Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.downstairs_bath_presence
        to: 'off'

    condition:
      - condition: state
        entity_id: switch.downstairs_bathroom_light
        state: 'on'

    action:
      - service: switch.turn_off
        data:
          entity_id: switch.downstairs_bathroom_light

