#####################################################################
### Living Room Lights - various automation/schedules
#####################################################################
automation:
  ### Always turn on the living room lamp at sunset
  - alias: Living Room Lamp On
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:20:00'

    condition: # condition added so this doesn't trigger if lights are lowered for watching tv later in the evening
      - condition: time
        before: '20:00:00'

    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_lamp
          brightness: 255
          transition: 60


  ### Set the Evening scene at sunset
  - alias: Evening Scene Schedule
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:10:00'

    condition: # condition added so this doesn't trigger if lights are lowered for watching tv later in the evening
      - condition: time
        before: '20:00:00'

      - condition: template
        value_template: "{{ states.media_player.apple_tv != 'playing' }}"

      - condition: or
        conditions:
          - condition: state
            entity_id: group.all_devices
            state: 'home'

          - condition: state
            entity_id: input_boolean.visitor_mode
            state: 'on'

    action:
      - service: scene.turn_on
        entity_id: scene.evening


  ### Turn off the living room lamp if we leave during the day
  - alias: Living Room Lamp Away
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.away_mode

    condition:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'

      - condition: state
        entity_id: light.living_room_lamp
        state: 'on'

    action:
      - service: light.turn_off
        entity_id: light.living_room_lamp


  ### Turn off the lights in the morning once sun is up high enough
  - alias: Living Room Off Morning
    initial_state: 'off'
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        above: 12

    condition:
      - condition: state
        entity_id: group.all_lights
        state: 'on'

      - condition: time
        before: '09:00:00'

      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'

      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'

    action:
      - service: timer.start
        entity_id: timer.sun_up

      - service: notify.mobile_app_rip8plus
        data:
          title: "Suns Up"
          message: "Lights off in 15 min..."
          data:
            push:
              sound:
                name: default


  ### Sun Up Timer Finish
  - alias: Sun Up Timer Finish
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.sun_up

    action:
      - service: script.sun_up


  ### Turn on some lights if we arrive home after sundown
  - alias: On Arrival Turn On Lights
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'

    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'

      - condition: state
        entity_id: input_boolean.visitor_mode
        state: 'off'

    action:
      - service: notify.mobile_app_rip8plus
        data:
          title: "Welcome Home"
          message: "Turning on some lights"
          data:
            push:
              sound: "US-EN-Alexa-Welcome-Home.wav"

      - service: scene.turn_on
        entity_id: scene.bright

      - service: homeassistant.turn_on
        entity_id: group.accent_lights

      - delay:
          minutes: 3

      - service: scene.turn_on
        entity_id: scene.evening

      - service: light.turn_off
        entity_id: light.kitchen_lights_level


  ### Turn on some lights when it is cloudy
  - alias: Living Room On Cloudy
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.rain
        from: 'off'
        to: 'on'

      - platform: template
        value_template: >-
          {% if is_state('sensor.dark_sky_summary', 'Rain') %}
            'true'
          {% elif is_state('sensor.dark_sky_summary', 'Thunderstorm') %}
            'true'
          {% elif is_state('sensor.dark_sky_summary', 'Showers') %}
            'true'
          {% elif is_state('sensor.dark_sky_summary', 'Drizzle') %}
            'true'
          {% elif is_state('sensor.dark_sky_summary', 'Mostly Cloudy') %}
            'true'
          {% else %}
            'false'
          {% endif %}


      - platform: numeric_state
        entity_id: sensor.dark_sky_precip_intensity
        above: 1

    condition:
      - condition: time
        after: '08:00:00'
        before: '17:00:00'

      - condition: state
        entity_id: group.all_devices
        state: 'home'

      - condition: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        above: 69

      - condition: numeric_state
        entity_id: sensor.illumination_front_entry
        below: 125

      - condition: template
        value_template: "{{ states.media_player.apple_tv.state != 'playing' }}"

    action:
      - service: scene.turn_on
        entity_id: scene.cloudy


  ### Turn off lights after rain has stopped
  - alias: Living Room Off Cloudy
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.dark_sky_precip_intensity
        below: 1

      - platform: state
        entity_id: input_boolean.rain
        from: 'on'
        to: 'off'

      - platform: numeric_state
        entity_id: sensor.illumination_front_entry
        above: 25

    condition:
      - condition: state
        entity_id: group.living_room
        state: 'on'

      - condition: numeric_state
        entity_id: sensor.illumination_front_entry
        above: 25

      - condition: time
        before: '17:00:00'

    action:
      - service: homeassistant.turn_off
        entity_id: group.living_room_lights

      - service: homeassistant.turn_off
        entity_id: group.entry_lights
