homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 387
  unit_system: imperial
  time_zone: America/Phoenix
  packages: !include_dir_named packages

  auth_providers:
   - type: homeassistant
   - type: trusted_networks
   - type: legacy_api_password

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  cors_allowed_origins: !secret cors

  trusted_networks:
    - !secret network_1
#    - !secret network_2
#    - !secret network_3
#    - !secret network_4

  ip_ban_enabled: true
  login_attempts_threshold: 5

system_health:

lovelace:
  mode: yaml

config:
discovery:
  ignore:
    - directv

sun:
history:

#python_script:
group: !include groups.yaml