homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 387
  unit_system: imperial
  time_zone: America/Phoenix
  packages: !include_dir_named packages

  auth_providers:
   - type: homeassistant

   - type: trusted_networks
     trusted_networks:
       - !secret network_1

   - type: legacy_api_password
     api_password: !secret http_password

config:

discovery:
  ignore:
    - directv

history:

http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  cors_allowed_origins: !secret cors
  ip_ban_enabled: true
  login_attempts_threshold: 3

lovelace:
  mode: yaml

mobile_app:

ios:

#python_script:

stream:

sun:

system_health:

zeroconf:


