homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 387
  unit_system: imperial
  time_zone: America/Phoenix
  external_url: !secret external_url
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - !secret trusted_network
  allowlist_external_dirs:
    - '/nvr'
    - '/snapshots'

default_config:
discovery:
frontend:
  themes: !include_dir_merge_named themes

## new nginx config; allow docker default ip ranges (may not need but will allow at first and test)



http:
#  use_x_forwarded_for: true
#  trusted_proxies:
#    - 172.16.0.0/12
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

ios:
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
