homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 387
  unit_system: imperial
  time_zone: America/Phoenix
  external_url: !secret external_url
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - !secret network_1

config:
discovery:
frontend:
  themes: !include_dir_merge_named themes

history:
http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

ios:
mobile_app:
my:
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
stream:
sun:
system_health:
zeroconf: