homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 387
  unit_system: imperial
  time_zone: America/Phoenix
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - !secret network_1

breaking_changes:
config:

discovery:
  ignore:
    - directv

frontend:
#  javascript_version: latest
  themes: !include_dir_merge_named themes

hacs:
  token: !secret hacs_token
  appdaemon: true
  python_script: true
  theme: true

history:

http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  cors_allowed_origins: !secret cors
  ip_ban_enabled: true
  login_attempts_threshold: 3

mobile_app:
#python_script:
scene: !include scenes.yaml
stream:
sun:
system_health:
zeroconf: