  ################################################
  ## Customize Cover - Roller Shades
  ################################################
homeassistant:
  customize:
    cover.kitchen_roller_shade_level:
      device_class: shade
      friendly_name: "Kitchen Rollershade"
#      homebridge_cover_type: rollershutter

    cover.kitchen_roller_shade_switch:
      hidden: true
      device_class: shade
      friendly_name: "Kitchen Rollershade State"

    cover.master_bath_roller_shades_level:
      device_class: shade
      friendly_name: "Master Bath Rollershades"
#      homebridge_cover_type: rollershutter

    cover.master_bath_roller_shades_switch:
      hidden: true
      device_class: shade
      friendly_name: "Master Bath Rollershade State"