#####################################################################
#   Scene Customizations
#####################################################################
homeassistant:
  customize:

    scene.morning:
      icon: mdi:weather-sunset-up