#####################################################################
#   Person Customizations
#####################################################################
homeassistant:
  customize:
    person.rick:
      entity_picture: /local/rick.jpg

    person.megs:
      entity_picture: /local/megs.jpg