#####################################################################
#   Battery Customizations
#####################################################################
homeassistant:
  customize:
    sensor.rip8plus_battery_level:
      friendly_name: "Rick's Phone Battery"
      icon_template: >-
        {% set battery_level = states('sensor.rip8plus_battery_level')|int('unknown') %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}

    sensor.mip8_battery_level:
      friendly_name: "Meg's Phone Battery"
      icon_template: >-
        {% set battery_level = states('sensor.mip8_battery_level')|int('unknown') %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}


#    sensor.lock_beach_battery:
#      friendly_name: "Bathroom Lock Battery"

#    sensor.dc_bathroom_battery:
#      friendly_name: "Bathroom Door Battery"

#    sensor.dc_front_door_battery:
#      friendly_name: "Front Door Battery"

#    sensor.dc_kitchen_door_battery:
#      friendly_name: "Kitchen Door Battery"

#    sensor.dc_south_door_battery:
#      friendly_name: "South Door Battery"

#    sensor.dc_office_door_battery:
#      friendly_name: "Office Door Battery"

#    sensor.dc_guest_balcony_door_battery:
#      friendly_name: "Guest Room Balcony Door Battery"

#    sensor.lock_south_battery:
#      friendly_name: "South Lock Battery"

#    sensor.ws_guest_room_window_battery:
#      friendly_name: "Guest Room Window Battery"

#    sensor.ws_living_room_north_window_battery:
#      friendly_name: "Living Room North Window Battery"

#    sensor.entry_multisensor_battery:
#      friendly_name: "Foyer Multisensor Battery"

#    sensor.motion_master_bedroom_battery:
#      friendly_name: "Master Bedroom Motion Battery"

#    sensor.motion_nursery_battery:
#      friendly_name: "Nursery Motion Battery"

#    sensor.motion_game_room_battery:
#      friendly_name: "Game Room Motion Battery"

#    sensor.downstairs_ac_leak_detector_battery:
#      friendly_name: "AC Leak Detector Battery"



