  ################################################
  ## Customize Sensor - Light Config
  ################################################
homeassistant:
  customize:
    sensor.time_brightness:
      hidden: true