#####################################################################
#   Switch Customizations
#####################################################################
homeassistant:
  customize:
## Etekcity 433MHz RF Switches - Names must be set here, as you cannont rename via UI
    switch.switch_one:
      friendly_name: "Upstairs Wipe Warmer"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_two:
      friendly_name: "Porch Christmas Lights"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_three:
      friendly_name: "Downstairs Wipe Warmer"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_four:
      friendly_name: "Power Wheels Charger"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_five:
      friendly_name: "Humidifier"
      assumed_state: false
      icon: mdi:cup-water


## these are subject to change for holidays, etc.
    switch.christmas_tree:
      icon: mdi:power-socket-us

    switch.staircase_christmas_lights:
      icon: mdi:power-socket-us


  ##########################################
  ## Switch Icon Customizations
  ##########################################
    switch.back_yard_outlet:
      icon: mdi:white-balance-incandescent

    switch.downstairs_bathroom_light:
      icon: mdi:white-balance-incandescent

    switch.fountains_switch:
      icon: mdi:beach

    switch.front_porch_lights_switch:
      icon: mdi:white-balance-incandescent

    switch.front_yard_outlet:
      icon: mdi:stocking

    switch.game_room_floodlights:
      icon: mdi:ceiling-light

    switch.kegerator:
      icon: mdi:power-socket-us

    switch.living_room_fan:
      icon: mdi:fan

    switch.master_bedroom_fan:
      icon: mdi:fan

    switch.mini_fridge:
      icon: mdi:power-socket-us

    switch.living_room_fan_light:
      assumed_state: false
      icon: mdi:ceiling-light

    switch.master_bedroom_fan_light:
      assumed_state: false
      icon: mdi:ceiling-light

    switch.nursery_lamp:
      icon: mdi:power-socket-us

    switch.outdoor_speakers:
      entity_picture: /local/music.ico

    switch.patio_light:
      icon: mdi:white-balance-incandescent

    switch.pool_light:
      icon: mdi:pool

    switch.south_porch_lights_switch:
      icon: mdi:white-balance-incandescent

    switch.staircase_lamp:
      icon: mdi:lamp

    switch.wine_room_lamp:
      icon: mdi:lamp

