################################################
## Customize Binary Sensors
################################################
homeassistant:
  customize:
    binary_sensor.rubino_online:
      friendly_name: "Rachio Station"

    binary_sensor.xiaomi_smart_button:
      friendly_name: "Smart Button"

#    binary_sensor.all_windows:
#      friendly_name: "All Windows"
#      entity_picture_template: >-
#        {% if is_state('binary_sensor.all_windows', 'on') %}
#          /local/red_shield.png
#        {% else %}
#          /local/green_shield.png
#        {% endif %}
#
#    binary_sensor.all_doors:
#      friendly_name: "All Doors"
#      entity_picture_template: >-
#        {% if is_state('binary_sensor.all_doors', 'on') %}
#           /local/red_shield.png
#        {% else %}
#           /local/green_shield.png
#        {% endif %}




