#####################################################################
#   Switch Customizations
#####################################################################
homeassistant:
  customize:
    switch.staircase_lamp:
      friendly_name: "Staircase Lamp"
      icon: mdi:lamp

    switch.wine_room_lamp:
      friendly_name: "Wine Room Lamp"
      icon: mdi:lamp

    switch.downstairs_bathroom_light:
      friendly_name: "Bathroom Lights"
      icon: mdi:white-balance-incandescent

    switch.fountains_switch:
      friendly_name: "Fountains"
      icon: mdi:beach

#    switch.front_yard_outlet:
#      friendly_name: "Front Christmas Lights"
#      icon: mdi:stocking
#
##    switch.back_yard_outlet:
##      friendly_name: "Party Lights"
##      icon: mdi:white-balance-incandescent

    switch.game_room_floodlights:
      friendly_name: "Game Room Floodlights"
      icon: mdi:ceiling-light

    switch.living_room_fan:
      icon: mdi:fan

    switch.living_room_fan_low:
      friendly_name: "Living Room Fan Low"

    switch.living_room_fan_medium:
      friendly_name: "Living Room Fan Medium"

    switch.living_room_fan_light:
      assumed_state: false
      icon: mdi:ceiling-light

    switch.master_bedroom_fan:
      friendly_name: "Master Bedroom Fan"
      icon: mdi:fan

    switch.master_bedroom_fan_light:
      assumed_state: false
      friendly_name: "Bedroom Fan Light"
      icon: mdi:ceiling-light

    switch.nursery_lamp:
      friendly_name: "Nursery Lamp"
      icon: mdi:power-socket-us

    switch.back_yard_outlet:
      friendly_name: "Party Lights"
      icon: mdi:white-balance-incandescent

    switch.patio_light:
      friendly_name: "Patio Lights"
      icon: mdi:white-balance-incandescent

    switch.pool_light:
      friendly_name: "Pool Light"
      icon: mdi:pool

    switch.south_porch_lights_switch:
      friendly_name: "South Porch Lights"
      icon: mdi:white-balance-incandescent

    switch.front_porch_lights_switch:
      friendly_name: "Front Porch Lights"
      icon: mdi:white-balance-incandescent

    switch.rubino_in_standby_mode:
      friendly_name: "Rachio Standby"

    switch.north_sprinklers_z1:
      friendly_name: "North Sprinklers"

    switch.northwest_sprinklers_z2:
      friendly_name: "Northwest Sprinklers"

    switch.northeast_sprinklers_z3:
      friendly_name: "Northeast Sprinklers"

    switch.east_sprinklers_z5:
      friendly_name: "East Sprinklers"

    switch.southeast_sprinklers_z6:
      friendly_name: "Southeast Sprinklers"

    switch.southwest_sprinklers_z7:
      friendly_name: "Southwest Sprinklers"

    switch.drip_and_citrus_trees_z4:
      friendly_name: "Drip Lines"

    switch.switch_one:
      friendly_name: "Upstairs Wipe Warmer"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_two:
      friendly_name: "Baby Monitor"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_three:
      friendly_name: "Downstairs Wipe Warmer"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_four:
      friendly_name: "Power Wheels Charger"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_five:
      friendly_name: "Humidifier"
      assumed_state: false
      icon: mdi:cup-water

    switch.flower_lamp:
      friendly_name: "Flower Lamp"
      icon: mdi:power-socket-us

    switch.floor_vase:
      friendly_name: "Floor Vase Lamp"
      icon: mdi:power-socket-us

    switch.outdoor_speakers:
      friendly_name: "Outdoor Speakers"
      entity_picture: /local/music.ico

    switch.mini_fridge:
      friendly_name: "Mini Fridge"
      icon: mdi:power-socket-us

    switch.kegerator:
      friendly_name: "Kegerator"
      icon: mdi:power-socket-us
