#####################################################################
#   Security Sensor Customizations
#####################################################################
homeassistant:
  customize:

    sensor.downstairs_ac_leak_detector:
      friendly_name: "Downstairs AC Leak Detector"
