#####################################################################
#   Switch Customizations
#####################################################################
homeassistant:
  customize:
## Etekcity 433MHz RF Switches - Names must be set here, as you cannont rename via UI
    switch.switch_one:
      friendly_name: "Upstairs Wipe Warmer"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_two:
      friendly_name: "Stairway Christmas Lights"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_three:
      friendly_name: "Downstairs Wipe Warmer"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_four:
      friendly_name: "Power Wheels Charger"
      assumed_state: false
      icon: mdi:power-socket-us

    switch.switch_five:
      friendly_name: "Humidifier"
      assumed_state: false
      icon: mdi:cup-water


  ##########################################
  ## Switch Icon Customizations
  ##########################################
    switch.fireplace:
      friendly_name: "Fireplace"
      assumed_state: true
      icon: mdi:power

    switch.living_room_fan:
      icon: mdi:fan

    switch.master_bedroom_fan:
      icon: mdi:fan

    switch.living_room_fan_light:
      assumed_state: false
      icon: mdi:ceiling-light

    switch.master_bedroom_fan_light:
      assumed_state: false
      icon: mdi:ceiling-light

    switch.staircase_lamp:
      icon: mdi:lamp

    switch.wine_room_lamp:
      icon: mdi:lamp

#    switch.outdoor_speakers:
#      entity_picture: /local/music.ico



