#####################################################################
### Kegerator Door Held Open Alarm
#####################################################################
automation:
  - alias: Kegerator Door Held Open
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.keg_door_held_open
        to: 'on'

    action:
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target:
            - media_player.kitchen
            - media_player.living_room
          message: "Attention, Please close the Kegerator door!"


      - service: notify.mobile_app_rip8plus
        data:
          title: "Kegerator Door Alarm!"
          message: "The Kegerator door is held open!"
          data:
            push:
              sound:
                name: default


  ### Kegerator Door Restoral
  - alias: Kegerator Door Restoral
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: binary_sensor.keg_door_held_open
        from: 'on'
        to: 'off'

    action:
      - service: media_player.volume_set
        entity_id: media_player.kitchen
        data_template:
          volume_level: "{{ states('sensor.alexa_volume') }}"

      - service: notify.mobile_app_rip8plus
        data:
          title: "Kegerator Restored"
          message: "Thanks for closing the door."
          data:
            push:
              sound:
                name: default

