#####################################################################
### Living Room Fan Morning
#####################################################################
automation:
  ### Living Room Ceiling Fan Morning
  - alias: Living Room Ceiling Fan Morning
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: script.morning_sequence
        to: 'on'

    condition:
      - condition: template
        value_template: "{{ states.climate.downstairs.attributes.current_temperature >= 78 }}"

    action:
      - service: switch.turn_on
        entity_id: switch.living_room_fan

