#####################################################################
### Automations for Living Room TV input select
#####################################################################
automation:
  ### Living Room TV Input Select
  - alias: Living Room TV Select Input
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.living_room_tv_input

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

    action:
      - service: switch.turn_on
        data_template:
          entity_id: "switch.tv_input_{{ trigger.to_state.state|lower }}"

# Reset the Input Select to "Select an option..."
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...
