#####################################################################
### Living Room Lamp Automation
#####################################################################
automation:
  ### Always turn on the living room lamp at sunset
  - alias: Living Room Lamp On
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:20:00'

    condition: # condition added so this doesn't trigger if lights are lowered for watching tv later in the evening
      - condition: time
        before: '20:00:00'

    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_lamp
          brightness: 255
          transition: 60


  ### Turn off the living room lamp if we leave during the day
  - alias: Living Room Lamp Away
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.away_mode

    condition:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'

      - condition: state
        entity_id: light.living_room_lamp
        state: 'on'

    action:
      - service: light.turn_off
        entity_id: light.living_room_lamp

