################################################################
## Sensor
################################################################
sensor:
  ### Time Based Brightness
  - platform: template
    sensors:
      time_brightness:
        value_template: >-
          {%- if now().strftime('%H%M')|int < 600 -%}
            64
          {%- elif now().strftime('%H%M')|int < 700 -%}
            128
          {%- elif now().strftime('%H%M')|int < 900 -%}
            192
          {%- elif now().strftime('%H%M')|int < 2000 -%}
            255
          {%- elif now().strftime('%H%M')|int < 2200 -%}
            192
          {%- elif now().strftime('%H%M')|int < 2300 -%}
            128
          {%- else -%}
            64
          {%- endif -%}
        entity_id: sensor.time