#####################################################################
### Upstairs climate-related sensors
#####################################################################
sensor:
  - platform: template
    sensors:
      us_avg_temp:
        friendly_name: "Upstairs Average Temperature"
        unit_of_measurement: "째F"
        device_class: temperature
        value_template: >-
          {{ ((float(states.sensor.upstairs_temperature.state) + float(states.sensor.nursery_temperature.state) + float(states.sensor.guest_room_temperature.state)) / 3) | round(1) }}
        entity_id: sensor.time


  - platform: template
    sensors:
      us_climate_current_temp:
        friendly_name: "Upstairs AC Temperature"
        unit_of_measurement: "째F"
        device_class: temperature
        value_template: "{{ (states.climate.upstairs.attributes|default({})).current_temperature|default('unknown') }}"
        entity_id: sensor.time

  - platform: template
    sensors:
      us_climate_preset:
        friendly_name: "Active Preset"
        value_template: "{{ (states.climate.upstairs.attributes|default({})).preset_mode|default('unknown') }}"
        entity_id: sensor.time

#  - platform: template
#    sensors:
#      us_climate_mode:
#        friendly_name: "Active Schedule"
#        value_template: "{{ (states.climate.upstairs.attributes|default({})).climate_mode|default('unknown') }}"
#        entity_id: sensor.time

  - platform: template
    sensors:
      us_climate_target_high:
        friendly_name: "Upstairs AC Setpoint"
        unit_of_measurement: "째F"
        device_class: temperature
        value_template: "{{ (states.climate.upstairs.attributes|default({})).target_temp_high|default('unknown') }}"
        entity_id: sensor.time

  - platform: template
    sensors:
      us_climate_target_low:
        friendly_name: "Upstairs Heat Setpoint"
        unit_of_measurement: "째F"
        device_class: temperature
        value_template: "{{ (states.climate.upstairs.attributes|default({})).target_temp_low|default('unknown') }}"
        entity_id: sensor.time

  - platform: template
    sensors:
      us_fan_state:
        friendly_name: "Upstairs HVAC Fan"
        value_template: "{{ (states.climate.upstairs.attributes|default({})).fan|default('unknown') }}"
        entity_id: sensor.time


