#####################################################################
### Window Sensors
#####################################################################
sensor:
### Living Room North Window Status
  - platform: template
    sensors:
      living_room_north_window_state:
        value_template: >-
          {% set state = states('sensor.living_room_north_window') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Living Room N. Window"
        icon_template: >-
          {% set state = states('sensor.living_room_north_window_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi: window-closed
          {% else %}
            {% if state == 'Open' %}
              mdi:window-open
            {% else %}
              mdi:window-closed
            {% endif %}
          {% endif %}


### Living Room North Window Tamper
  - platform: template
    sensors:
      living_room_north_window_tamper:
        value_template: >-
          {% set state = states('sensor.living_room_north_window_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}
        friendly_name: "Living Room N. Window Tamper"


### Guest Room Window Status
  - platform: template
    sensors:
      guest_room_window_state:
        value_template: >-
          {% set state = states('sensor.guest_room_window') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Guest Room Window"
        icon_template: >-
          {% set state = states('sensor.guest_room_window_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi: window-closed
          {% else %}
            {% if state == 'Open' %}
              mdi:window-open
            {% else %}
              mdi:window-closed
            {% endif %}
          {% endif %}


### Guest Room Window Tamper
  - platform: template
    sensors:
      guest_room_window_tamper:
        value_template: >-
          {% set state = states('sensor.guest_room_window_sensor_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}
        friendly_name: "Guest Room Window Tamper"


### Master Bedroom Northwest Window
  - platform: template
    sensors:
      master_bedroom_northwest_window_state:
        value_template: >-
          {% set state = states('binary_sensor.master_window_northwest') %}
          {% if state == 'on' %}
            Open
          {% else %}
            Closed
          {% endif %}
        friendly_name: "Master Bedroom Northwest Window"
        icon_template: >-
          {% set state = states('binary_sensor.master_window_northwest')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi: window-closed
          {% else %}
            {% if state == 'on' %}
              mdi:window-open
            {% else %}
              mdi:window-closed
            {% endif %}
          {% endif %}


### Master Bedroom Southwest Window
  - platform: template
    sensors:
      master_bedroom_southwest_window_state:
        value_template: >-
          {% set state = states('binary_sensor.master_window_southwest') %}
          {% if state == 'on' %}
            Open
          {% else %}
            Closed
          {% endif %}
        friendly_name: "Master Bedroom Southwest Window"
        icon_template: >-
          {% set state = states('binary_sensor.master_window_southwest')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi: window-closed
          {% else %}
            {% if state == 'on' %}
              mdi:window-open
            {% else %}
              mdi:window-closed
            {% endif %}
          {% endif %}
