#####################################################################
### Master Bedroom Ceiling Fan Control via temperature
#####################################################################
sensor:
  ### Master Bedroom Fan Temp Setting
  - platform: template
    sensors:
      master_bedroom_fan_speed:
        friendly_name: "Master Bedroom Fan Speed"
        value_template: >-
          {% set temperature = states('sensor.upstairs_temperature') | float(76.2) %}
          {% if 74.5 <= temperature <=76.0 %}
            1
          {% elif 76.1 <= temperature <=77.4 %}
            2
          {% elif 77.5 <= temperature <=80.5 %}
            4
          {% elif temperature > 80.5 %}
            5
          {% else %}
            Off
          {% endif %}

## for sensor.upstairs_temperature the trigger for speed 4 should be 77.5