#####################################################################
### Ring Doorbell Sensors
#####################################################################
sensor:
  - platform: ring
    monitored_conditions:
      - last_ding
      - last_motion
      - wifi_signal_strength

