#####################################################################
### Sensor - Fibaro Motion Detector status
#####################################################################
sensor:
  - platform: template
    sensors:
      front_entry_motion:
        friendly_name: "Front Entry Motion"
        icon_template: mdi:motion-sensor
        value_template: >-
          {% set state = states('binary_sensor.front_entry_fibaro_multisensor') %}
          {% if state == 'off' %}
            Clear
          {% elif state == 'on' %}
            Detected
          {% else %}
            {{ state|title }}
          {% endif %}