#####################################################################
### Weather Sensors by Darksky
#####################################################################
sensor:
  - platform: darksky
    api_key: !secret forecast_api_key
    forecast:
      - 0
      - 1
      - 2
      - 3

    monitored_conditions:
      - summary
      - icon
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - dew_point
      - wind_speed
      - wind_gust
      - wind_bearing
      - humidity
      - pressure
      - uv_index
      - nearest_storm_distance
      - cloud_cover
      - daily_summary
      - hourly_summary
      - minutely_summary
      - precip_probability
      - precip_intensity
