#####################################################################
### TP-LINK Outlets - Power Consumption Sensors
#####################################################################
sensor:
## TP-LINK Outlet Usage: Outdoor Speakers
  - platform: template
    sensors:
      outdoor_speakers_amps:
        friendly_name_template: "{{ states.switch.outdoor_speakers.name}} Current"
        value_template: '{{ states.switch.outdoor_speakers.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      outdoor_speakers_watts:
        friendly_name_template: "{{ states.switch.outdoor_speakers.name}} Current Consumption"
        value_template: '{{ states.switch.outdoor_speakers.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      outdoor_speakers_total_kwh:
        friendly_name_template: "{{ states.switch.outdoor_speakers.name}} Total Consumption"
        value_template: '{{ states.switch.outdoor_speakers.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      outdoor_speakers_volts:
        friendly_name_template: "{{ states.switch.outdoor_speakers.name}} Voltage"
        value_template: '{{ states.switch.outdoor_speakers.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      outdoor_speakers_today_kwh:
        friendly_name_template: "{{ states.switch.outdoor_speakers.name}} Today's Consumption"
        value_template: '{{ states.switch.outdoor_speakers.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'


## TP-LINK Outlet Usage: Flower Lamp
  - platform: template
    sensors:
      christmas_tree_amps:
        friendly_name_template: "{{ states.switch.office_spare.name}} Current"
        value_template: '{{ states.switch.office_spare.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      christmas_tree_watts:
        friendly_name_template: "{{ states.switch.office_spare.name}} Current Consumption"
        value_template: '{{ states.switch.office_spare.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      christmas_tree_total_kwh:
        friendly_name_template: "{{ states.switch.office_spare.name}} Total Consumption"
        value_template: '{{ states.switch.office_spare.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      christmas_tree_volts:
        friendly_name_template: "{{ states.switch.office_spare.name}} Voltage"
        value_template: '{{ states.switch.office_spare.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      christmas_tree_today_kwh:
        friendly_name_template: "{{ states.switch.office_spare.name}} Today's Consumption"
        value_template: '{{ states.switch.office_spare.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'


## TP-LINK Outlet Usage: Kegerator
  - platform: template
    sensors:
      kegerator_amps:
        friendly_name_template: "{{ states.switch.kegerator.name}} Current"
        value_template: '{{ states.switch.kegerator.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      kegerator_watts:
        friendly_name_template: "{{ states.switch.kegerator.name}} Current Consumption"
        value_template: '{{ states.switch.kegerator.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      kegerator_total_kwh:
        friendly_name_template: "{{ states.switch.kegerator.name}} Total Consumption"
        value_template: '{{ states.switch.kegerator.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      kegerator_volts:
        friendly_name_template: "{{ states.switch.kegerator.name}} Voltage"
        value_template: '{{ states.switch.kegerator.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
#      kegerator_today_kwh:
#        friendly_name_template: "{{ states.switch.kegerator.name}} Today's Consumption"
#        value_template: '{{ states.switch.kegerator.attributes["today_energy_kwh"] | float }}'
#        unit_of_measurement: 'kWh'


## TP-LINK Outlet Usage: Nursery Lamp
  - platform: template
    sensors:
      nursery_lamp_amps:
        friendly_name_template: "{{ states.switch.nursery_lamp.name}} Current"
        value_template: '{{ states.switch.nursery_lamp.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      nursery_lamp_watts:
        friendly_name_template: "{{ states.switch.nursery_lamp.name}} Current Consumption"
        value_template: '{{ states.switch.nursery_lamp.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      nursery_lamp_total_kwh:
        friendly_name_template: "{{ states.switch.nursery_lamp.name}} Total Consumption"
        value_template: '{{ states.switch.nursery_lamp.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      nursery_lamp_volts:
        friendly_name_template: "{{ states.switch.nursery_lamp.name}} Voltage"
        value_template: '{{ states.switch.nursery_lamp.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
#      nursery_lamp_today_kwh:
#        friendly_name_template: "{{ states.switch.nursery_lamp.name}} Today's Consumption"
#        value_template: '{{ states.switch.nursery_lamp.attributes["today_energy_kwh"] | float }}'
#        unit_of_measurement: 'kWh'


