#####################################################################
### Entry Door Sensors
#####################################################################
sensor:
### Front Door Status
  - platform: template
    sensors:
      front_door_state:
        value_template: >-
          {% set state = states('sensor.front_door_contact_access_control') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Front Door"
        icon_template: >-
          {% set state = states('sensor.front_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### Front Door Tamper
  - platform: template
    sensors:
      front_door_tamper:
        value_template: >-
          {% set state = states('sensor.front_door_contact_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


### South Door Status
  - platform: template
    sensors:
      south_door_state:
        value_template: >-
          {% set state = states('sensor.south_door_contact_access_control') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "South Door"
        icon_template: >-
          {% set state = states('sensor.south_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### South Door Tamper
  - platform: template
    sensors:
      south_door_tamper:
        value_template: >-
          {% set state = states('sensor.south_door_contact_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


### Kitchen Door Status
  - platform: template
    sensors:
      kitchen_door_state:
        value_template: >-
          {% set state = states('sensor.kitchen_door_access_control') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Kitchen Door"
        icon_template: >-
          {% set state = states('sensor.kitchen_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### Kitchen Door Tamper
  - platform: template
    sensors:
      kitchen_door_tamper:
        value_template: >-
          {% set state = states('sensor.kitchen_door_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


### Bathroom Door Status
  - platform: template
    sensors:
      bathroom_door_state:
        value_template: >-
          {% set state = states('sensor.bathroom_door_contact_access_control') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Bathroom Door"
        icon_template: >-
          {% set state = states('sensor.bathroom_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### Bathroom Door Tamper
  - platform: template
    sensors:
      bathroom_door_tamper:
        value_template: >-
          {% set state = states('sensor.bathroom_door_contact_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


### Office Door Status
  - platform: template
    sensors:
      office_door_state:
        value_template: >-
          {% set state = states('sensor.office_door_contact_access_control') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Office Door"
        icon_template: >-
          {% set state = states('sensor.office_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### Office Door Tamper
  - platform: template
    sensors:
      office_door_tamper:
        value_template: >-
          {% set state = states('sensor.office_door_contact_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


### Guest Room Balcony Door Status
  - platform: template
    sensors:
      guest_room_balcony_door_state:
        value_template: >-
          {% set state = states('sensor.guest_room_balcony_door') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Guest Room Balcony Door"
        icon_template: >-
          {% set state = states('sensor.guest_room_balcony_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### Guest Room Balcony Door Tamper
  - platform: template
    sensors:
      guest_room_balcony_door_tamper:
        value_template: >-
          {% set state = states('sensor.guest_room_balcony_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


