#####################################################################
### Battery Sensors
#####################################################################
sensor:
  - platform: template
    sensors:
      ### Beach Lock Battery
      lock_bathroom_battery:
        friendly_name: "Bathroom Lock Battery"
        value_template: "{{ (states.zwave.bathroom_entry.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery


      ### South Lock Battery
      lock_south_battery:
        friendly_name: "South Lock Battery"
        value_template: "{{ (states.zwave.south_entry.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery


      ### Front entry Fibaro Multisensor Battery
      entry_multisensor_battery:
        friendly_name: "Foyer Multisensor Battery"
        value_template: "{{ (states.zwave.front_entry_fibaro_multisensor.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery


      ### Game Room Motion Battery
      motion_game_room_battery:
        friendly_name: "Game Room Motion Battery"
        value_template: "{{ (states.binary_sensor.motion_game_room.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery


      ### Downstairs Bathroom Motion Battery
      motion_downstairs_bath_battery:
        friendly_name: "Downstairs Bathroom Motion Battery"
        value_template: "{{ (states.binary_sensor.motion_downstairs_bath.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery


      ### Master Bedroom Motion Battery
      motion_master_bedroom_battery:
        friendly_name: "Master Bedroom Motion Battery"
        value_template: "{{ (states.binary_sensor.motion_master_bedroom.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery


      ### Master Bedroom Bed Motion Battery
      motion_master_bedroom_bed_battery:
        friendly_name: "Master Bed Motion Battery"
        value_template: "{{ (states.binary_sensor.motion_master_bedroom_bed.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery


      ### Nursery Motion Battery
      motion_nursery_battery:
        friendly_name: "Nursery Motion Battery"
        value_template: "{{ (states.binary_sensor.motion_nursery.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery


      ### Downstairs AC Leak Detector Battery
      downstairs_ac_leak_detector_battery:
        friendly_name: "AC Leak Detector Battery"
        value_template: "{{ (states.zwave.downstairs_ac_leak_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        device_class: battery

