#####################################################################
### Sensor
#####################################################################

### Amcrest Camera Sensors
sensor:
  - platform: amcrest