#####################################################################
### Sensor
#####################################################################
sensor:
### Kegerator Door Status
  - platform: template
    sensors:
      kegerator_door_state:
        value_template: >-
          {% set state = states('binary_sensor.kegerator_door') %}
          {% if state == 'on' %}
            Open
          {% elif state == 'off' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Kegerator Door"
        icon_template: >-
          {% set state = states('sensor.kegerator_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}

