#####################################################################
### Downstairs climate-related sensors
#####################################################################
sensor:
  - platform: template
    sensors:
      ds_avg_temp:
        friendly_name: "Downstairs Average Temperature"
        unit_of_measurement: "째F"
        value_template: >-
          {{ ((float(states.sensor.downstairs_temperature.state) + float(states.sensor.living_room_temperature.state) + float(states.sensor.entryway_temperature.state) + float(states.sensor.office_temperature.state) + float(states.sensor.front_entry_fibaro_multisensor_temperature.state) + float(states.sensor.broadlink_sensor_temperature.state)) / 6) | round(1) }}


  - platform: template
    sensors:
      ds_climate_current_temp:
        friendly_name: "Downstairs AC Temperature"
        unit_of_measurement: "째F"
        value_template: "{{ (states.climate.downstairs.attributes|default({})).current_temperature|default('unknown') }}"
        entity_id: sensor.time

  - platform: template
    sensors:
      ds_climate_hold:
        friendly_name: "Manual Override"
        value_template: "{{ (states.climate.downstairs.attributes|default({})).hold_mode|default('unknown') }}"
        entity_id: sensor.time

  - platform: template
    sensors:
      ds_climate_away:
        friendly_name: "Away Mode"
        value_template: "{{ (states.climate.downstairs.attributes|default({})).away_mode|default('unknown') }}"
        entity_id: sensor.time

  - platform: template
    sensors:
      ds_climate_mode:
        friendly_name: "Active Schedule"
        value_template: "{{ (states.climate.downstairs.attributes|default({})).climate_mode|default('unknown') }}"
        entity_id: sensor.time

  - platform: template
    sensors:
      ds_climate_target_high:
        friendly_name: "Downstairs AC Setpoint"
        unit_of_measurement: "째F"
        value_template: "{{ (states.climate.downstairs.attributes|default({})).target_temp_high|default('unknown') }}"
        entity_id: sensor.time

  - platform: template
    sensors:
      ds_climate_target_low:
        friendly_name: "Downstairs Heat Setpoint"
        unit_of_measurement: "째F"
        value_template: "{{ (states.climate.downstairs.attributes|default({})).target_temp_low|default('unknown') }}"
        entity_id: sensor.time

  - platform: template
    sensors:
      ds_fan_state:
        friendly_name: "Downstairs HVAC Fan"
        value_template: "{{ (states.climate.downstairs.attributes|default({})).fan|default('unknown') }}"
        entity_id: sensor.time


  ################################################
  ## Sensor - Broadlink RM 2 Pro
  ################################################
  - platform: broadlink
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    monitored_conditions:
      - 'temperature'
