#####################################################################
### Automation Humidor Light
#####################################################################
automation:
  - alias: Humidor Low
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.humidor_low
        to: 'on'

    action:
      - service: light.turn_on
        entity_id: light.sn1_led
        data:
          brightness: 255
          color_name: "red"

#      - service: notify.mobile_app_rip8plus
#        data:
#          title: "Refill Humidor"
#          message: "Humidor is at {{ states('sensor.sn1_humidity') }}% refill soon!"
#          data:
#            push:
#              sound:
#                name: default


  - alias: Humidor OK
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.humidor_low
        to: 'off'

    action:
      - service: light.turn_on
        entity_id: light.sn1_led
        data:
          brightness: 255
          color_name: "green"

#      - delay:
#          minutes: 15
#
#      - service: light.turn_off
#        entity_id: light.sn1_led

