#####################################################################
### Automation Humidor Light
#####################################################################
automation:
  - alias: Humidor Low
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.humidor_low
        to: 'on'

    action:
      - service: light.turn_on
        entity_id: light.sn1_led
        data:
          brightness: 255
          color_name: "red"


  - alias: Humidor OK
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.humidor_low
        to: 'off'

    action:
      - service: light.turn_on
        entity_id: light.sn1_led
        data:
          brightness: 255
          color_name: "green"
