#####################################################################
### Nursery Ceiling Fan Automations
#####################################################################
automation:
  ### Turn on the nursery fan if it's warm
  - alias: Nursery Fan On
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: binary_sensor.nursery_presence
        to: 'on'

    condition:
      - condition: state
        entity_id: fan.nursery_fan
        state: 'off'

      - condition: template
        value_template: "{{ states('sensor.nursery_fan_speed') != 'off' }}"

    action:
      ## may be able to simplify and remove this first one...test.
      - service: fan.turn_on
        entity_id: fan.nursery_fan

      - service: fan.set_speed
        entity_id: fan.nursery_fan
        data_template:
          speed: "{{ states('sensor.nursery_fan_speed') }}"


  ### Set Nursery Fan Speed Automatically
  - alias: Nursery Fan Auto Speed Select
    initial_state: 'on'
     
    trigger:
      - platform: time_pattern
        minutes: '/10'

    condition:
      - condition: state
        entity_id: input_boolean.nursery_fan_hold
        state: 'off'

      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.nursery_presence
            state: 'on'

          - condition: time
            after: '19:30:00'
            before: '08:30:00'

    action:
      - service: fan.set_speed
        entity_id: fan.nursery_fan
        data_template:
          speed: "{{ states('sensor.nursery_fan_speed') }}"

#      - service: logbook.log
#        data_template:
#          name: "Nursery Fan Speed"
#          message: "changed to {{ states('sensor.nursery_fan_speed') }}."



