#####################################################################
### Schedule the baby wipe warmers
#####################################################################
automation:
  ### downstairs wipe warmer schedule ON
  - alias: Downstairs Wipe Warmer On
    initial_state: 'on'
     
    trigger:
      - platform: time
        at: '07:25:00'

      - platform: template
        value_template: "{{ states('sensor.living_room_temperature') <= '77' }}"

      - platform: state
        entity_id: group.all_devices
        from: 'not_home'
        to: 'home'
        for:
          minutes: 5

    condition:
      - condition: state
        entity_id: sensor.season
        state: 'Winter'

      - condition: state
        entity_id: group.all_devices
        state: 'home'

      - condition: template
        value_template: "{{ states('sensor.living_room_temperature') < '77.5' }}"

      - condition: time
        before: '21:05:00'
        after: '07:20:00'

      - condition: state
        entity_id: switch.switch_three
        state: 'off'

    action:
      - service: switch.turn_on
        entity_id: switch.switch_three


  ### downstairs wipe warmer schedule OFF
  - alias: Downstairs Wipe Warmer Off
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: script.bedtime
        from: 'off'
        to: 'on'

      - platform: template
        value_template: "{{ states('sensor.living_room_temperature') > '78' }}"

      - platform: time
        at: '21:05:59'

    condition:
      - condition: state
        entity_id: switch.switch_three
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.switch_three


  - alias: Upstairs Wipe Warmer On
    initial_state: 'on'
     
    trigger:
      - platform: time
        at: '20:00:00'

      - platform: template
        value_template: "{{ states('sensor.nursery_temperature') <= '77' }}"

      - platform: state
        entity_id: script.nap_time
        to: 'on'

      - platform: state
        entity_id: group.all_devices
        from: 'not_home'
        to: 'home'
        for:
          minutes: 5

    condition:
      - condition: state
        entity_id: sensor.season
        state: 'Winter'

      - condition: state
        entity_id: group.all_devices
        state: 'home'

      - condition: template
        value_template: "{{ states('sensor.nursery_temperature') < '77.5' }}"

      - condition: state
        entity_id: switch.switch_one
        state: 'off'

    action:
      - service: switch.turn_on
        entity_id: switch.switch_one


  ### upstairs wipe warmer schedule OFF
  - alias: Upstairs Wipe Warmer Off
    initial_state: 'on'
     
    trigger:
      - platform: time
        at: '09:00:59'

      - platform: template
        value_template: "{{ states('sensor.nursery_temperature') >= '78' }}"

    condition:
      - condition: state
        entity_id: switch.switch_one
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.switch_one

