#####################################################################
### Nursery Presence Detection 2.0
#####################################################################
automation:
  ### assume the nursery is vacant after 45 min of inactivity
  - alias: Nursery Unoccupied
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: binary_sensor.nursery_presence
        to: 'off'
        for:
          minutes: 5

    condition:
      - condition: time
        after: '07:00:00'
        before: '19:00:00'

    action:
      - service: fan.turn_off
        entity_id: fan.nursery_fan

      - service: homeassistant.turn_off
        entity_id: group.nursery_lights

      - service: switch.turn_off
        entity_id: switch.switch_one


