#####################################################################
### Nursery Humidifier Automation
#####################################################################
automation:
  ### Turn off the humidifier
  - alias: Nursery Humidifier Off
    initial_state: 'on'
     
    trigger:
      platform: time
      at: '00:08:00'

    condition:
      - condition: state
        entity_id: switch.switch_five
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.switch_five

