#####################################################################
### Amazon Dasher event handler automations
#####################################################################
automation:
  ### Begin bedtime countdown when Dasher Wellness is pressed
  - alias: Dasher Bedtime Timer
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer_bedtime

    action:
      - service: timer.start
        entity_id: timer.bedtime


  ### Turn on Master Bedroom Night Time scene when Laundress Dash button is pressed
  - alias: Dasher Night Time
    initial_state: 'on'
    trigger:
      platform: event
      event_type: script_night_time

    action:
      - service: script.turn_on
        entity_id: script.master_bedroom_night_time


  ### Turn on the Baby Playlist in the Nursery when Puracy Dash button is pressed
  - alias: Dasher Baby Playlist
    initial_state: 'on'
    trigger:
      platform: event
      event_type: script_baby_playlist

    action:
      - service: script.turn_on
        entity_id: script.baby_playlist


  ### Test script when Dude Dash button is pressed
  - alias: Dasher Test
    initial_state: 'on'
    trigger:
      platform: event
      event_type: script_test

    action:
      - service: script.turn_on
        entity_id: script.script_test

