####################################################################
## Laundry Room Lights
####################################################################
automation:
  ### Set Presence Detection to ON
  - alias: Laundry Room Presence Detected
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_laundry_room
        to: 'on'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.laundry_room_presence


  ### Set Presence Detection to OFF
  - alias: Laundry Room Vacant
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_laundry_room
        to: 'off'
        for:
          seconds: 30

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.laundry_room_presence


  ### Turn on the laundry room lights when presence is detected
  - alias: Laundry Room Lights On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.laundry_room_presence
        to: 'on'

    condition:
      - condition: state
        entity_id: light.laundry_room
        state: 'off'

    action:
      - service: light.turn_on
        data:
          entity_id: light.laundry_room


  ### Turn off the laundry room lights
  - alias: Laundry Room Lights Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.laundry_room_presence
        to: 'off'

    condition:
      - condition: state
        entity_id: light.laundry_room
        state: 'on'

    action:
      - service: light.turn_off
        data:
          entity_id: light.laundry_room

