
  ###################################################################
  ### Aeotec zwave Minimote #1: zwave.family_room_minimote
  #####
  ###    short                       long
  ###  1 scene.evening    scene.bright
  ###  2 scene.movie_time            scene.dim
  ###  3 kitchen_lights on 50%       kitchen_lights on 100%
  ###  4 kitchen_lights off          script.bedtime
  ###################################################################
automation:
  - alias: Minimote 1 Button 1 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 1

    action:
      - service: scene.turn_on
        entity_id: scene.evening

  ###
  - alias: Minimote 1 Button 1 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 2

    action:
      - service: scene.turn_on
        entity_id: scene.bright

  ###
  - alias: Minimote 1 Button 2 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 3

    action:
      - service: scene.turn_on
        entity_id: scene.movie_time

      - service: light.turn_off
        entity_id: light.kitchen_lights

  ###
  - alias: Minimote 1 Button 2 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 4

    action:
      - service: scene.turn_on
        entity_id: scene.dim

  ###
  - alias: Minimote 1 Button 3 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 5

    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_lights
          transition: 5
          brightness: 150

  ###
  - alias: Minimote 1 Button 3 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 6

    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_lights
          transition: 5
          brightness: 255

  ###
  - alias: Minimote 1 Button 4 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 7

    action:
      - service: light.turn_off
        data:
          entity_id: light.kitchen_lights

  ###
  - alias: Minimote 1 Button 4 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 8

    action:
      - service: script.bedtime


  ###################################################################
  ### Aeotec zwave Minimote #3: zwave.master_br_minimote
  #####
  ###    short                       long
  ###  1 mbr dim                    mbr bright
  ###  2 bath dim
  ###  3 
  ###  4 
  ###################################################################
  - alias: Minimote 3 Button 1 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 1

    action:
      - service: light.turn_on
        data:
          entity_id: light.under_bed_lights

      - service: hue.hue_activate_scene
        data:
          group_name: "Master Bathroom"
          scene_name: "Morning"

      - service: light.turn_on
        data:
          entity_id: light.foyer_lights
          brightness: 50

  ###
  - alias: Minimote 3 Button 1 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 2

    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_chandelier

      - service: light.turn_off
        data:
          entity_id: light.under_bed_lights

  ###
  - alias: Minimote 3 Button 2 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 3

    action:
      - service: script.mbr_night_light

  ###
  - alias: Minimote 3 Button 2 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 4

    action:
      - service: script.bedtime

  ###
  - alias: Minimote 3 Button 3 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 5

    action:
      - service: switch.turn_on
        data:
          entity_id: switch.master_bedroom_fan

  ###
  - alias: Minimote 3 Button 3 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 6

# set fan speed to 2
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_bedroom_fan_speed
          option: 2

  ###
  - alias: Minimote 3 Button 4 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 7

    action:
      - service: switch.turn_off
        data:
          entity_id: switch.master_bedroom_fan

  ###
  - alias: Minimote 3 Button 4 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 8

    action:
      - service: scene.turn_on
        data:
          entity_id: scene.early_morning


  ### Aeotec zwave Minimote #3: aeotec_dsa03202_Minimote_31
