#####################################################################
#  RF Switch Automation - Saves Switch State to MQTT
#####################################################################
automation:
  - alias: RF Switches State Save
    initial_state: 'on'
     
    trigger:
      platform: state
      entity_id: switch.switch_one, switch.switch_two, switch.switch_three, switch.switch_four, switch.switch_five

    action:
      service: mqtt.publish
      data_template:
        topic: "/home/rfswitches/{{ trigger.entity_id.split('.')[1] }}"
        retain: true
        qos: 1
        payload: '{{ trigger.to_state.state }}'


#####################################################################
# Startup event - restores states of dropdowns, and RF Switches...etc
#####################################################################
  - alias: RF Switch State Restore
    initial_state: 'on'
     
    trigger:
      platform: homeassistant
      event: start

    action:
      - delay:
          minutes: 1
      - service_template: >
          {%- if states.sensor.rf_switch_one.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.switch_one
      - service_template: >
          {%- if states.sensor.rf_switch_two.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.switch_two
      - service_template: >
          {%- if states.sensor.rf_switch_three.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.switch_three
      - service_template: >
          {%- if states.sensor.rf_switch_four.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.switch_four
      - service_template: >
          {%- if states.sensor.rf_switch_five.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}
        data:
          entity_id: switch.switch_five


