#####################################################################
### Binary Sensor: if any door is not closed, turn on
#####################################################################
binary_sensor:
  - platform: template
    sensors:
      all_doors:
        friendly_name: "All Doors"
        device_class: door
        value_template: >-
          {{ not is_state('binary_sensor.bathroom_door_state', 'off')
             or not is_state('binary_sensor.front_door_state', 'off')
             or not is_state('binary_sensor.kitchen_door_state', 'off')
             or not is_state('binary_sensor.office_entry_door_state', 'off')
             or not is_state('binary_sensor.guest_room_balcony_door_state', 'off')
             or not is_state('binary_sensor.south_door_state', 'off') }}
        delay_off:
          seconds: 7