#####################################################################
### Binary Sensor - HVAC Status
#####################################################################
binary_sensor:
  - platform: template
    sensors:
      hvac_running:
        friendly_name: "HVAC Running"
        value_template: >-
          {{ states.climate.upstairs.attributes.hvac_action != 'fan' and
             states.climate.upstairs.attributes.hvac_action != 'idle' or
             states.climate.downstairs.attributes.hvac_action != 'fan' and
             states.climate.downstairs.attributes.hvac_action != 'idle' }}

## original values
#          {{ states.climate.upstairs.attributes.hvac_action != 'idle' or
#             states.climate.downstairs.attributes.hvac_action != 'idle' }}

        delay_off:
          minutes: 1
