################################################################
## Binary Sensor
################################################################
binary_sensor:
## Workday Sensor
  - platform: workday
    country: US
    add_holidays:
      - '2022-01-01'  # new years day
      - '2022-01-20'  # mlk day
      - '2022-03-18'  # pto
      - '2022-07-06'  # pto
      - '2022-10-30'  # pto
      - '2022-11-25'  # day after
      - '2022-12-23'  # pto
      - '2022-12-26'  # pto
      - '2022-12-27'  # pto
      - '2022-12-28'  # pto
      - '2022-12-29'  # pto
      - '2022-12-30'  # pto