#####################################################################
### Binary Sensor - Downstairs Bathroom Presence
#####################################################################
binary_sensor:
  - platform: template
    sensors:
      downstairs_bath_presence:
        friendly_name: "Downstairs Bathroom Presence"
        value_template: >-
          {{ is_state('binary_sensor.motion_downstairs_bath', 'on') }}
        delay_off:
          minutes: 7
