#####################################################################
### Binary Sensor - HVAC Status
#####################################################################
binary_sensor:
  - platform: template
    sensors:
      downstairs_hvac_running:
        friendly_name: "Downstairs HVAC Running"
        value_template: >-
          {{ states.climate.downstairs.attributes.hvac_action != 'fan' and
             states.climate.downstairs.attributes.hvac_action != 'idle' }}
        delay_off:
          minutes: 1

  - platform: template
    sensors:
      upstairs_hvac_running:
        friendly_name: "Upstairs HVAC Running"
        value_template: >-
          {{ states.climate.upstairs.attributes.hvac_action != 'fan' and
             states.climate.upstairs.attributes.hvac_action != 'idle' }}
        delay_off:
          minutes: 1