################################################################
## Binary Sensor
################################################################
binary_sensor:
## Workday Sensor
  - platform: workday
    country: US




