#####################################################################
### Binary Sensor: if any door is held open for 5 min, turn on
#####################################################################
binary_sensor:
  - platform: template
    sensors:
      door_held_open:
        friendly_name: "Door Held Open"
        value_template: >-
          {{ is_state('binary_sensor.bathroom_door_state', 'on')
             or is_state('binary_sensor.front_door_state', 'on')
             or is_state('binary_sensor.kitchen_door_state', 'on')
             or is_state('binary_sensor.office_door_state', 'on')
             or is_state('binary_sensor.guest_room_balcony_door_state', 'on')
             or is_state('binary_sensor.south_door_state', 'on') }}
#        entity_picture_template: >-
#          {% if is_state('binary_sensor.all_doors', 'on') %}
#            /local/red_shield.png
#          {% else %}
#            /local/green_shield.png
#          {% endif %}
        delay_on:
          minutes: 5