#####################################################################
### Binary Sensor: turn precool automation on or off based on date
#####################################################################
binary_sensor:
  - platform: template
    sensors:
      climate_precool:
        friendly_name: "Climate Precool"
        value_template: >-
          {{ strptime(states('sensor.date'), '%Y-%m-%d').month < 11 }}