#####################################################################
### Binary Sensor
#####################################################################
binary_sensor:
  - platform: template
    sensors:
      nursery_presence:
        friendly_name: "Nursery Presence"
        value_template: >-
          {{ is_state('binary_sensor.nursery_occupancy', 'on')
             or is_state('binary_sensor.nursery_motion', 'on') }}
        availability_template: "{{ not 'unavailable' in [states('binary_sensor.nursery_occupancy'), states('binary_sensor.nursery_motion')] and not 'unknown' in [states('binary_sensor.nursery_occupancy'), states('binary_sensor.nursery_motion')] and not 'none' in [states('binary_sensor.nursery_occupancy'), states('binary_sensor.nursery_motion')] }}"
        delay_off:
          minutes: 15