#####################################################################
### Set Away Mode when weather is Awesome
#####################################################################
automation:
  - alias: Set Eco Mode if weather is nice
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Awesome'

    condition:
      - condition: template
        value_template: "{{ states.climate.downstairs.attributes.current_temperature <= 80 }}"

      - condition: template
        value_template: "{{ states.climate.upstairs.attributes.current_temperature <= 82 }}"

    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.downstairs
          preset_mode: 'Eco'

      - service: climate.set_preset_mode
        data:
          entity_id: climate.upstairs
          preset_mode: 'Eco'




