#####################################################################
### Pool Light Controls
#####################################################################
automation:
### Reset the Pool Light selection when switched off
  - alias: Pool Light Menu Reset
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.pool_light
        to: 'off'
        for:
          seconds: 15

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.pool_scene
          option: Select an option...

      - service: input_select.select_option
        data:
          entity_id: input_select.pool_color
          option: Select an option...


### Pool Scene Selection
  - alias: Pool Scene
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.pool_scene

    action:
      - service: script.turn_on
        data_template:
          entity_id: >-
            {% if is_state('input_select.pool_scene', 'Cycle') %}
              script.pool_cycle
            {% elif is_state('input_select.pool_scene', 'Party') %}
              script.pool_party
            {% elif is_state('input_select.pool_scene', 'Romance') %}
              script.pool_romance
            {% elif is_state('input_select.pool_scene', 'Caribbean') %}
              script.pool_caribbean
            {% elif is_state('input_select.pool_scene', 'Patriotic') %}
              script.pool_patriotic
            {% elif is_state('input_select.pool_scene', 'Sunset') %}
              script.pool_sunset
            {% elif is_state('input_select.pool_scene', 'Royal') %}
              script.pool_royal
            {% else %}
              unknown
            {% endif %}

      # Reset the Pool Color input_select
      - service: input_select.select_option
        data:
          entity_id: input_select.pool_color
          option: Select an option...

### commenting this out for now - testing the state change reset above...
#      - delay:
#          seconds: 10
#
#      # Reset the Input Select to "Select an option..."
#      - service: input_select.select_option
#        data_template:
#          entity_id: "{{ trigger.to_state.entity_id }}"
#          option: Select an option...


### Pool Color Selection
  - alias: Pool Color
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.pool_color

    action:
      - service: script.turn_on
        data_template:
          entity_id: >-
            {% if is_state('input_select.pool_color', 'Blue') %}
              script.pool_blue
            {% elif is_state('input_select.pool_color', 'Green') %}
              script.pool_green
            {% elif is_state('input_select.pool_color', 'Red') %}
              script.pool_red
            {% elif is_state('input_select.pool_color', 'White') %}
              script.pool_white
            {% elif is_state('input_select.pool_color', 'Magenta') %}
              script.pool_magenta
            {% else %}
              unknown
            {% endif %}

      # Reset the Pool Scene input_select
      - service: input_select.select_option
        data:
          entity_id: input_select.pool_scene
          option: Select an option...


#      - delay:
#          seconds: 10
#
#      # Reset the Input Select to "Select an option..."
#      - service: input_select.select_option
#        data_template:
#          entity_id: "{{ trigger.to_state.entity_id }}"
#          option: Select an option...


