#####################################################################
### Xiaomi smart button automations
#####################################################################

automation:
#####################################################################
### Living Room Smart Button
#####################################################################

  ### Living Room Smart Button Single Press
  - alias: Living Room Smart Button Single Press
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.smart_button_living_room
        click_type: single

    action:
      - service: timer.start
        entity_id: timer.bedtime

      - service: media_player.volume_set
        entity_id: media_player.living_room
        data_template:
          volume_level: "{{ states('sensor.alexa_volume') }}"

      - service: notify.alexa_media
        data:
          target: media_player.living_room
          message: "Goodnight. See you in the morning."
          data:
            type: tts

  ### Living Room Smart Button Double Press
  - alias: Living Room Smart Button Double Press
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.smart_button_living_room
        click_type: double

    action:
      - service: timer.cancel
        entity_id: timer.bedtime


#####################################################################
### Master Bedroom Smart Button
#####################################################################

  ### Master Bedroom Smart Button Single Press
  - alias: Master Bedroom Smart Button Single Press
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.smart_button_master_bedroom
        click_type: single

    action:
      - service: script.turn_on
        entity_id: script.nightlight

  ### Master Bedroom Smart Button Double Press
  - alias: Master Bedroom Smart Button Double Press
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.smart_button_master_bedroom
        click_type: double

    action:
      - service: timer.start
        entity_id: timer.bedtime


  ### Master Bedroom Smart Button Long Press
  - alias: Master Bedroom Smart Button Long Press
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.smart_button_master_bedroom
        click_type: long_click_press

    action:
      - service: timer.cancel
        entity_id: timer.bedtime


#####################################################################
### Office Smart Button
#####################################################################

  ### Office Smart Button Single Press
  - alias: Office Smart Button Single Press
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.smart_button_office
        click_type: single

    action:
      - service: timer.start
        entity_id: timer.bedtime

  ### Office Smart Button Double Press
  - alias: Office Smart Button Double Press
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.smart_button_office
        click_type: double

    action:
      - service: timer.cancel
        entity_id: timer.bedtime

  ### Office Smart Button Long Press
  - alias: Office Smart Button Long Press
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.smart_button_office
        click_type: long_click_press

    action:
      - service: script.turn_on
        entity_id: script.bright


#####################################################################
### Other Smart Button Example
#####################################################################

  ### Smart Button other press examples
#  - alias: Toggle couch light on double click
#    trigger:
#      platform: event
#      event_type: xiaomi_aqara.click
#      event_data:
#        entity_id: binary_sensor.switch_158d000xxxxxc2
#        click_type: double
#    action:
#      service: switch.toggle
#      entity_id: switch.wall_switch_right_158d000xxxxx01
#  - alias: Let a dog bark on long press
#    trigger:
#      platform: event
#      event_type: xiaomi_aqara.click
#      event_data:
#        entity_id: binary_sensor.switch_158d000xxxxxc2
#        click_type: long_click_press
#    action:
#      service: xiaomi_aqara.play_ringtone
#      data:
#        gw_mac: xxxxxxxxxxxx
#        ringtone_id: 8
#        ringtone_vol: 8


