#####################################################################
### Mailbox Camera Control
#####################################################################
automation:
  ## if the mailbox door is opened, do ptz pattern tour, then park
  - alias: Mailbox Door Opened
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.mailbox_door
        to: 'on'

#    condition:
#      - condition: sun
#        after: sunset

    action:
      - service: script.mailbox_alert

      - service: shell_command.driveway_ptz_preset_4
      - delay:
          seconds: 2

      - service: shell_command.driveway_ptz_preset_5
      - delay:
          seconds: 7
      
      - service: shell_command.driveway_ptz_preset_6
      - delay:
          seconds: 6

      - service: shell_command.driveway_ptz_preset_3
      - delay:
          seconds: 7

      - service: shell_command.driveway_ptz_preset_2


  ## Mailbox Door Closed - return to parked ptz preset
  - alias: Mailbox Door Closed
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.mailbox_door
        to: 'off'
        for:
          seconds: 10

    action:
      - service: shell_command.driveway_ptz_preset_2


  ## Mailbox Door Held Open - notify me
  - alias: Mailbox Door Held Open
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.mailbox_door
        to: 'off'
        for:
          minutes: 3

    action:
      - service: notify.mobile_app_rip8plus
        data:
          title: "Mailbox"
          message: "Mailbox Door Held Open"
          data:
            push:
              thread-id: "mailbox"
              sound:
                name: default


