#####################################################################
### Set BBQ Temp Thresholds
#####################################################################
automation:
  ### Grill too hot
  - alias: BBQ Grill Alarm High Temp
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.grill_temperature

    condition:
      - condition: state
        entity_id: binary_sensor.bbq_grill_high
        state: 'on'

      - condition: state
        entity_id: input_boolean.bbq_alert_high
        state: 'on'

    action:
      - service: notify.mobile_app_rip8plus
        data:
          title: "Grill Temp"
          message: "The grill is {{ states('sensor.grill_temperature') }} degrees. That's too hot!"
          data:
            push:
              thread-id: "bbq"
              sound:
                name: "descent.caf"
            apns_headers:
              'apns-collapse-id': 'bbq_high'


  ### Grill too cold
  - alias: BBQ Grill Alarm Low Temp
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.grill_temperature

    condition:
      - condition: state
        entity_id: binary_sensor.bbq_grill_low
        state: 'on'

      - condition: state
        entity_id: input_boolean.bbq_alert_low
        state: 'on'

    action:
      - service: notify.mobile_app_rip8plus
        data:
          title: "Grill Temp"
          message: "The grill is {{ states('sensor.grill_temperature') }} degrees. That's too low!"
          data:
            push:
              thread-id: "bbq"
              sound:
                name: default
            apns_headers:
              'apns-collapse-id': 'bbq_low'



  ### Food target temperature reached
  - alias: BBQ Food Target Temp
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bbq_food_ready
        to: 'on'

    condition:
      - condition: state
        entity_id: input_boolean.bbq_alert_food
        state: 'on'

    action:
      - service: notify.mobile_app_rip8plus
        data:
          title: "Food Target Temp"
          message: "Food is at {{ states('sensor.food_temperature') }} degrees. Go check it!"
          data:
            push:
              thread-id: "bbq"
              sound:
                name: default
            apns_headers:
              'apns-collapse-id': 'bbq_food'




### reference; to do a custom notify:
### {% if states('sensor.grill_temperature') >= states('input_number.bbq_high_temp') %} "OMGLOLBBQ" {% endif %}
#      - service: script.do alexa announce thing here
