####################################################################
## Downstairs Bathroom Lights
####################################################################
automation:
### Turn on the lights if entering from patio
  - alias: Downstairs Bathroom Lights On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.bathroom_door_state
        to: 'Open'

      - platform: state
        entity_id: binary_sensor.motion_downstairs_bath
        to: 'on'

    condition:
      - condition: sun
        after: sunset

      - condition: state
        entity_id: switch.downstairs_bath_lights_switch
        state: 'off'

    action:
      - service: switch.turn_on
        data:
          entity_id: switch.downstairs_bath_lights_switch


### Turn off the downstairs bathroom lights
  - alias: Downstairs Bathroom Lights Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.downstairs_bath_presence
        to: 'off'

    condition:
      - condition: state
        entity_id: switch.downstairs_bath_lights_switch
        state: 'on'

    action:
      - service: switch.turn_off
        data:
          entity_id: switch.downstairs_bath_lights_switch



#### Turn on the lights if entering from patio
#  - alias: Bathroom Lights on Entry
#    initial_state: 'on'
#    trigger:
#      - platform: state
#        entity_id: sensor.bathroom_door_state
##        from: 'Closed'
##        to: 'Open'
#
#    condition:
#      - condition: sun
#        after: sunset
#
#    action:
#      - service_template: >-
#          {% if is_state('sensor.bathroom_door_state', 'Closed') %}
#            switch.turn_on
#          {% else %}
#            switch.turn_off
#          {% endif %}
#        data:
#          entity_id: switch.downstairs_bath_lights_switch


### Preserve old settings
#      - service: switch.turn_on
#        data:
#          entity_id: switch.downstairs_bath_lights_switch

#      - delay:
#          minutes: 15
#
#      - service: switch.turn_off
#        data:
#          entity_id: switch.downstairs_bath_lights_switch


### REFERENCE - alexa announce door open 
### disabled due to low WAF - saving for templating syntax
#      - service: notify.alexa_media
#        data_template:
#          target: media_player.living_room
#          message: "The {{ trigger.to_state.attributes.friendly_name }} is open."
#          data:
#            type: tts
