#####################################################################
### Master Bedroom Automatic Nightlight
#####################################################################
automation:
  - alias: Master Bedroom Nightlight
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.motion_master_bedroom
      to: 'on'

    condition:
          - condition: time
            after: '21:00:00'
            before: '06:00:00'

    action:
      - service: script.turn_on
        entity_id: script.nightlight
