#####################################################################
### After Hours Automation
#####################################################################
automation:
  ### Turn off things left on after_hours
  - alias: After Hours Shutdown
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.after_hours
        to: 'on'

    condition:
      - condition: state
        entity_id: input_boolean.party_mode
        state: 'off'

    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.patio_light
          - switch.pool_light
          - fan.patio_fan
          - group.accent_lights
