#####################################################################
### Control Visitor Mode for dog sitter
### Related Automations: automation_away_mode.yaml
#####################################################################
automation:
  ### Turn on visitor_mode if door is unlocked by Dog Sitter
  - alias: Turn On Visitor Mode via Code
    initial_state: 'on'
     
    trigger:
      - platform: template
        value_template: "{{ states('sensor.lock_south_door_status') == 'Unlocked by Dog Sitter' }}"

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'

      - condition: state
        entity_id: input_boolean.visitor_mode
        state: 'off'

    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.visitor_mode


  ### Turn off Visitor Mode when we return home
  - alias: Cancel Visitor Mode
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: group.all_devices
        from: 'not_home'
        to: 'home'
        for:
          minutes: 7

    condition:
      - condition: state
        entity_id: input_boolean.visitor_mode
        state: 'on'

    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.visitor_mode


  ### Start Away Mode countdown if visitor_mode is turned off and we are not home
  ### Useful if our house sitter leaves for an extended time and we manually turn off visitor_mode (add automation if you can identify lock from outside)
  - alias: Visitor Away
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: input_boolean.visitor_mode
        to: 'off'
        for:
          minutes: 5

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'

    action:
      - service: timer.start
        entity_id: timer.away_mode


#####################################################################
### Handle Away Mode Automations
#####################################################################
  ### Disable climate away mode automation when visitor_mode is turned on
  - alias: Disable away_mode when visitor_mode is on
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: input_boolean.visitor_mode
        to: 'on'

    action:
      - service: automation.turn_off
        entity_id: automation.away_mode_countdown

      - service: automation.turn_off
        entity_id: automation.away_mode_on


  ### Enable climate away mode automation when visitor_mode is turned off
  - alias: Enable away_mode when visitor_mode is off
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: input_boolean.visitor_mode
        to: 'off'

    action:
      - service: automation.turn_off
        entity_id: automation.away_mode_countdown

      - service: automation.turn_on
        entity_id: automation.away_mode_on


