#####################################################################
### Automations for Media Players
#####################################################################
automation:
  ### Set Lighting script when media is playing on Apple TV
  - alias: AppleTV script Set
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: media_player.apple_tv
        to: 'playing'

      - platform: state
        entity_id: media_player.apple_tv
        to: 'paused'

      - platform: state
        entity_id: media_player.apple_tv
        to: 'stopped'

    condition: 
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'

      - condition: state
        entity_id: input_boolean.dinner_time
        state: 'off'

      - condition: state
        entity_id: input_boolean.sleeping
        state: 'off'

    action:
      - service: script.turn_on
        data_template:
          entity_id: >-
            {% if trigger.to_state.state == "playing" or trigger.to_state.state == "resumed" %}
              script.movie_time
            {% elif trigger.to_state.state == "paused" or trigger.to_state.state == "stopped" %}
              script.movie_paused
            {% elif trigger.to_state.state == "idle" and now().strftime('%H%M')|int > 2000 %}
              script.tv_time
            {% else %}
              script.evening
            {% endif %}

#            {% if trigger.to_state.state == "playing" or trigger.to_state.state == "resumed" %}
#              script.movie_time
#            {% elif trigger.to_state.state == "paused" or trigger.to_state.state == "stopped" %}
#              script.movie_paused
#            {% else %}
#              script.evening
#            {% endif %}


### Kodi automations
#  ### This automation works, but I switched to AppleTV for now
#  ### Set Kodi scene when media is playing
#  - alias: Kodi Scene Set
#    initial_state: 'on'
#    trigger:
#      - platform: state
#        entity_id: media_player.kodi_living_room
#
#    condition: 
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#
#      - condition: state
#        entity_id: input_boolean.dinner_time
#        state: 'off'
#
#    action:
#      - service: script.turn_on
#        data_template:
#          entity_id: >-
#            {% if trigger.to_state.state == "playing" or trigger.to_state.state == "resumed" %}
#              script.movie_time
#            {% elif trigger.to_state.state == "paused" or trigger.to_state.state == "idle" %}
#              script.movie_paused
#            {% elif trigger.to_state.state == "stopped" or trigger.to_state.state == "ended" %}
#              script.movie_ended
#            {% else %}
#              script.evening
#            {% endif %}


