#####################################################################
# Set DirecTV Channel
#####################################################################
automation:
  - alias: "DirecTV Channel Selection"
    description: "Change the channel based on selection."
    trigger:
      - platform: state
        entity_id: input_select.directv_channel

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"
        
    action:
      - service: script.turn_on
        data_template:
          entity_id: "script.directv_media_living_room_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...  
          #input_select.directv_channel






