#####################################################################
### Master Bathroom Roller Shades
#####################################################################
automation:
  ### master bath shade schedule weekdays
  - alias: Master Bath Shade Up Weekday
    initial_state: 'on'
    trigger:
      - platform: time
        at: '09:00:00'

    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri

    action:
      - service: cover.open_cover
        entity_id: cover.master_bath_roller_shades_level


  ### master bath shade schedule weekends
  - alias: Master Bath Shade Up Weekend
    initial_state: 'on'
    trigger:
      - platform: time
        at: '12:00:00'

    condition:
      - condition: time
        weekday:
          - sat
          - sun

    action:
      - service: cover.open_cover
        entity_id: cover.master_bath_roller_shades_level


  ### master bath shade lowered schedule
  - alias: Master Bath Shade Down
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '00:10:00'

    action:
      - service: cover.close_cover
        entity_id: cover.master_bath_roller_shades_level
