#####################################################################
### Master Bathroom Lights Automation
#####################################################################
automation:
  ### Trigger the Master Bathroom (bath) lights on motion
  - alias: Master Bathroom Lights On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_presence
        to: 'on'

    condition:
      - condition: time
        after: '17:00:00'

      - condition: numeric_state
        entity_id: sensor.illumination_master_bedroom
        below: 45

      - condition: state
        entity_id: input_boolean.sleeping
        state: 'off'

    action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Master Bathroom"
        scene_name: "Morning"


  ### Turn off the Master Bathroom lights
  - alias: Master Bathroom Lights Off after motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_master_bedroom
        to: 'off'
        for:
          minutes: 30

    condition:
      - condition: state
        entity_id: light.master_bathroom_ceiling
        state: 'on'

    action:
      - service: light.turn_off
        entity_id: light.master_bathroom_ceiling

