#####################################################################
### Master Bathroom - mini fridge automations for baby bottles
#####################################################################
automation:
  ### mini fridge OFF schedule
  - alias: Mini Fridge OFF
    initial_state: 'on'
    trigger:
      - platform: time
        at: '11:15:00'

    condition:
      - condition: state
        entity_id: switch.mini_fridge
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.mini_fridge

