#####################################################################
### Upstairs Climate-related automations
#####################################################################
automation:
  ### Set Climate on away
  - alias: Climate Upstairs Away Mode
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.away_mode

    condition:
      - condition: state
        entity_id: input_boolean.visitor_mode
        state: 'off'

    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.upstairs
          away_mode: 'on'


  ### Sleep Mode On
  - alias: Climate Upstairs Sleep Schedule
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: script.bedtime
        from: 'off'
        to: 'on'

      - platform: state
        entity_id: input_boolean.after_hours
        from: 'off'
        to: 'on'

    condition:
      - condition: template
        value_template: "{{ states.climate.upstairs.attributes.hold_mode != 'sleep' }}"

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'sleep'


  ### Set Temperature upon return
  - alias: Climate Upstairs Resume
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
      for:
        minutes: 2

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'home'

      - delay:
          minutes: 30

      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.upstairs
          resume_all: 'true'


  ### Doors Left Open
  - alias: Climate Upstairs Door Left Open
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.door_held_open
        to: 'on'
        for:
          minutes: 5

    condition:
      - condition: template
        value_template: "{{ states.climate.upstairs.attributes.hold_mode != 'away' }}"

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'away'

      - service: notify.notify
        data:
          title: "Door Held Open"
          message: "A door's been open too long - Away mode activated upstairs"


  ### Set min fan time for Summer
  - alias: Set fan timer summer
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Summer'

    action:
      - service: climate.ecobee_set_fan_min_on_time
        data:
          entity_id: climate.upstairs
          fan_min_on_time: '30'


  ### Set min fan time for Winter
  - alias: Set fan timer winter
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Winter'

      - platform: state
        entity_id: sensor.season
        to: 'Awesome'

    action:
      - service: climate.ecobee_set_fan_min_on_time
        data:
          entity_id: climate.upstairs
          fan_min_on_time: '5'


  ### Set away mode when weather is awesome
  - alias: Climate Upstairs Away if Awesome Weather
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.season
        to: 'Awesome'
        for:
          minutes: 30

    condition:
      - condition: template
        value_template: "{{ states.climate.upstairs.attributes.current_temperature <= 82 }}"

    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.upstairs
          away_mode: 'on'


#  ### Climate Resume
#  - alias: Climate Upstairs Resume
#    initial_state: 'on'
#    trigger:
#      - platform: time
#        at: '02:00:00'
#
#      - platform: time
#        at: '18:02:00'
#
#      - platform: time
#        at: '22:05:00'
#
#    condition:
#      - condition: state
#        entity_id: group.door_sensors
#        state: 'closed'
#
#      - condition: template
#        value_template: "{{ states.sensor.season.state != 'Awesome' }}"
#
#      - condition: or
#        conditions:
#          - condition: state
#            entity_id: group.all_devices
#            state: 'home'
#          
#          - condition: state
#            entity_id: input_boolean.visitor_mode
#            state: 'on'
#
#    action:
#      - service: climate.ecobee_resume_program
#        data:
#          entity_id: climate.upstairs
#          resume_all: 'true'


#  ### Home Mode Weekdays
#  - alias: Climate Upstairs Home Schedule Weekdays
#    initial_state: 'on'
#    trigger:
#      - platform: time
#        at: '18:00:00'
#
#    condition:
#      - condition: time
#        weekday:
#          - mon
#          - tue
#          - wed
#          - thu
#          - fri
#
#      - condition: or
#        conditions:
#          - condition: state
#            entity_id: group.all_devices
#            state: 'home'
#
#          - condition: state
#            entity_id: input_boolean.visitor_mode
#            state: 'on'
#
#    action:
#      - service: climate.set_hold_mode
#        data:
#          entity_id: climate.upstairs
#          hold_mode: 'home'


#  ### Home Mode Weekends
#  - alias: Climate Upstairs Home Schedule Weekends
#    initial_state: 'on'
#    trigger:
#      - platform: time
#        at: '17:00:00'
#
#    condition:
#      - condition: time
#        weekday:
#          - sat
#          - sun
#
#      - condition: or
#        conditions:
#          - condition: state
#            entity_id: group.all_devices
#            state: 'home'
#
#          - condition: state
#            entity_id: input_boolean.visitor_mode
#            state: 'on'
#
#    action:
#      - service: climate.set_hold_mode
#        data:
#          entity_id: climate.upstairs
#          hold_mode: 'home'
