#####################################################################
### Rain Sensor
#####################################################################
automation:
  - alias: rain sensor
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: weather.downstairs

    action:
      - service_template: >-
          {% if is_state('sensor.dark_sky_summary', 'Rain') %}
            homeassistant.turn_on
          {% elif is_state('sensor.dark_sky_summary', 'Light Rain') %}
            homeassistant.turn_on
          {% elif is_state('sensor.dark_sky_summary', 'Thunderstorm') %}
            homeassistant.turn_on
          {% elif is_state('sensor.dark_sky_summary', 'Showers') %}
            homeassistant.turn_on
          {% elif is_state('sensor.dark_sky_summary', 'Drizzle') %}
            homeassistant.turn_on
          {% else %}
            homeassistant.turn_off
          {% endif %}
        data:
          entity_id: input_boolean.rain
