#####################################################################
### Master Bedroom Ceiling Fan - overly complex controls :)
#####################################################################
automation:
  ### turn the master bed fan off
  - alias: Master Bedroom Fan Off
    initial_state: 'on'
    trigger:
      - platform: time
        at: '12:00:00'

    condition:
      - condition: state
        entity_id: switch.master_bedroom_fan
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.master_bedroom_fan


  ### master_bedroom_fan_speed_selector
  - alias: Master Bedroom Fan Speed Select
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.master_bedroom_fan_speed

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

    action:
      # Reset fan switch states
      - service: homeassistant.turn_off
        entity_id: group.mbr_fan_speed

      - delay:
          seconds: 1.5

      # Turn on the corresponding fan speed switch
      - service: switch.turn_on
        data_template:
          entity_id: "switch.master_bedroom_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

      # Set the Input Selection to current option
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: "{{ states.trigger.to_state.state }}"


  ### master_bedroom_fan_auto
  - alias: Master Bedroom Fan Auto
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: script.master_bedroom_night_time
        to: 'on'

    condition:
      - condition: state
        entity_id: switch.master_bedroom_fan
        state: 'off'

      - condition: numeric_state
        entity_id: sensor.upstairs_temperature
        above: 71

      - condition: numeric_state
        entity_id: sensor.upstairs_temperature
        below: 81

    action:
      - service: script.turn_on
        entity_id: script.mbr_fan_speed_step


  ### Reset Fan Selection
  - alias: Master Bedroom Fan Reset Selection
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: switch.master_bedroom_fan
        to: 'off'

    action:
      # Reset the Input Select to "Select an option..."
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...


#####################################################################
#  Automation - Saves Switch State to MQTT
#####################################################################
  - alias: Master Bedroom Fan Speed State Save
    initial_state: 'off'
    hide_entity: true
    trigger:
      platform: state
      entity_id: switch.master_bedroom_fan, switch.master_bedroom_fan_1, switch.master_bedroom_fan_2, switch.master_bedroom_fan_3, switch.master_bedroom_fan_4, switch.master_bedroom_fan_5, switch.master_bedroom_fan_6, switch.master_bedroom_fan_7, switch.master_bedroom_fan_8, switch.master_bedroom_fan_9, switch.master_bedroom_fan_10, switch.master_bedroom_fan_11, switch.master_bedroom_fan_12
    action:
      service: mqtt.publish
      data_template:
        topic: "/home/mbrfanspeed/{{ trigger.entity_id.split('.')[1] }}"
        retain: true
        qos: 1
        payload: '{{ trigger.to_state.state }}'


#####################################################################
# restores states of fan speed switches - doesn't work ... :(
#####################################################################
  - alias: Master Bedroom Fan Speed State Restore
    initial_state: 'off'
    hide_entity: true
    trigger:
      platform: homeassistant
      event: start
    action:
      - delay:
          minutes: 1
      - service_template: >
          {%- if states.sensor.master_bedroom_fan.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_1.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_1
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_2.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_2
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_3.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_3
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_4.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_4
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_5.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_5
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_6.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_6
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_7.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_7
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_8.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_8
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_9.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_9
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_10.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_10
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_11.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_11
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_12.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}
        data:
          entity_id: switch.master_bedroom_fan_12
