####################################################################
## Automations for Notify events and
## "Watchdog" Automations - notify us when we are away of events
####################################################################
automation:
  ## Cancel Away Mode
  - alias: Cancel Away
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: CANCEL_AWAY
    action:
      service: timer.cancel
      entity_id: timer.away_mode


#### While we are away ...
  ## Notify if master bedroom lights turned on
  - alias: Notify if away and bedroom lights turn on
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: group.master_bedroom_lights
        to: 'on'

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'

    action:
      - service: notify.ios_i8plus
        data:
          title: "Home Assistant Alert"
          message: "Master Bedroom Lights On"


  ## Notify if an exterior door is opened
  - alias: Notify if away and door is opened
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.front_door_state, sensor.south_door_state, sensor.kitchen_door_state, sensor.bathroom_door_state, sensor.office_door_state
        from: 'Closed'
        to: 'Open'

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'

    action:
      - service: notify.ios_i8plus
        data:
          title: "Exterior Door Opened"
          message: "Someone opened the {{ trigger.to_state.attributes.friendly_name }}."


  ## Send notification after home assistant has restarted
  - alias: Startup Notification
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: homeassistant
      event: start

    action:
    - service: notify.pushbullet
      data:
        title: "Home Assistant Startup"
        target: "device/Chrome"
        message: "Home Assistant is up and running."

    - service: notify.ios_i8plus
      data:
        title: "Home Assistant Startup"
        message: "Home Assistant is up and running."


