#####################################################################
### Security Sensor Automation
#####################################################################
automation:
  ### AC Leak Detector Alarm
  - alias: Downstairs AC Leak Detector Alarm
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.downstairs_ac_leak_detector
        to: 'Leak Detected!'

    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs
          operation_mode: 'off'

      - service: notify.notify
        data:
          title: "Leak Detected"
          message: "HVAC overflow detected - AC turned off!"


  ### Kegerator Door Alarm
  - alias: Kegerator Door Held Open
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.kegerator_door_state
        to: 'Open'
        for:
          seconds: 30

    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.keg_door_open

      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: .7

      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.kitchen
          message: "Attention, Please close the Kegerator door!"

      - service: notify.notify
        data:
          title: "Kegerator Door Alarm!"
          message: "The Kegerator door is held open!"


  ### Kegerator Door Restoral
  - alias: Kegerator Door Restoral
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.kegerator_door_state
        from: 'Open'
        to: 'Closed'

    condition:
      - condition: state
        entity_id: input_boolean.keg_door_open
        state: 'on'

    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.keg_door_open

      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: .5

      - service: notify.notify
        data:
          title: "Kegerator Restored"
          message: "Thank you for closing the Kegerator door."


  ### Door Held Open
  - alias: Entry Door Held Open
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.front_door_state, sensor.south_door_state, sensor.kitchen_door_state, sensor.bathroom_door_state
        to: 'Open'
        for:
          minutes: 5

    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.door_held_open


  ### All Secure
  - alias: All Secure
    initial_state: 'on'
#    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.front_door_state, sensor.south_door_state, sensor.kitchen_door_state, sensor.bathroom_door_state
        to: 'Closed'

    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.all_secure


  ### Door Open Event Workaround
  - alias: Record Door Open Events
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - sensor.front_door_contact_access_control
          - sensor.south_door_contact_access_control
          - sensor.office_door_contact_access_control
          - sensor.bathroom_door_contact_access_control
          - sensor.kitchen_door_access_control
        to: '22'

    action:
      - service: logbook.log
        data_template:
          name: "{{ trigger.to_state.attributes.friendly_name }}"
          message: " changed to open."
