####################################################################
## Notify on system restart
####################################################################
automation:
  ## Send notification after home assistant has restarted
  - alias: Startup Notification
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: homeassistant
      event: start

    action:
    - service: notify.pushbullet
      data:
        title: "Home Assistant Startup"
        target: "device/Chrome"
        message: "Home Assistant is up and running."

    - service: notify.mobile_app_rip8plus
      data:
        title: "Home Assistant Startup"
        message: "Home Assistant is up and running."
        data:
          push:
            sound:
              name: default


