####################################################################
## Notify - action: Cancel / Pause Away Mode
####################################################################
automation:
  - alias: iOS Cancel Away
    initial_state: 'on'
     
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: CANCEL_AWAY

    action:
      service: timer.cancel
      entity_id: timer.away_mode


  - alias: iOS Pause Away
    initial_state: 'on'
     
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: PAUSE_AWAY

    action:
      service: timer.pause
      entity_id: timer.away_mode


  - alias: iOS Visitor Mode
    initial_state: 'on'
     
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: VISITOR

    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.visitor_mode

      - service: timer.cancel
        entity_id: timer.away_mode


