#####################################################################
### Control TTS Announcements
#####################################################################
automation:
  ### Turn on announcements
  - alias: Announcements ON
    initial_state: 'on'
    trigger:
      - platform: time
        at: '08:00:00'

    condition:
      - condition: state
        entity_id: input_boolean.announce
        state: 'off'

    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.announce


  ### Turn off announcements
  - alias: Announcements OFF
    initial_state: 'on'
    trigger:
      - platform: time
        at: '21:30:00'

    condition:
      - condition: state
        entity_id: input_boolean.announce
        state: 'on'

    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.announce


  ### Control announcements at startup
  - alias: Announcement Startup
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: time
        after: '08:00:00'
        before: '21:30:00'

    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.announce
