#####################################################################
### Alexa TTS: this allows text input to be spoken by selected echos
#####################################################################
automation:
  ## Announce what is typed as input
  - alias: Alexa TTS
    trigger:
      platform: state
      entity_id: input_select.alexa
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: >
            {% if is_state('input_select.alexa', 'Living Room') %}
              media_player.living_room
            {% elif is_state('input_select.alexa', 'Master Bedroom') %}
              media_player.master_bedroom
            {% elif is_state('input_select.alexa', 'Kitchen') %}
              media_player.kitchen
            {% elif is_state('input_select.alexa', 'Game Room') %}
              media_player.game_room
            {% elif is_state('input_select.alexa', 'Nursery') %}
              media_player.nursery
            {% elif is_state('input_select.alexa', 'Office') %}
              media_player.office
            {% elif is_state('input_select.alexa', 'None') %}
              false
            {% endif %}
          volume_level: '{{ states.input_number.alexa_volume.state | float /10 }}'
      - service: notify.alexa_media
        data_template:
          target: >
            {% if is_state('input_select.alexa', 'Living Room') %}
              media_player.living_room
            {% elif is_state('input_select.alexa', 'Master Bedroom') %}
              media_player.master_bedroom
            {% elif is_state('input_select.alexa', 'Kitchen') %}
              media_player.kitchen
            {% elif is_state('input_select.alexa', 'Game Room') %}
              media_player.game_room
            {% elif is_state('input_select.alexa', 'Nursery') %}
              media_player.nursery
            {% elif is_state('input_select.alexa', 'Office') %}
              media_player.office
            {% elif is_state('input_select.alexa', 'None') %}
              false
            {% endif %}
          message: "{{  states('input_text.alexa_tts') }}"
          data:
            type: tts

      - delay: '00:00:02'

      - service: input_select.select_option
        data:
          entity_id: input_select.alexa
          option: None


