####################################################################
## Automations for Notify events and
## "Watchdog" Automations - notify us when we are away of events
####################################################################
automation:
#### While we are away ...
  ## Notify if master bedroom lights turned on
  - alias: Notify if away and bedroom lights turn on
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: group.master_bedroom_lights
        to: 'on'

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'

    action:
      - service: notify.mobile_app_rip8plus
        data:
          title: "Home Assistant Alert"
          message: "Master Bedroom Lights On"
          data:
            push:
              sound:
                name: default


  ## Notify if an exterior door is opened
  - alias: Notify if away and door is opened
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: sensor.front_door_state, sensor.south_door_state, sensor.kitchen_door_state, sensor.bathroom_door_state, sensor.office_door_state
        from: 'Closed'
        to: 'Open'

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'

    action:
      - service: notify.mobile_app_rip8plus
        data:
          title: "Exterior Door Opened"
          message: "Someone opened the {{ trigger.to_state.attributes.friendly_name }}."
          data:
            push:
              sound:
                name: default

