#####################################################################
### Automation - Sleeping
#####################################################################
automation:
  - alias: Sleeping Off Weekday
    initial_state: 'on'
     
    trigger:
      - platform: time
        at: '10:30:00'

    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.sleeping


  - alias: Sleeping Off Weekend
    initial_state: 'on'
     
    trigger:
      - platform: time
        at: '11:45:00'

    condition:
      - condition: time
        weekday:
          - sat
          - sun

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.sleeping

