#####################################################################
### Automation - Sleeping
#####################################################################
automation:
  - alias: Sleeping Off
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: time
        at: '06:45:00'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.sleeping
