#####################################################################
### Weather-based Lighting Automations
#####################################################################
automation:
  ### Turn on some lights if it is cloudy
  - alias: Living Room On Cloudy
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.rain
        from: 'off'
        to: 'on'

      - platform: template
        value_template: >-
          {% if is_state('sensor.dark_sky_summary', 'Rain') %}
            'true'
          {% elif is_state('sensor.dark_sky_summary', 'Thunderstorm') %}
            'true'
          {% elif is_state('sensor.dark_sky_summary', 'Showers') %}
            'true'
          {% elif is_state('sensor.dark_sky_summary', 'Drizzle') %}
            'true'
          {% elif is_state('sensor.dark_sky_summary', 'Mostly Cloudy') %}
            'true'
          {% else %}
            'false'
          {% endif %}


      - platform: numeric_state
        entity_id: sensor.dark_sky_precip_intensity
        above: 1

    condition:
      - condition: time
        after: '08:00:00'
        before: '17:00:00'

      - condition: state
        entity_id: group.all_devices
        state: 'home'

      - condition: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        above: 69

      - condition: numeric_state
        entity_id: sensor.illumination_front_entry
        below: 125

      - condition: template
        value_template: "{{ states.media_player.apple_tv.state != 'playing' }}"

    action:
      - service: scene.turn_on
        entity_id: scene.cloudy


  ### Turn off lights after rain has stopped
  - alias: Living Room Off Cloudy
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.dark_sky_precip_intensity
        below: 1

      - platform: state
        entity_id: input_boolean.rain
        from: 'on'
        to: 'off'

      - platform: numeric_state
        entity_id: sensor.illumination_front_entry
        above: 25

    condition:
      - condition: state
        entity_id: group.living_room
        state: 'on'

      - condition: numeric_state
        entity_id: sensor.illumination_front_entry
        above: 25

      - condition: time
        before: '17:00:00'

    action:
      - service: homeassistant.turn_off
        entity_id: group.living_room_lights

      - service: homeassistant.turn_off
        entity_id: group.entry_lights
