#####################################################################
### Set the Evening Scene at sunset
#####################################################################
automation:
  - alias: Evening Scene Schedule
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:10:00'

    condition: # condition added so this doesn't trigger if lights are lowered for watching tv later in the evening
      - condition: time
        before: '20:00:00'

      - condition: template
        value_template: "{{ states('media_player.apple_tv') != 'playing' }}"

      - condition: or
        conditions:
          - condition: state
            entity_id: group.all_devices
            state: 'home'

          - condition: state
            entity_id: input_boolean.visitor_mode
            state: 'on'

    action:
      - service: script.turn_on
        entity_id: script.evening

