############################################################################
#    @package          :     alexa_config
#    @description      :     alexa smarthome config for haaska
############################################################################
alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_pswd
      url: amazon.com
      include_devices:
        - "Fire Stick"
        - "Richard's 3rd Fire"
        - "Richard's 4th Fire"
        - "Living Room"
        - "Game Room"
        - "Master Bedroom"
        - FireTV
        - Nursery
        - Office
        - Downstairs
        - Kitchen
        - firetv_living_room


#####################################################################
### Alexa Smarthome Integration
#####################################################################
alexa:
  smart_home:
    filter:
      include_entities:
      ################################################
      ## Scripts
      ################################################
        - script.company_mode
        - script.ecobee_ds_home
        - script.ecobee_ds_resume
        - script.ecobee_us_home
        - script.ecobee_us_resume
        - script.find_iphone
        - script.hue_lr_christmas
        - script.hue_lr_daybreak
        - script.hue_lr_dimmed
        - script.hue_lr_minty
        - script.hue_lr_movie
        - script.hue_lr_nightlight
        - script.hue_lr_sunrise
        - script.hue_lr_sunset
        - script.hue_mbath_morning
        - script.master_bedroom_night_time
        - script.mbr_night_light
        - script.nap_time
        - script.pool_cycle
        - script.pool_party
        - script.start_bedtime_timer

      ################################################
      ## Scenes
      ################################################
        - scene.bright
        - scene.cloudy
        - scene.dim
        - scene.evening
        - scene.morning
        - scene.movie_time

      ################################################
      ## Groups
      ################################################
        - group.accent_lights
        - group.entry_lights
        - group.exterior_lights
        - group.interior_lights
        - group.game_room_lights
        - group.master_bedroom_lights
        - group.master_bathroom_lights
        - group.porch_lights
        - group.christmas_lights

      ################################################
      ## Climate
      ################################################
        - climate.downstairs
        - climate.upstairs

      ################################################
      ## Lights
      ################################################
        - light.billiards
        - light.dining_room_chandelier_level
        - light.entryway
        - light.living_room
        - light.foyer_lights_level
        - light.gateway_light_7811dcb7da52
        - light.kitchen_lights_level
        - light.living_room_lamp
        - light.lr_ceiling
        - light.master_bathroom
        - light.master_bath_vanity
        - light.master_bed_ceiling_level
        - light.master_bed_entry_level
        - light.master_bedroom_chandelier_level
        - light.master_reading_lamp
        - light.master_sitting_lamp
        - light.nursery_light
        - light.nursery_wall_light
        - light.office_desk_lamp
        - light.under_bed_lights
        - light.wine_room

      ################################################
      ## Switches
      ################################################
#        - switch.amp_input_dvd
#        - switch.amp_input_ipod
#        - switch.amp_input_movie
#        - switch.amp_input_tv
#        - switch.amp_movie_mode
#        - switch.amp_music_mode
#        - switch.amp_mute
        - switch.amp_power
        - switch.directv_play
        - switch.directv_power
        - switch.downstairs_bath_lights_switch
        - switch.flower_lamp
        - switch.fountains_switch
        - switch.game_room_floodlights
        - switch.living_room_fan
        - switch.living_room_fan_high
        - switch.living_room_fan_light
        - switch.living_room_fan_low
        - switch.living_room_fan_medium
        - switch.master_bedroom_fan
        - switch.master_bedroom_fan_light
        - switch.nursery_lamp
        - switch.outdoor_speakers
        - switch.patio_lights_switch
        - switch.back_yard_outlet
        - switch.front_yard_outlet
        - switch.pool_light_switch
        - switch.staircase_lamp
        - switch.switch_five
        - switch.switch_four
        - switch.switch_one
        - switch.switch_three
        - switch.switch_two
        - switch.tv_input_chromecast
        - switch.tv_input_directv
        - switch.tv_input_firetv
        - switch.tv_mute
        - switch.tv_power
        - switch.wine_room_lamp
        - switch.mini_fridge

      ################################################
      ## Fans
      ################################################
        - fan.patio_fan
        - fan.nursery_fan

      ################################################
      ## Input_Booleans
      ################################################
        - input_boolean.dinner_time
        - input_boolean.holiday
        - input_boolean.rain
        - input_boolean.visitor_mode

      ################################################
      ## Locks
      ################################################
        - lock.bathroom_entry_locked
        - lock.south_entry_locked

      ################################################
      ## Sensors
      ################################################
        - sensor.broadlink_sensor_temperature
        - sensor.downstairs_temperature
        - sensor.entryway_temperature
        - sensor.front_entry_fibaro_multisensor_temperature
        - sensor.guest_room_temperature
        - sensor.living_room_temperature
        - sensor.nursery_temperature
        - sensor.office_temperature
        - sensor.upstairs_temperature

      ################################################
      ## Covers
      ################################################
        - cover.master_bath_shade
        - cover.kitchen_shade

      ################################################
      ## Automations
      ################################################
        - automation.climate_downstairs_door_left_open
        - automation.doorbell_pressed
        - automation.fountains_on
        - automation.south_door_unlock_on_arrival


################################################
## Custom Names
################################################
    entity_config:
      automation.climate_downstairs_door_left_open:
        name: Open Door Schedule
        description: Automation for door held open

      automation.doorbell_pressed:
        name: Doorbell
        description: Automation for doorbell alerts

      automation.fountains_on:
        name: Fountain Schedule
        description: Automation for fountains

      automation.south_door_unlock_on_arrival:
        name: Auto Unlock Schedule
        description: Automation for arrival unlock

