#####################################################################
### Alexa Smarthome Integration
#####################################################################
alexa:
  smart_home:
#    endpoint: "https://api.amazonalexa.com/v3/events"
#    client_id: !secret amazon_client_id
#    client_secret: !secret amazon_client_secret
    filter:
      include_entities:
      ################################################
      ## Scripts
      ################################################
        - script.away
        - script.baby_playlist
        - script.bedtime
        - script.bright
        - script.christmas_time
        - script.climate_downstairs_cooldown
        - script.climate_upstairs_cooldown
        - script.cloudy
        - script.company_mode
        - script.dim
        - script.ecobee_ds_away
        - script.ecobee_ds_eco
        - script.ecobee_ds_home
        - script.ecobee_ds_normal
        - script.ecobee_ds_resume
        - script.ecobee_ds_sleep
        - script.ecobee_us_away
        - script.ecobee_us_eco
        - script.ecobee_us_home
        - script.ecobee_us_resume
        - script.ecobee_us_sleep
        - script.evening
        - script.game_time
        - script.hue_lr_daybreak
        - script.hue_lr_dimmed
        - script.hue_lr_minty
        - script.hue_lr_movie
        - script.hue_lr_nightlight
        - script.hue_lr_normal
        - script.hue_lr_sunrise
        - script.hue_lr_sunset
        - script.hue_mbath_morning
        - script.living_room_appletv_plex
        - script.master_bedroom_night_time
        - script.mbr_night_light
        - script.morning_sequence
        - script.movie_time
        - script.nap_time
        - script.nightlight
        - script.play_white_noise
        - script.pool_blue
        - script.pool_caribbean
        - script.pool_cycle
        - script.pool_green
        - script.pool_magenta
        - script.pool_party
        - script.pool_patriotic
        - script.pool_red
        - script.pool_romance
        - script.pool_royal
        - script.pool_sunset
        - script.pool_white
        - script.pool_pump_quick_clean
        - script.start_bedtime_timer
        - script.tv_power_off
        - script.tv_time
        - script.unlock_megs

      ################################################
      ## Scenes (created within Home Assistant UI)
      ################################################
        - scene.cozy
        - scene.lounge
        - scene.aj_night_time

      ################################################
      ## Groups
      ################################################
        - group.accent_lights
        - group.entry_lights
        - group.exterior_lights
        - group.game_room_lights
        - group.interior_lights
        - group.living_room_lights
        - group.master_bedroom_lights
        - group.master_bathroom_lights
        - group.porch_lights
        - group.wine_room_lights
        - group.christmas_lights

      ################################################
      ## Climate
      ################################################
        - climate.downstairs
        - climate.upstairs

      ################################################
      ## Lights
      ################################################
        - light.billiards
        - light.dining_room_chandelier
        - light.entryway
        - light.foyer_lights
        - light.kitchen_night_light
        - light.kitchen_lights
        - light.laundry_room
        - light.living_room_lamp
        - light.living_room_ceiling
        - light.lounge_light
        - light.master_bathroom_ceiling
        - light.master_bathroom_vanity
        - light.master_bed_ceiling
        - light.master_bed_entry
        - light.master_bedside_lamps
        - light.master_bedroom_chandelier
        - light.master_reading_lamp
        - light.master_sitting_lamp
        - light.nursery_light
        - light.nursery_wall_light
        - light.office_desk_lamp
        - light.pantry
        - light.bedframe_light
        - light.wine_room_ceiling
        - light.bar_strip_light

      ################################################
      ## Switches
      ################################################
        - switch.amp
        - switch.appletv
        - switch.aquarium
        - switch.back_yard_outlet
        - switch.christmas_tree
        - switch.chromecast
        - switch.downstairs_bathroom_light
        - switch.fireplace
        - switch.fireplace_flame_down
        - switch.fireplace_flame_up
        - switch.fireplace_flicker
        - switch.fireplace_light
        - switch.fireplace_temp_down
        - switch.fireplace_temp_up
        - switch.fireplace_timer
        - switch.fountains_switch
        - switch.game_room_floodlights
        - switch.hdmi_3
        - switch.irrigation_system_rain_delay
        - switch.kegerator
        - switch.living_room_fan
        - switch.living_room_fan_high
        - switch.living_room_fan_light
        - switch.living_room_fan_low
        - switch.living_room_fan_medium
        - switch.master_bedroom_fan
        - switch.master_bedroom_fan_light
        - switch.media
        - switch.mini_fridge
        - switch.mute
        - switch.nursery_lamp
        - switch.outdoor_speakers
        - switch.patio_lights
        - switch.pc
        - switch.pool_light
        - switch.pool_pump
        - switch.porch_rope_lights
        - switch.staircase_lamp
        - switch.switch_five
        - switch.switch_four
        - switch.switch_one
        - switch.switch_three
        - switch.switch_two
        - switch.tv
        - switch.tv_volume
        - switch.wine_room_lamp


      ################################################
      ## Fans
      ################################################
        - fan.patio_fan
        - fan.nursery_fan

      ################################################
      ## Input_Booleans
      ################################################
        - input_boolean.movie_night
        - input_boolean.holiday
        - input_boolean.rain
        - input_boolean.visitor_mode
        - input_boolean.bbq_alert_high
        - input_boolean.bbq_alert_low
        - input_boolean.bbq_alert_food

      ################################################
      ## Locks
      ################################################
        - lock.bathroom_entry
        - lock.south_entry

      ################################################
      ## Sensors (not supported via Alexa Smart Home)
      ################################################
#        - sensor.broadlink_sensor_temperature
#        - sensor.downstairs_temperature
#        - sensor.entryway_temperature
#        - sensor.front_entry_fibaro_multisensor_temperature
#        - sensor.guest_room_temperature
#        - sensor.living_room_temperature
#        - sensor.nursery_temperature
#        - sensor.office_temperature
#        - sensor.upstairs_temperature

      ################################################
      ## Covers
      ################################################
        - cover.master_bath_shades
        - cover.kitchen_shade

      ################################################
      ## Automations
      ################################################
        - automation.climate_downstairs_door_held_open
        - automation.doorbell_pressed
        - automation.fountains_on
        - automation.south_door_unlock_on_arrival


      include_domains:
        - image_processing


################################################
## Custom Names
################################################
    entity_config:
      automation.climate_downstairs_door_held_open:
        name: Open Door Schedule
        description: Automation for door held open

      automation.doorbell_pressed:
        name: Doorbell
        description: Automation for doorbell alerts

      automation.fountains_on:
        name: Fountain Schedule
        description: Automation for fountains

      automation.south_door_unlock_on_arrival:
        name: Auto Unlock Schedule
        description: Automation for arrival unlock

      climate.downstairs:
        name: Downstairs Thermostat
        description: Downstairs Thermostat

      climate.upstairs:
        name: Upstairs Thermostat
        description: Upstairs Thermostat

      input_boolean.bbq_alert_high:
        name: High Temp Alarm
        description: High Temp Alarm for BBQ

      input_boolean.bbq_alert_low:
        name: Low Temp Alarm
        description: Low Temp Alarm for BBQ

      input_boolean.bbq_alert_food:
        name: Food Temp Alarm
        description: Food Target Temp Alarm for BBQ


## TV HDMI Inputs via Broadlink
#      switch.appletv:
#        name: AppleTV
#        description: TV HDMI 1
#
#      switch.pc:
#        name: PC
#        description: TV HDMI 2
#
#      switch.hdmi_3:
#        name: HDMI 3
#        description: TV HDMI 3

## 433MHz RF Switches via Broadlink        
      switch.switch_two:
        name: Stairway Christmas Lights
        description: Stairway Christmas Lights

      switch.switch_four:
        name: Humidifier
        description: Humidifier

      switch.switch_five:
        name: Star Light
        description: Star Light

## Rachio
      switch.irrigation_system_rain_delay:
        name: Rain Delay
        description: Rachio Rain Delay

