#####################################################################
### Alexa Smarthome Integration
#####################################################################
alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_media_client_id
    client_secret: !secret alexa_media_client_secret

    filter:
      include_domains:
        - climate
        - cover
        - fan
        - group
        - input_boolean
        - input_number
        - light
        - lock
        - person
        - scene

      include_entity_globs:
        - binary_sensor.all_*
        - binary_sensor.*_armed
        - binary_sensor.*_state
        - script.ecobee_*

#      exclude_entity_globs:

      exclude_entities:
        - group.all_devices
        - group.alarm_clock
        - group.master_bedroom_fan
        - input_number.alexa_volume
        - light.b_table_1
        - light.b_table_2
        - light.b_table_3
        - light.center_entryway
        - light.kitchen_entryway
        - light.laundry_1
        - light.laundry_2
        - light.master_bath_entry
        - light.master_bath_sink
        - light.party_lights
        - light.sn1_led
        - light.south_entryway

      include_entities:
        - automation.climate_downstairs_door_held_open
        - automation.doorbell_pressed
        - automation.south_door_unlock_on_arrival
#        - input_boolean.bbq_alert_food
#        - input_boolean.bbq_alert_high
#        - input_boolean.bbq_alert_low
#        - input_boolean.holiday
#        - input_boolean.hvac_maintenance
#        - input_boolean.master_fan_hold
#        - input_boolean.movie_night
#        - input_boolean.north_gate_shunt
#        - input_boolean.nursery_fan_hold
#        - input_boolean.party_mode
#        - input_boolean.pool_maintenance
#        - input_boolean.sleeping
#        - input_boolean.visitor_mode
        - media_player.home_theater
        - media_player.bar_tv

## scripts
        - script.alarm_clock_snooze
        - script.away
        - script.bedtime
        - script.bright
        - script.broadlink_living_room_fan_light_off
        - script.broadlink_living_room_fan_medium
        - script.broadlink_living_room_fan_off
        - script.cancel_away_timer
        - script.cancel_bedtime_timer
        - script.christmas_music
        - script.christmas_time
        - script.climate_downstairs_cooldown
        - script.climate_upstairs_cooldown
        - script.cloudy
        - script.company_mode
        - script.evening
        - script.game_time
        - script.home_theater_remote_ad_skip
        - script.home_theater_remote_skip_30
        - script.iphone_find_megs_phone
        - script.kitchen_shade_to_50
#        - script.living_room_fan_high
#        - script.living_room_fan_light
#        - script.living_room_fan_low
        - script.master_bedroom_night_time
        - script.morning
        - script.morning_sequence
        - script.movie_time
        - script.pause_away_timer
        - script.pause_bedtime_timer
        - script.pool_blue
        - script.pool_caribbean
        - script.pool_cycle
        - script.pool_green
        - script.pool_magenta
        - script.pool_party
        - script.pool_patriotic
        - script.pool_pump_quick_clean
        - script.pool_red
        - script.pool_romance
        - script.pool_royal
        - script.pool_sunset
        - script.pool_white
        - script.routine_wake_up
        - script.scene_living_room_default
        - script.start_bedtime_timer
        - script.traverse_cancel_start_vehicle
        - script.traverse_lock_doors
        - script.traverse_start_vehicle
        - script.traverse_unlock_doors
        - script.tv_time
        - script.unlock_megs

## sensors
        - sensor.food_temperature
        - sensor.grill_temperature
        - sensor.humidor_humidity
        - sensor.humidor_temperature

## switches
        - switch.amp
        - switch.appletv
        - switch.aquarium
        - switch.back_yard_outlet # Party Lights switch
        - switch.christmas_tree
        - switch.chromecast
        - switch.downstairs_bathroom_light
        - switch.downstairs_christmas_lights
        - switch.drip_and_citrus_trees_schedule
        - switch.fireplace
        - switch.fountains
        - switch.game_room_floodlights
        - switch.hdmi_three
        - switch.irrigation_system_rain_delay
        - switch.living_room_fan
        - switch.living_room_fan_high
        - switch.living_room_fan_light
        - switch.living_room_fan_low
        - switch.living_room_fan_medium
        - switch.master_bedroom_fan
        - switch.master_bedroom_fan_light
        - switch.mute
        - switch.nursery_lamp
        - switch.patio_lights
        - switch.pc
        - switch.pool_light
        - switch.pool_pump
        - switch.porch_rope_lights
        - switch.space_heater
        - switch.staircase_lamp
        - switch.starlight
        - switch.front_house_lights # switch.tplink_outlet_1
        - switch.tplink_outlet_2
        - switch.tv
        - switch.tv_volume
        - switch.upstairs_christmas_lights
#        - switch.outdoor_speakers
#        - switch.rf_switch_1
#        - switch.rf_switch_2
#        - switch.rf_switch_3
#        - switch.rf_switch_4
#        - switch.rf_switch_5

## timers
        - timer.bedtime
        

################################################
## Custom Names
################################################
    entity_config:
      automation.climate_downstairs_door_held_open:
        name: Door Held Open Alarm
        description: Automation for door held open

      automation.doorbell_pressed:
        name: Doorbell
        description: Automation for doorbell alerts

      automation.fountains_on:
        name: Fountain Schedule
        description: Automation for fountains

      automation.south_door_unlock_on_arrival:
        name: Auto Unlock
        description: Automation for arrival unlock

      climate.downstairs:
        name: Downstairs Thermostat
        description: Downstairs Thermostat

      climate.upstairs:
        name: Upstairs Thermostat
        description: Upstairs Thermostat

      input_boolean.bbq_alert_high:
        name: High Temp Alarm
        description: High Temp Alarm for BBQ

      input_boolean.bbq_alert_low:
        name: Low Temp Alarm
        description: Low Temp Alarm for BBQ

      input_boolean.bbq_alert_food:
        name: Food Temp Alarm
        description: Food Target Temp Alarm for BBQ

## Rachio
      switch.irrigation_system_rain_delay:
        name: Rain Delay
        description: Rachio Rain Delay

## TV HDMI Inputs via Broadlink
#      switch.appletv:
#        name: AppleTV
#        description: TV HDMI 1
#
#      switch.pc:
#        name: PC
#        description: TV HDMI 2
#
#      switch.hdmi_3:
#        name: HDMI 3
#        description: TV HDMI 3

### 433MHz RF Switches via Broadlink        
#      switch.rf_switch_1:
#        name: Outlet 1
#        description: 433MHz RF Outlet 1
#
#      switch.rf_switch_2:
#        name: Outlet 2
#        description: 433MHz RF Outlet 2
#
#      switch.rf_switch_3:
#        name: Outlet 3
#        description: 433MHz RF Outlet 3
#
#      switch.rf_switch_4:
#        name: Outlet 4
#        description: 433MHz RF Outlet 3
#
#      switch.rf_switch_5:
#        name: Outlet 5
#        description: 433MHz RF Outlet 3
