  ################################################
  ## Customize Global Icons
  ################################################
homeassistant:
  customize_glob:
    "input_boolean.*":
      icon: mdi:toggle-switch

    "scene.*":
      icon: mdi:play-circle

    "script.*":
      icon: mdi:play-circle

    "sensor.*_amps":
      icon: mdi:flash-circle

    "sensor.*_watts":
      icon: mdi:flash-circle

    "sensor.*_kwh":
      icon: mdi:flash-circle

    "sensor.*_volts":
      icon: mdi:flash-circle

    "timer.*":
      icon: mdi:timer-outline

    "sensor.*illumination*":
      icon: mdi:white-balance-sunny