#####################################################################
#    @package          :     accent_lights
#    @description      :     accent_lights and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'accent_lights'


    ################################################
    ## Switch
    ################################################
    switch.staircase_lamp:
      friendly_name: "Staircase Lamp"
      icon: mdi:lamp

    switch.wine_room_lamp:
      friendly_name: "Wine Room Lamp"
      icon: mdi:lamp


#####################################################################
### Switch
#####################################################################
switch:
  ### Sonoff wifi switches
  - platform: mqtt
    name: "Staircase Lamp"
    command_topic: "cmnd/sonoff0/power"
    state_topic: "stat/sonoff0/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Wine Room Lamp"
    command_topic: "cmnd/sonoff1/power"
    state_topic: "stat/sonoff1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true


#####################################################################
### Automation
#####################################################################
automation:
  ### Turn on the accent_lights at sunset
  - alias: Accent Lights On
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:05:00'

    action:
      - service: homeassistant.turn_on
        entity_id: group.accent_lights

  ### Turn off accent_lights if still on late night
  - alias: Accent Lights Auto Off
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.after_hours
      to: 'on'

    condition:
      condition: state
      entity_id: group.accent_lights
      state: 'on'

    action:
      - service: homeassistant.turn_off
        entity_id: group.accent_lights
