#####################################################################
#    @package          :     alexa_tts
#    @description      :     alexa_tts settings
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'alexa_tts'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true


    ################################################
    ## Input Text
    ################################################
    input_text.alexa_tts:
      icon: mdi:textbox


    ################################################
    ## Input Select
    ################################################
    input_select.alexa:
      icon: mdi:format-list-bulleted


    ################################################
    ## Input Number
    ################################################
    input_number.alexa_volume:
      icon: mdi:volume-high


#####################################################################
### Group
#####################################################################
group:
  Alexa TTS:
    entities:
      - input_number.alexa_volume
      - input_text.alexa_tts
      - input_select.alexa


#####################################################################
### Input Text
#####################################################################
input_text:
  alexa_tts:
    name: Alexa TTS
    initial: Hello


#####################################################################
### Input Number
#####################################################################
input_number:
  alexa_volume:
    name: Alexa Volume
    initial: 4
    min: 1
    max: 10
    step: 1


#####################################################################
### Input Select
#####################################################################
input_select:
  alexa:
    name: Alexa
    options:
      - None
      - Office
      - Living Room
      - Game Room
      - Kitchen
      - Master Bedroom
      - Nursery

    initial: None
    icon: mdi:target


#####################################################################
### Automation
#####################################################################
automation:
  ## Announce what is typed as input
  - alias: Alexa TTS
    trigger:
      platform: state
      entity_id: input_select.alexa
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: >
            {% if is_state('input_select.alexa', 'Living Room') %}
              media_player.living_room
            {% elif is_state('input_select.alexa', 'Master Bedroom') %}
              media_player.master_bedroom
            {% elif is_state('input_select.alexa', 'Kitchen') %}
              media_player.kitchen
            {% elif is_state('input_select.alexa', 'Game Room') %}
              media_player.game_room
            {% elif is_state('input_select.alexa', 'Nursery') %}
              media_player.nursery
            {% elif is_state('input_select.alexa', 'Office') %}
              media_player.office
            {% elif is_state('input_select.alexa', 'None') %}
              false
            {% endif %}
          volume_level: '{{ states.input_number.alexa_volume.state | float /10 }}'
      - service: media_player.alexa_tts
        data_template:
          entity_id: >
            {% if is_state('input_select.alexa', 'Living Room') %}
              media_player.living_room
            {% elif is_state('input_select.alexa', 'Master Bedroom') %}
              media_player.master_bedroom
            {% elif is_state('input_select.alexa', 'Kitchen') %}
              media_player.kitchen
            {% elif is_state('input_select.alexa', 'Game Room') %}
              media_player.game_room
            {% elif is_state('input_select.alexa', 'Nursery') %}
              media_player.nursery
            {% elif is_state('input_select.alexa', 'Office') %}
              media_player.office
            {% elif is_state('input_select.alexa', 'None') %}
              false
            {% endif %}
          message: "{{  states.input_text.alexa_tts.state }}"

      - delay: '00:00:02'

      - service: input_select.select_option
        data:
          entity_id: input_select.alexa
          option: None

