#####################################################################
#    @package          :     batteries
#    @description      :     batteries, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'batteries'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true


    ################################################
    ## Sensor
    ################################################
    sensor.lock_beach_battery:
      <<: *contained
      friendly_name: "Beach Bathroom Lock Battery"

    sensor.dc_beach_battery:
      <<: *contained
      friendly_name: "Beach Bathroom Door Battery"

    sensor.dc_front_door_battery:
      <<: *contained
      friendly_name: "Front Door Battery"

    sensor.dc_kitchen_door_battery:
      <<: *contained
      friendly_name: "Kitchen Door Battery"

    sensor.dc_south_door_battery:
      <<: *contained
      friendly_name: "South Door Battery"

    sensor.lock_south_battery:
      <<: *contained
      friendly_name: "South Lock Battery"

    sensor.entry_multisensor_battery:
      <<: *contained
      friendly_name: "Foyer Multisensor Battery"

    sensor.downstairs_ac_leak_detector_battery:
      <<: *contained
      friendly_name: "AC Leak Detector Battery"

    sensor.i8plus_battery_level:
      <<: *contained
      friendly_name: "Rick's Phone Battery"
      icon_template: >-
        {% set battery_level = states('sensor.i8plus_battery_level')|int('unknown') %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}

    sensor.mip8_battery_level_2:
      <<: *contained
      friendly_name: "Meg's Phone Battery"
      icon_template: >-
        {% set battery_level = states('sensor.mip8_battery_level_2')|int('unknown') %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}


#####################################################################
### Group
#####################################################################
group:
  Device Status:
    entities:
      - sensor.ring_front_door_last_motion
      - sensor.ring_front_door_last_ding
      - sensor.dc_front_door_battery
      - sensor.dc_kitchen_door_battery
      - sensor.lock_south_battery
      - sensor.south_door_battery
      - sensor.lock_beach_battery
      - sensor.dc_beach_battery
      - sensor.entry_multisensor_battery
      - sensor.downstairs_ac_leak_detector_battery


#####################################################################
### Sensor
#####################################################################
sensor:
  - platform: template
    sensors:
      ### Beach Lock Battery
      lock_beach_battery:
        value_template: "{{ (states.zwave.bathroom_entry.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.lock_beach_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
        entity_id: sensor.time


      ### South Lock Battery
      lock_south_battery:
        value_template: "{{ (states.zwave.south_entry.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.lock_south_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
        entity_id: sensor.time


      ### Front entry Fibaro Multisensor Battery
      entry_multisensor_battery:
        value_template: "{{ (states.zwave.front_entry_fibaro_multisensor.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.entry_multisensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
        entity_id: sensor.time


      ### Beach Bathroom Door Contact Battery
  - platform: template
    sensors:
      dc_beach_battery:
        value_template: "{{ (states.zwave.beach_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.dc_beach_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
        entity_id: sensor.time


      ### Front Door Contact Battery
  - platform: template
    sensors:
      dc_front_door_battery:
        value_template: "{{ (states.zwave.front_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.dc_front_door_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
        entity_id: sensor.time


      ### Kitchen Door Contact Battery
  - platform: template
    sensors:
      dc_kitchen_door_battery:
        value_template: "{{ (states.zwave.kitchen_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.dc_kitchen_door_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
        entity_id: sensor.time


      ### South Door Contact Battery
  - platform: template
    sensors:
      dc_south_door_battery:
        value_template: "{{ (states.zwave.south_door_contact.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.dc_south_door_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
        entity_id: sensor.time


      ### Downstairs AC Leak Detector Battery
      downstairs_ac_leak_detector_battery:
        value_template: "{{ (states.zwave.everspring_st812_flood_detector.attributes|default).battery_level|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.downstairs_ac_leak_detector_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
        entity_id: sensor.time
