#####################################################################
#    @package          :     security_cameras
#    @description      :     security_cameras and associated automations, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'cameras'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true


    ################################################
    ## Group
    ################################################
    group.camera_front_porch:
      <<: *contained

    group.camera_north_gate:
      <<: *contained

    group.camera_nw_ptz:
      <<: *contained

    group.camera_nursery_ptz:
      <<: *contained

    group.camera_ring_doorbell:
      <<: *contained


#####################################################################
### Group
#####################################################################
group:
  camera_front_porch:
    name: Front Porch Camera
    entities:
      - camera.front_porch

  camera_north_gate:
    name: North Gate Camera
    entities:
      - camera.north_gate

  camera_nw_ptz:
    name: NW PTZ Camera
    entities:
      - camera.nw_ptz

  camera_nursery_ptz:
    name: Nursery PTZ Camera
    entities:
      - camera.nursery_ptz

  camera_ring_doorbell:
    name: Front Door Camera
    entities:
      - camera.front_door

  Camera Status:
    entities:
      - sensor.nursery_ptz_preset
      - sensor.nw_ptz_preset
      - sensor.nursery_ptz_sd_used
      - sensor.nw_ptz_sd_used

  Traffic Report:
    entities:
#      - camera.east_valley_traffic
#      - camera.inbound_traffic
#      - camera.downtown_traffic
      - camera.ramp_traffic

#####################################################################
### Camera
#####################################################################
camera:
  - platform: generic
    still_image_url: !secret front_door_url
    name: Front Porch
    username: !secret camera_user
    password: !secret camera_password

  - platform: generic
    still_image_url: !secret north_gate_url
    name: North Gate
    username: !secret camera_user
    password: !secret camera_password

  - platform: ring
    name: Front Door

#  - platform: generic
#    still_image_url: !secret ib_image_url
#    name: Inbound Traffic

  - platform: generic
    still_image_url: !secret 10_ramp_url
    name: Ramp Traffic

  - platform: generic
    still_image_url: !secret doppler_url
    name: Weather

#####################################################################
### Amcrest
#####################################################################
amcrest:
  ### NW PTZ
  - host: !secret north_ptz_host
    name: NW PTZ
    username: !secret camera_user
    password: !secret camera_password
    port: !secret north_ptz_port
    resolution: high
    stream_source: rtsp
    sensors:
      - motion_detector

  ### NURSERY PTZ
  - host: !secret nursery_ptz_host
    name: Nursery PTZ
    username: !secret camera_user
    password: !secret camera_password
    port: !secret nursery_ptz_port
    resolution: high
    stream_source: rtsp
    sensors:
      - motion_detector
