#####################################################################
#    @package          :     security_cameras
#    @description      :     security_cameras and associated automations, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'cameras'

      hidden: &hidden
        <<: *customize
        hidden: true


#####################################################################
### Camera
#####################################################################
camera:
  - platform: generic
    still_image_url: !secret front_door_url
    name: Front Porch
    username: !secret camera_user
    password: !secret camera_password

  - platform: generic
    still_image_url: !secret north_gate_url
    name: North Gate
    username: !secret camera_user
    password: !secret camera_password

  - platform: ring

  - platform: generic
    still_image_url: !secret 10_ramp_url
    name: Ramp Traffic

  - platform: generic
    still_image_url: !secret doppler_url
    name: Weather

#####################################################################
### Amcrest
#####################################################################
amcrest:
  ### NW PTZ
  - host: !secret north_ptz_host
    name: NW PTZ
    username: !secret camera_user
    password: !secret camera_password
    port: !secret north_ptz_port
    resolution: high
    stream_source: rtsp
    sensors:
      - motion_detector

  ### NURSERY PTZ
  - host: !secret nursery_ptz_host
    name: Nursery PTZ
    username: !secret camera_user
    password: !secret camera_password
    port: !secret nursery_ptz_port
    resolution: high
    stream_source: rtsp
    sensors:
      - motion_detector
