#####################################################################
#    @package          :     dasher events
#    @description      :     system and associated automations, etc.
#####################################################################
automation:
  ### Begin bedtime countdown when Dasher Wellness is pressed
  - alias: Dasher Bedtime Timer
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer_bedtime

    action:
      - service: timer.start
        entity_id: timer.bedtime

  ### Turn on the nightlight when Laundress Dash button is pressed
  - alias: Dasher Night Time
    initial_state: 'on'
    trigger:
      platform: event
      event_type: script_night_time

    action:
      - service: script.turn_on
        entity_id: script.master_bedroom_night_time