#####################################################################
#    @package          :     device_trackers
#    @description      :     zones, device trackers and associated automations, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'device_trackers'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Device Trackers
    ################################################
    device_tracker.i8plus:
      friendly_name: "Rick"
      entity_picture: /local/rick.jpg

    device_tracker.mip8:
      friendly_name: "Megs"
      entity_picture: /local/megs.jpg

    ################################################
    ## Sensor
    ################################################
    sensor.ricks_office_commute:
      friendly_name: "Ricks Commute to Work"
      icon: mdi:car

    sensor.ricks_home_commute:
      friendly_name: "Ricks Commute Home"
      icon: mdi:car

    sensor.megs_work_commute:
      friendly_name: "Megs Commute to Work"
      icon: mdi:car

    sensor.megs_home_commute:
      friendly_name: "Megs Commute Home"
      icon: mdi:car

    sensor.ricks_eta_home:
      friendly_name: "Ricks ETA"
      icon: mdi:timer

    sensor.ricks_eta:
      icon: mdi:timer

    sensor.megs_eta_home:
      friendly_name: "Megs ETA"
      icon: mdi:timer

    sensor.megs_eta:
      icon: mdi:timer


################################################################
## Device Tracker
################################################################
device_tracker:
  - platform: ddwrt
    host: !secret router_ip
    username: !secret router_user
    password: !secret router_pass
    track_new_devices: no
    consider_home: 180

  - platform: icloud
    username: !secret icloud_megs
    password: !secret icloud_megs_password


################################################################
##  Proximity
################################################################
proximity:
  home:
    ignored_zones:
      - ricks_office
      - megs_work
    devices:
      - device_tracker.mip8
      - device_tracker.i8plus
    tolerance: 50
    unit_of_measurement: mi

  rick:
    ignored_zones:
      - megs_work
    devices:
      - device_tracker.i8plus
    tolerance: 50
    unit_of_measurement: mi


#####################################################################
###  Sensor
#####################################################################
sensor:

  - platform: google_travel_time
    scan_interval: 900
    name: Ricks Office Commute
    api_key: !secret google_time_travel_api_key
    origin: Home
    destination: Office

  - platform: google_travel_time
    scan_interval: 900
    name: Ricks Home Commute
    api_key: !secret google_time_travel_api_key
    origin: Office
    destination: Home

#  - platform: google_travel_time
#    scan_interval: 420
#    name: Megs Work Commute
#    api_key: !secret google_time_travel_api_key
#    origin: Home
#    destination: Arete

#  - platform: google_travel_time
#    scan_interval: 420
#    name: Megs Home Commute
#    api_key: !secret google_time_travel_api_key
#    origin: Arete
#    destination: Home

  - platform: google_travel_time
    scan_interval: 300
    name: Megs ETA Home
    api_key: !secret google_time_travel_api_key
    origin: device_tracker.mip8
    destination: Home

  - platform: google_travel_time
    scan_interval: 600
    name: Ricks ETA Home
    api_key: !secret google_time_travel_api_key
    origin: device_tracker.i8plus
    destination: Home

  - platform: template
    sensors:
      ricks_eta:
        friendly_name: "Rick's ETA"
        value_template: >-
          {% if is_state('sensor.ricks_eta_home', '0') %}
            Home
          {% else %}
            {{ states('sensor.ricks_eta_home') }}
          {% endif %}
        entity_id: sensor.time

      megs_eta:
        friendly_name: "Meg's ETA"
        value_template: >-
          {% if is_state('sensor.megs_eta_home', '0') %}
            Home
          {% else %}
            {{ states('sensor.megs_eta_home') }}
          {% endif %}
        entity_id: sensor.time


#####################################################################
###  Automation
#####################################################################
automation:
  ### Away Mode Countdown
  - alias: Away Mode Countdown
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.all_devices
        from: 'home'
        to: 'not_home'
        for:
          minutes: 5

    condition:
      - condition: state
        entity_id: input_boolean.visitor_mode
        state: 'off'

    action:
      - service: timer.start
        entity_id: timer.away_mode

      - service: notify.ios_i8plus
        data:
          title: "Away Detected"
          message: "Counting down..."
          data:
            push:
              category: cancelaway


  ### Away Mode Timer Finish
  - alias: Away Mode On
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.away_mode

    action:
      - service: script.away


  ### Away Mode Cancel
  - alias: Away Mode Cancel
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: group.all_devices
        from: 'not_home'
        to: 'home'

    condition:
      - condition: template
        value_template: "{{ states('timer.away_mode') != 'idle'}}"

    action:
      - service: timer.cancel
        entity_id: timer.away_mode

      - service: notify.ios_i8plus
        data:
          title: "Away Mode Cancelled"
          message: "Away mode cancelled."


  ### Turn on Visitor Mode if we foget to
  - alias: Enable Visitor Mode
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: template
        value_template: "{{ states('sensor.lock_south_door_status') == 'Unlocked by Dog Sitter' }}"

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'

      - condition: state
        entity_id: input_boolean.visitor_mode
        state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.visitor_mode


  ### Cancel Visitor Mode
  - alias: Cancel Visitor Mode
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: group.all_devices
        from: 'not_home'
        to: 'home'

    condition:
      - condition: state
        entity_id: input_boolean.visitor_mode
        state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.visitor_mode


  ### Announce Rick's arrival
  - alias: Announce Rick On Arrival
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: proximity.rick
        below: 5

    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'

      - condition: time
        before: '19:00:00'
        after: '14:00:00'

      - condition: state
        entity_id: device_tracker.i8plus
        state: 'not_home'


    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room
          volume_level: .5

      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room
          message: "Good news, Rick is less than 10 minutes away and will be home soon"
