#####################################################################
#    @package          :     game_room
#    @description      :     game_room and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'game_room'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Switch
    ################################################
    switch.game_room_lights:
      friendly_name: "Game Room Lights"
      icon: mdi:ceiling-light



