#####################################################################
#    @package          :     game_room
#    @description      :     game_room and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'game_room'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
#    group.game_room:
#      <<: *contained
#      friendly_name: "Game Room"
#      order: 6

    ################################################
    ## Switch
    ################################################
    switch.game_room_lights_switch:
      friendly_name: "Game Room Lights"
      icon: mdi:ceiling-light


#####################################################################
### Group
#####################################################################
group:
  Game Room:
    entities:
      - switch.game_room_lights_switch
