#####################################################################
#    @package          :     homekit
#    @description      :     homekit configuration for apple ios
#####################################################################
homekit:
  auto_start: False
  ip_address: !secret homekit_ip

  filter:
    include_entities:
#################################
# Device Tracker
#################################
      - device_tracker.i8plus
      - device_tracker.mip8

#################################
# Climate - enabled
#################################
      - climate.downstairs
      - climate.upstairs

#################################
# Lights - enabled
#################################
      - light.entryway
      - light.living_room
      - light.foyer_lights_level
      - light.dining_room_chandelier_level
      - light.kitchen_lights_level
      - light.living_room_lamp
      - light.master_bathroom
      - light.master_bed_ceiling_level
      - light.master_bed_entry_level
      - light.master_bedroom_chandelier_level
      - light.master_reading_lamp
      - light.master_sitting_lamp
      - light.nursery_wall_light
      - light.wine_room
      - light.office_desk_lamp
      - light.under_bed_lights

#################################
# Switches - enabled
#################################
      - switch.game_room_lights
      - switch.directv_power
      - switch.flower_lamp
      - switch.fountains_switch
      - switch.living_room_fan
      - switch.patio_lights_switch
      - switch.pool_light_switch
      - switch.tv_mute
      - switch.tv_power
      - switch.wine_room_lamp
      - switch.front_porch_lights_switch
      - switch.south_porch_lights_switch
      - switch.downstairs_bath_lights_switch
      - switch.outdoor_speakers

#################################
# Scripts - enabled
#################################
      - script.ecobee_us_home
      - script.ecobee_us_resume
      - script.ecobee_ds_home
      - script.ecobee_ds_resume
      - script.start_bedtime_timer
      - script.hue_lr_bright
      - script.hue_lr_christmas
      - script.hue_lr_daybreak
      - script.hue_lr_dimmed
      - script.hue_lr_minty
      - script.hue_lr_movie
      - script.hue_lr_nightlight
      - script.hue_lr_sunrise
      - script.hue_lr_sunset
      - script.hue_mbath_morning

#################################
# Sensors - enabled
#################################
      - sensor.downstairs_humidity
      - sensor.downstairs_temperature
      - sensor.ds_avg_temp
      - sensor.guest_room_temperature
      - sensor.nursery_temperature
      - sensor.living_room_temperature
      - sensor.upstairs_humidity
      - sensor.upstairs_temperature
      - sensor.us_avg_temp
      - sensor.office_temperature


################################################
## Entity Configuration - Customize Devices
################################################
  entity_config:
    switch.flower_lamp:
      type: outlet

    switch.outdoor_speakers:
      type: outlet


################################################
## Automation - wait for z-wave network
################################################
automation:
  - alias: "Start HomeKit"
    trigger:
      - platform: event
        event_type: zwave.network_ready

    action:
#      - delay: 00:05
      - service: homekit.start

#################################
# Lights - disabled
#################################
#      - light.a020a60d26b2_1921681032
#      - light.a020a61d8740_1921681033
#      - light.center_entry
#      - light.downstairs_bath_light_1
#      - light.downstairs_bath_light_2
#      - light.downstairs_bath_light_3
#      - light.kitchen_light_east
#      - light.kitchen_entry
#      - light.lr_ceiling
#      - light.master_bath_entry
#      - light.master_bath_sink
#      - light.master_bathtub
#      - light.master_bedroom
#      - light.master_br_entry_north
#      - light.patio_light_north
#      - light.foyer_upstairs_north
#      - light.northeast_ceiling
#      - light.kitchen_light_northeast
#      - light.master_br_ceiling_ne
#      - light.northeast_wine
#      - light.northwest_ceiling
#      - light.kitchen_light_northwest
#      - light.master_br_ceiling_nw
#      - light.porch_light_northwest
#      - light.northwest_wine
#      - light.sn1_led
#      - light.south_entry
#      - light.master_br_entry_south
#      - light.patio_light_south
#      - light.porch_light_south
#      - light.foyer_upstairs_south
#      - light.southeast_ceiling
#      - light.kitchen_light_southeast
#      - light.master_br_ceiling_se
#      - light.porch_light_southeast
#      - light.southeast_wine
#      - light.southwest_ceiling
#      - light.kitchen_light_southwest
#      - light.master_br_ceiling_sw
#      - light.porch_light_southwest
#      - light.southwest_wine
#      - light.kitchen_light_west
#      - light.porch_light_west

#################################
# Switches - disabled
#################################
#      - switch.amp_input_dvd
#      - switch.amp_input_movie
#      - switch.amp_input_tv
#      - switch.amp_input_ipod
#      - switch.amp_movie_mode
#      - switch.amp_music_mode
#      - switch.amp_mute
#      - switch.amp_power
#      - switch.amp_volume
#      - switch.kitchen_roller_shade_switch
#      - switch.living_room_fan_high
#      - switch.living_room_fan_light
#      - switch.living_room_fan_low
#      - switch.living_room_fan_medium
#      - switch.master_bath_roller_shades_switch
#      - switch.master_bedroom_fan
#      - switch.master_bedroom_fan_1
#      - switch.master_bedroom_fan_10
#      - switch.master_bedroom_fan_11
#      - switch.master_bedroom_fan_12
#      - switch.master_bedroom_fan_2
#      - switch.master_bedroom_fan_3
#      - switch.master_bedroom_fan_4
#      - switch.master_bedroom_fan_5
#      - switch.master_bedroom_fan_6
#      - switch.master_bedroom_fan_7
#      - switch.master_bedroom_fan_8
#      - switch.master_bedroom_fan_9
#      - switch.master_bedroom_fan_delay
#      - switch.master_bedroom_fan_light
#      - switch.master_bedroom_fan_random
#      - switch.patio_party_lights_switch
#      - switch.staircase_lamp
#      - switch.tv_input_chromecast
#      - switch.tv_input_directv
#      - switch.tv_input_firetv
#      - switch.tv_volume
#      - switch.switch_five
#      - switch.switch_four
#      - switch.switch_one
#      - switch.switch_three
#      - switch.switch_two

#################################
# Scripts - disabled
#################################
#      - script.close_kitchen_shade
#      - script.close_master_bath_shades
#      - script.time_temp
#      - script.master_bedroom_night_time
#      - script.mbr_night_light
#      - script.open_kitchen_shade
#      - script.open_master_bath_shades
#      - script.stop_kitchen_shade
#      - script.stop_master_bath_shades
#      - script.away
#      - script.company_mode
#      - script.desk_lamp_test
#      - script.ecobee_ds_away
#      - script.ecobee_ds_sleep
#      - script.ecobee_us_away
#      - script.ecobee_us_sleep
#      - script.mbr_fan_speed_step
#      - script.morning_sequence
#      - script.nap_time
#      - script.pool_blue
#      - script.pool_caribbean
#      - script.pool_cycle
#      - script.pool_green
#      - script.pool_magenta
#      - script.pool_party
#      - script.pool_patriotic
#      - script.pool_red
#      - script.pool_romance
#      - script.pool_royal
#      - script.pool_sunset
#      - script.pool_white
#      - script.rgb_strip_test
#      - script.script_test
#      - script.tv_power_off
#      - script.unlock_megs

#################################
# Covers - disabled
#################################
#      - cover.kitchen_roller_shade_level
#      - cover.kitchen_roller_shade_switch
#      - cover.kitchen_shade
#      - cover.master_bath_roller_shades_level
#      - cover.master_bath_roller_shades_switch
#      - cover.master_bath_shades

#################################
# Locks - disabled
#################################
#      - lock.bathroom_entry_locked
#      - lock.south_entry_locked

#################################
# Sensors - disabled
#################################
#      - sensor.bathroom_entry_alarm_level
#      - sensor.bathroom_entry_alarm_type
#      - sensor.bathroom_door_contact_access_control
#      - sensor.beach_door_contact_alarm_level
#      - sensor.beach_door_contact_alarm_type
#      - sensor.beach_door_contact_burglar
#      - sensor.beach_door_contact_sourcenodeid
#      - sensor.bathroom_door_state
#      - sensor.beach_door_tamper
#      - sensor.broadlink_sensor_temperature
#      - sensor.clock_am_pm
#      - sensor.clock_date
#      - sensor.clock_day
#      - sensor.clock_time
#      - sensor.crime
#      - sensor.dark_sky_cloud_coverage
#      - sensor.dark_sky_daily_max_precip_intensity
#      - sensor.dark_sky_daily_summary
#      - sensor.dark_sky_minutely_summary
#      - sensor.dark_sky_nearest_storm_distance
#      - sensor.dark_sky_precip_intensity
#      - sensor.dark_sky_precip_probability
#      - sensor.day_after_that
#      - sensor.day_after_tomorrow
#      - sensor.disk_free_home
#      - sensor.ds_climate_setting
#      - sensor.ds_climate_target_high
#      - sensor.ds_climate_target_low
#      - sensor.ds_fan_state
#      - sensor.entry_multisensor_battery
#      - sensor.entryway_temperature
#      - sensor.floorplan_date
#      - sensor.floorplan_time
#      - sensor.front_door_contact_access_control
#      - sensor.front_door_contact_alarm_level
#      - sensor.front_door_contact_alarm_type
#      - sensor.front_door_contact_burglar
#      - sensor.front_door_contact_sourcenodeid
#      - sensor.front_door_state
#      - sensor.front_door_tamper
#      - sensor.front_entry_fibaro_multisensor_alarm_level
#      - sensor.front_entry_fibaro_multisensor_alarm_type
#      - sensor.front_entry_fibaro_multisensor_burglar
#      - sensor.front_entry_fibaro_multisensor_general
#      - sensor.front_entry_fibaro_multisensor_luminance
#      - sensor.front_entry_fibaro_multisensor_seismic_intensity
#      - sensor.front_entry_fibaro_multisensor_sourcenodeid
#      - sensor.front_entry_fibaro_multisensor_temperature
#      - sensor.front_entry_motion
#      - sensor.ha_current_version
#      - sensor.ha_last_restart
#      - sensor.holiday
#      - sensor.rip8plus_battery_level
#      - sensor.i8plus_battery_state
#      - sensor.mip8_battery_level
#      - sensor.mip8_battery_state_2
#      - sensor.iphwn666_battery_level
#      - sensor.iphwn666_battery_state
#      - sensor.kitchen_door_access_control
#      - sensor.kitchen_door_alarm_level
#      - sensor.kitchen_door_alarm_type
#      - sensor.kitchen_door_burglar
#      - sensor.kitchen_door_sourcenodeid
#      - sensor.kitchen_door_state
#      - sensor.kitchen_door_tamper
#      - sensor.last_boot
#      - sensor.lock_beach_battery
#      - sensor.lock_beach_door_status
#      - sensor.lock_south_battery
#      - sensor.lock_south_door_status
#      - sensor.master_bedroom_fan
#      - sensor.master_bedroom_fan_1
#      - sensor.master_bedroom_fan_10
#      - sensor.master_bedroom_fan_11
#      - sensor.master_bedroom_fan_12
#      - sensor.master_bedroom_fan_2
#      - sensor.master_bedroom_fan_3
#      - sensor.master_bedroom_fan_4
#      - sensor.master_bedroom_fan_5
#      - sensor.master_bedroom_fan_6
#      - sensor.master_bedroom_fan_7
#      - sensor.master_bedroom_fan_8
#      - sensor.master_bedroom_fan_9
#      - sensor.megs_eta
#      - sensor.megs_eta_home
#      - sensor.megs_home_commute
#      - sensor.megs_work_commute
#      - sensor.memory_free
#      - sensor.moon
#      - sensor.nursery_ptz_motion_detected
#      - sensor.nw_ptz_motion_detected
#      - sensor.processor_use
#      - sensor.pws_alerts
#      - sensor.pws_dewpoint_f
#      - sensor.pws_dewpoint_string
#      - sensor.pws_feelslike_f
#      - sensor.pws_feelslike_string
#      - sensor.pws_heat_index_f
#      - sensor.pws_heat_index_string
#      - sensor.pws_observation_time
#      - sensor.pws_precip_today_in
#      - sensor.pws_precip_today_string
#      - sensor.pws_pressure_in
#      - sensor.pws_pressure_mb
#      - sensor.pws_relative_humidity
#      - sensor.pws_solarradiation
#      - sensor.pws_station_id
#      - sensor.pws_temp_f
#      - sensor.pws_uv
#      - sensor.pws_visibility_mi
#      - sensor.pws_weather
#      - sensor.pws_wind_dir
#      - sensor.pws_wind_mph
#      - sensor.pws_wind_string
#      - sensor.rf_switch_five
#      - sensor.rf_switch_four
#      - sensor.rf_switch_one
#      - sensor.rf_switch_three
#      - sensor.rf_switch_two
#      - sensor.ricks_eta
#      - sensor.ricks_eta_home
#      - sensor.ricks_home_commute
#      - sensor.ricks_office_commute
#      - sensor.sabnzbd_disk
#      - sensor.sabnzbd_disk_free
#      - sensor.sabnzbd_left
#      - sensor.sabnzbd_queue
#      - sensor.sabnzbd_speed
#      - sensor.sabnzbd_status
#      - sensor.season
#      - sensor.sn1_humidity
#      - sensor.sn1_ldr
#      - sensor.sn1_pir
#      - sensor.sn1_temperature
#      - sensor.south_door_contact_access_control
#      - sensor.south_door_contact_alarm_level
#      - sensor.south_door_contact_alarm_type
#      - sensor.south_door_contact_burglar
#      - sensor.south_door_contact_sourcenodeid
#      - sensor.south_door_state
#      - sensor.south_door_tamper
#      - sensor.south_entry_alarm_level
#      - sensor.south_entry_alarm_type
#      - sensor.speedtest_download
#      - sensor.speedtest_ping
#      - sensor.speedtest_upload
#      - sensor.staircase_lamp
#      - sensor.time_brightness
#      - sensor.tomorrow
#      - sensor.uptime
#      - sensor.us_climate_setting
#      - sensor.us_climate_target_high
#      - sensor.us_climate_target_low
#      - sensor.us_fan_state
#      - sensor.wine_room_lamp
#      - sensor.yw_day2_condition
#      - sensor.yw_day2_temperature_max
#      - sensor.yw_day2_temperature_min
#      - sensor.yw_day3_condition
#      - sensor.yw_day3_temperature_max
#      - sensor.yw_day3_temperature_min
#      - sensor.yw_tomorrow_condition
#      - sensor.yw_tomorrow_temperature_max
#      - sensor.yw_tomorrow_temperature_min
#      - sensor.yweather_condition
#      - sensor.yweather_current
#      - sensor.yweather_humidity
#      - sensor.yweather_pressure
#      - sensor.yweather_temperature
#      - sensor.yweather_temperature_max
#      - sensor.yweather_temperature_min
#      - sensor.yweather_visibility
#      - sensor.yweather_wind_speed
