#####################################################################
#    @package          :     input_boolean
#    @description      :     input_boolean configurations
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'input_boolean'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Input Boolean
    ################################################
    input_boolean.visitor_mode:
      icon: mdi:account

    input_boolean.vacation_mode:
      icon: mdi:beach

    input_boolean.dinner_time:
      icon: mdi:food-fork-drink

    input_boolean.door_held_open:
      icon: mdi:door-open


#####################################################################
### Input Boolean
#####################################################################
input_boolean:
  visitor_mode:
    name: Visitor Mode
    initial: off

  vacation_mode:
    name: Vacation Mode
    initial: off

  dinner_time:
    name: Dinner Time
    initial: off

  door_held_open:
    name: Door Held Open
    initial: off
