#####################################################################
#    @package          :     kitchen_dining
#    @description      :     kitchen and dining room automations, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'kitchen_dining'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Light
    ################################################
    light.kitchen_lights_level:
      friendly_name: "Kitchen Lights"
      icon: mdi:white-balance-incandescent

    light.dining_room_chandelier_level:
      friendly_name: "Dining Room Light"
      icon: mdi:ceiling-light


#####################################################################
### Automation
#####################################################################
automation:
### Turn on the pantry light when door opens
  - alias: Pantry Light Toggle
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.pantry_door_contact
#        from: 'off'
#        to: 'on'

    action:
      - service: light.toggle
        data:
          entity_id: light.pantry


### Turn off the pantry light when door is closed
  - alias: Pantry Light Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.pantry_door_contact
        from: 'on'
        to: 'off'
        for:
          seconds: 15

    condition:
      - condition: state
        entity_id: light.pantry
        state: 'on'

    action:
      - service: light.turn_off
        data:
          entity_id: light.pantry
