#####################################################################
#    @package          :     kitchen_dining
#    @description      :     kitchen and dining room automations, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'kitchen_dining'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Light
    ################################################
    light.kitchen_lights_level:
      friendly_name: "Kitchen Lights"
      icon: mdi:white-balance-incandescent

    light.dining_room_chandelier_level:
      friendly_name: "Dining Room Light"
      icon: mdi:ceiling-light


#####################################################################
### Automation
#####################################################################
#automation:

