#####################################################################
#    @package          :     light_config
#    @description      :     configuration for lighting
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'light_config'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true


    ################################################
    ## Sensor
    ################################################
    sensor.time_brightness:
      <<: *hidden


#####################################################################
### Light
#####################################################################
hue:
  bridges:
    - host: !secret hue_host
      allow_unreachable: true
      allow_hue_groups: true


################################################################
## Sensor
################################################################
sensor:
  ### Time Based Brightness
  - platform: template
    sensors:
      time_brightness:
        value_template: >-
          {%- if now().strftime('%H%M')|int < 600 -%}
            64
          {%- elif now().strftime('%H%M')|int < 700 -%}
            128
          {%- elif now().strftime('%H%M')|int < 900 -%}
            192
          {%- elif now().strftime('%H%M')|int < 2000 -%}
            255
          {%- elif now().strftime('%H%M')|int < 2200 -%}
            192
          {%- elif now().strftime('%H%M')|int < 2300 -%}
            128
          {%- else -%}
            64
          {%- endif -%}
        entity_id: sensor.time
