#####################################################################
#    @package          :     living_room_fan
#    @description      :     living room ceiling fan controls
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'living_room_fan'
        homebridge_hidden: true

      contained: &contained
        <<: *customize
        haaska_hidden: true
#        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
#        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
#    group.living_room_fan:
#      <<: *contained
#      order: 1

    ################################################
    ## Switch
    ################################################
    switch.living_room_fan:
      icon: mdi:fan

    switch.living_room_fan_low:
      haaska_name: "Living Room Fan Low"

    switch.living_room_fan_medium:
      haaska_name: "Living Room Fan Medium"

    switch.living_room_fan_high:
      haaska_name: "Living Room Fan High"

    switch.living_room_fan_light:
      assumed_state: false
      icon: mdi:ceiling-light

    ################################################
    ## Input Select
    ################################################
    input_select.living_room_fan_speed:
      icon: mdi:fan
      <<: *contained


#####################################################################
### Group
#####################################################################
group:
  Living Room Fan:
    control: hidden
    entities:
      - switch.living_room_fan
      - input_select.living_room_fan_speed
      - switch.living_room_fan_light


#####################################################################
### Input Select
#####################################################################
input_select:
  ### Living Room Ceiling Fan Speed
  living_room_fan_speed:
    name: Living Room Fan
    initial: "Select an option..."
    options:
      - "Select an option..."
      - "Low"
      - "Medium"
      - "High"


#####################################################################
### Automation
#####################################################################
automation:
  ### Living Room Ceiling Fan
  - alias: Living Room Ceiling Fan Speed Select
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.living_room_fan_speed

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

    action:
      ### Turn the corresponding switch on to send the fan speed command
      - service: switch.turn_on
        entity_id: switch.living_room_fan

      - delay:
          seconds: 2

      - service: switch.turn_on
        data_template:
          entity_id: "switch.living_room_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

      ### Reset the Input Select to "Select an option..."
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...

  ### Default Living Room Ceiling Fan to High
  - alias: Living Room Ceiling Fan Default Speed
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.living_room_fan
        from: 'off'
        to: 'on'

    action:
      ### Turn the corresponding switch on to send the fan speed command
      - service: input_select.select_option
        data_template:
          entity_id: input_select.living_room_fan_speed
          option: High