#####################################################################
#    @package          :     master_bath
#    @description      :     master bath lights and Somfy RTS Shades
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'master_bath'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.master_bath:
      <<: *contained
      order: 4

    ################################################
    ## Light
    ################################################
    light.master_bathroom:
      <<: *contained
      friendly_name: "Master Bathroom Lights"
      icon: mdi:google-circles-communities

    light.master_bath_entry:
      <<: *contained
      icon: mdi:white-balance-incandescent

    light.master_bath_sink:
      <<: *contained
      icon: mdi:white-balance-incandescent

    light.master_bathtub:
      <<: *contained
      icon: mdi:white-balance-incandescent

    ################################################
    ## Cover
    ################################################
    cover.master_bath_roller_shades_level:
      <<: *contained
      device_class: garage
      friendly_name: "Master Bath Rollershades"
      homebridge_cover_type: rollershutter
      icon: mdi:blinds

    cover.master_bath_roller_shades_switch:
      <<: *hidden
      device_class: garage
      friendly_name: "Master Bath Rollershade State"
      icon: mdi:blinds

    cover.master_bath_shade:
      <<: *contained
      device_class: garage
      friendly_name: "Master Bath Shades"
      homebridge_cover_type: rollershutter
      icon: mdi:blinds


#####################################################################
### Group
#####################################################################
group:
  Master Bath:
    control: hidden
    entities:
      - script.hue_mbath_morning
      - light.master_bathroom
      - light.master_bath_entry
      - light.master_bath_sink
      - light.master_bathtub
      - cover.master_bath_roller_shades_level

  Master Bath Lights:
    entities:
      - light.master_bath_entry
      - light.master_bath_sink
      - light.master_bathtub


#####################################################################
### Cover (custom test for alexa control)
#####################################################################
#cover:
#  - platform: template
#    covers:
#      master_bath_shades:
#        friendly_name: 'Master Bath Shades'
#        open_cover:
#          service: script.turn_on
#          entity_id: script.open_master_bath_shades
#        close_cover:
#          service: script.turn_on
#          entity_id: script.close_master_bath_shades
#        stop_cover:
#          service: script.turn_on
#          entity_id: script.stop_master_bath_shades


#####################################################################
### Script
#####################################################################
#script:
#  ### Alexa Open Master Bath Shades
#  open_master_bath_shades:
#    alias: "Open Master Bath Shades"
#    sequence:
#    - service: cover.open_cover
#      entity_id: cover.master_bath_roller_shades_level
#
#  ### Alexa Close Master Bath Shades
#  close_master_bath_shades:
#    alias: "Close Master Bath Shades"
#    sequence:
#    - service: cover.close_cover
#      entity_id: cover.master_bath_roller_shades_level
#
#  ### Alexa Park Master Bath Shades
#  stop_master_bath_shades:
#    alias: "Park Master Bath Shades"
#    sequence:
#    - service: cover.stop_cover
#      entity_id: cover.master_bath_roller_shades_level


#####################################################################
### Automation
#####################################################################
automation:
  ### master bath shade raised schedule
  - alias: Master Bath Shade Up
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: time
        at: '11:00:00'

    action:
      - service: cover.open_cover
        entity_id: cover.master_bath_roller_shades_level

  ### master bath shade lowered schedule
  - alias: Master Bath Shade Down
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: '00:15:00'

    action:
      - service: cover.close_cover
        entity_id: cover.master_bath_roller_shades_level
