############################################################################
#    @package          :     master_bedroom_fan
#    @description      :     master bedroom ceiling fan and associated automations, scenes, etc.
############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'master_bedroom_fan'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.master_bedroom_fan:
      <<: *contained
      order: 2

    group.mbr_fan_speed:
      <<: *hidden

    ################################################
    ## Switch
    ################################################
    switch.master_bedroom_fan:
      friendly_name: "Master Bedroom Fan"
      icon: mdi:fan

    switch.master_bedroom_fan_light:
      assumed_state: false
      friendly_name: "Bedroom Fan Light"
      icon: mdi:ceiling-light

    switch.master_bedroom_fan_1:
      <<: *contained

    switch.master_bedroom_fan_2:
      <<: *contained

    switch.master_bedroom_fan_3:
      <<: *contained

    switch.master_bedroom_fan_4:
      <<: *contained

    switch.master_bedroom_fan_5:
      <<: *contained

    switch.master_bedroom_fan_6:
      <<: *contained


    ### WINTER SPEEDS
    switch.master_bedroom_fan_7:
      <<: *contained

    switch.master_bedroom_fan_8:
      <<: *contained

    switch.master_bedroom_fan_9:
      <<: *contained

    switch.master_bedroom_fan_10:
      <<: *contained

    switch.master_bedroom_fan_11:
      <<: *contained

    switch.master_bedroom_fan_12:
      <<: *contained

    switch.master_bedroom_fan_random:
      <<: *contained

    switch.master_bedroom_fan_vacation:
      <<: *contained

    switch.master_bedroom_fan_delay:
      <<: *contained

    ################################################
    ## Sensor
    ################################################
    sensor.master_bedroom_fan:
      <<: *hidden

    sensor.master_bedroom_fan_1:
      <<: *hidden

    sensor.master_bedroom_fan_2:
      <<: *hidden

    sensor.master_bedroom_fan_3:
      <<: *hidden

    sensor.master_bedroom_fan_4:
      <<: *hidden

    sensor.master_bedroom_fan_5:
      <<: *hidden

    sensor.master_bedroom_fan_6:
      <<: *hidden

    sensor.master_bedroom_fan_7:
      <<: *hidden

    sensor.master_bedroom_fan_8:
      <<: *hidden

    sensor.master_bedroom_fan_9:
      <<: *hidden

    sensor.master_bedroom_fan_10:
      <<: *hidden

    sensor.master_bedroom_fan_11:
      <<: *hidden

    sensor.master_bedroom_fan_12:
      <<: *hidden


    ################################################
    ## Script
    ################################################
    script.mbr_fan_speed_step:
      <<: *contained
      friendly_name: "Master Bedroom Fan Auto"
      icon: mdi:fan


#####################################################################
### Group
#####################################################################
group:
  Master Bedroom Fan:
    control: hidden
    entities:
      - switch.master_bedroom_fan
      - switch.master_bedroom_fan_light
      - input_select.master_bedroom_fan_speed
      - script.mbr_fan_speed_step_low
      - script.mbr_fan_speed_step_high

  MBR Fan Speed:
    entities:
      - switch.master_bedroom_fan_1
      - switch.master_bedroom_fan_2
      - switch.master_bedroom_fan_3
      - switch.master_bedroom_fan_4
      - switch.master_bedroom_fan_5
      - switch.master_bedroom_fan_6
      - switch.master_bedroom_fan_7
      - switch.master_bedroom_fan_8
      - switch.master_bedroom_fan_9
      - switch.master_bedroom_fan_10
      - switch.master_bedroom_fan_11
      - switch.master_bedroom_fan_12




#####################################################################
### Input Select
#####################################################################
input_select:
  master_bedroom_fan_speed:
    name: Master Bedroom Fan Speed
    initial: "Select an option..."
    options:
      - "Select an option..."
      - "Off"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
      - "11"
      - "12"
      - "Random"


#####################################################################
#  Sensor
#####################################################################
sensor:
  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan"
    name: "Master Bedroom Fan"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_1"
    name: "Master Bedroom Fan 1"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_2"
    name: "Master Bedroom Fan 2"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_3"
    name: "Master Bedroom Fan 3"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_4"
    name: "Master Bedroom Fan 4"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_5"
    name: "Master Bedroom Fan 5"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_6"
    name: "Master Bedroom Fan 6"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_7"
    name: "Master Bedroom Fan 7"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_8"
    name: "Master Bedroom Fan 8"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_9"
    name: "Master Bedroom Fan 9"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_10"
    name: "Master Bedroom Fan 10"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_11"
    name: "Master Bedroom Fan 11"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/mbrfanspeed/master_bedroom_fan_12"
    name: "Master Bedroom Fan 12"
    value_template: "{{ value }}"


#####################################################################
### Script
#####################################################################
script:
  mbr_fan_speed_step:
    sequence:
      - service: homeassistant.turn_off
        entity_id: group.mbr_fan_speed

      - delay: 2

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 2

      - delay:
          hours: 3

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 1


#####################################################################
### Automation
#####################################################################
automation:
  ### turn the master bed fan off
  - alias: Master Bedroom Fan Off
    initial_state: 'on'
    trigger:
      - platform: time
        at: '12:00:00'

    condition:
      - condition: state
        entity_id: switch.master_bedroom_fan
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.master_bedroom_fan


  ### master_bedroom_fan_speed_selector
  - alias: Master Bedroom Fan Speed Select
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.master_bedroom_fan_speed

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

    action:
      # Reset fan switch states
      - service: homeassistant.turn_off
        entity_id: group.mbr_fan_speed

      - delay:
          seconds: 1.5

      # Turn on the corresponding fan speed switch
      - service: switch.turn_on
        data_template:
          entity_id: "switch.master_bedroom_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

      # Set the Input Selection to current option
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: "{{ states.trigger.to_state.state }}"


  ### master_bedroom_fan_auto
  - alias: Master Bedroom Fan Auto
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: script.master_bedroom_night_time
        to: 'on'

    condition:
      - condition: state
        entity_id: switch.master_bedroom_fan
        state: 'off'

      - condition: numeric_state
        entity_id: sensor.upstairs_temperature
        above: 71

      - condition: numeric_state
        entity_id: sensor.upstairs_temperature
        below: 81

    action:
      - service: script.turn_on
        entity_id: script.mbr_fan_speed_step


  ### Reset Fan Selection
  - alias: Master Bedroom Fan Reset Selection
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: switch.master_bedroom_fan
        to: 'off'

    action:
      # Reset the Input Select to "Select an option..."
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...


#####################################################################
#  Automation - Saves Switch State to MQTT
#####################################################################
  - alias: Master Bedroom Fan Speed State Save
    initial_state: 'off'
    hide_entity: true
    trigger:
      platform: state
      entity_id: switch.master_bedroom_fan, switch.master_bedroom_fan_1, switch.master_bedroom_fan_2, switch.master_bedroom_fan_3, switch.master_bedroom_fan_4, switch.master_bedroom_fan_5, switch.master_bedroom_fan_6, switch.master_bedroom_fan_7, switch.master_bedroom_fan_8, switch.master_bedroom_fan_9, switch.master_bedroom_fan_10, switch.master_bedroom_fan_11, switch.master_bedroom_fan_12
    action:
      service: mqtt.publish
      data_template:
        topic: "/home/mbrfanspeed/{{ trigger.entity_id.split('.')[1] }}"
        retain: true
        qos: 1
        payload: '{{ trigger.to_state.state }}'


#####################################################################
# Startup event - restores states of fan speed switches
#####################################################################
  - alias: Master Bedroom Fan Speed State Restore
    initial_state: 'off'
    hide_entity: true
    trigger:
      platform: homeassistant
      event: start
    action:
      - delay:
          minutes: 1
      - service_template: >
          {%- if states.sensor.master_bedroom_fan.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_1.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_1
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_2.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_2
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_3.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_3
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_4.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_4
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_5.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_5
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_6.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_6
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_7.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_7
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_8.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_8
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_9.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_9
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_10.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_10
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_11.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}    
        entity_id: switch.master_bedroom_fan_11
      - service_template: >
          {%- if states.sensor.master_bedroom_fan_12.state | lower == "on" -%}
              homeassistant.turn_on
          {%- else  -%}
              homeassistant.turn_off
          {%- endif -%}
        data:
          entity_id: switch.master_bedroom_fan_12
