#####################################################################
#    @package          :     notify
#    @description      :     notifications and alerting components
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'notify'

      hidden: &hidden
        <<: *customize
        hidden: true


#####################################################################
### Notify
#####################################################################
notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pushbullet_api_key

  - platform: ecobee
    name: downstairs_ecobee

  - platform: ecobee
    name: upstairs_ecobee

#####################################################################
### iOS
#####################################################################
ios:
  push:
    categories:
      - name: cancel_away
        identifier: 'cancelaway'
        actions:
          - identifier: 'CANCEL_AWAY'
            title: 'Cancel Away'
            authenticationRequired: false

      ### EXAMPLE ###
#      - name: Alarm
#        identifier: 'alarm'
#        actions:
#          - identifier: 'SOUND_ALARM'
#            title: 'Sound Alarm'
#            activationMode: 'background'
#            authenticationRequired: yes
#            destructive: yes
#            behavior: 'default'
#          - identifier: 'SILENCE_ALARM'
#            title: 'Silence Alarm'
#            activationMode: 'background'
#            authenticationRequired: yes
#            destructive: no
#            behavior: 'textInput'
#            textInputButtonTitle: 'Silencio!'
#            textInputPlaceholder: 'Placeholder'



#####################################################################
###  Automation
#####################################################################
automation:
  - alias: Cancel Away
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: CANCEL_AWAY
    action:
      service: timer.cancel
      entity_id: timer.away_mode
