#####################################################################
#    @package          :     patio
#    @description      :     patio, fountains, and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'patio'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Switch
    ################################################
    switch.back_yard_outlet:
      friendly_name: "Party Lights"
      icon: mdi:white-balance-incandescent

    switch.patio_lights_switch:
      friendly_name: "Patio Lights"
      icon: mdi:white-balance-incandescent


#####################################################################
### Automation
#####################################################################
#automation:

