#####################################################################
#    @package          :     patio
#    @description      :     patio, fountains, and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'patio'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Switch
    ################################################
    switch.back_yard_outlet:
      friendly_name: "Back Christmas Lights"
      icon: mdi:snowman

    switch.front_yard_outlet:
      friendly_name: "Front Christmas Lights"
      icon: mdi:stocking


    switch.patio_lights_switch:
      friendly_name: "Patio Lights"
      icon: mdi:white-balance-incandescent


#####################################################################
### Automation
#####################################################################
automation:
### Turn off the Christmas Lights - Weekdays
  - alias: Christmas Lights Off Weekdays
    initial_state: 'on'
    trigger:
      platform: time
      at: '00:00:00'

    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri

      - condition: state
        entity_id: switch.back_yard_outlet
        state: 'on'

    action:
  # outdoor Christmas lights
      - service: homeassistant.turn_off
        entity_id: group.christmas_lights


### Turn off the Christmas Lights - Weekends
  - alias: Christmas Lights Off Weekends
    initial_state: 'on'
    trigger:
      platform: time
      at: '01:30:00'

    condition:
      - condition: time
        weekday:
          - sat
          - sun

      - condition: state
        entity_id: switch.back_yard_outlet
        state: 'on'

    action:
      - service: homeassistant.turn_off
        entity_id: group.christmas_lights
