#####################################################################
#    @package          :     Rachio
#    @description      :     Rachio irrigation setup
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'rachio'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Switch
    ################################################
    switch.rubino_in_standby_mode:
      friendly_name: "Rachio Standby"

    switch.north_sprinklers_z1:
      friendly_name: "North Sprinklers"

    switch.northwest_sprinklers_z2:
      friendly_name: "Northwest Sprinklers"

    switch.northeast_sprinklers_z3:
      friendly_name: "Northeast Sprinklers"

    switch.east_sprinklers_z5:
      friendly_name: "East Sprinklers"

    switch.southeast_sprinklers_z6:
      friendly_name: "Southeast Sprinklers"

    switch.southwest_sprinklers_z7:
      friendly_name: "Southwest Sprinklers"

    switch.drip_and_citrus_trees_z4:
      friendly_name: "Drip Lines"


    ################################################
    ## Sensors
    ################################################
    binary_sensor.rubino_online:
      friendly_name: "Rachio Station"

    sensor.rachio_status:
      friendly_name: "Rachio Status"
      entity_picture: /local/rachio.png


####################################################################
## Rachio component config
####################################################################
rachio:
  api_key: !secret rachio_token


####################################################################
## iFrame config
####################################################################
#panel_iframe:
#  rachio:
#    title: Rachio
#    url: "https://app.rach.io"
#    icon: mdi:water-pump


####################################################################
## Switch
####################################################################
switch:
  - platform: rachio

####################################################################
## Binary Sensor
####################################################################
binary_sensor:
  - platform: rachio

####################################################################
## Sensor
####################################################################
sensor:
  - platform: template
    sensors:
      rachio_status:
        friendly_name: "Rachio Status"
        value_template: >-
          {% if is_state('binary_sensor.rubino_online', 'on') %}
            Online
          {% else %}
            Offline
          {% endif %}
        entity_id: sensor.time