#####################################################################
#    @package          :     Ring Doorbell
#    @description      :     Ring Doorbell Config
#####################################################################
ring:
  username: !secret ring_username
  password: !secret ring_password


#####################################################################
### Binary Sensor
#####################################################################
binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion


#####################################################################
### Sensor
#####################################################################
sensor:
  - platform: ring
    monitored_conditions:
      - last_ding
      - last_motion
      - wifi_signal_strength

