#####################################################################
#    @package          :     scenes
#    @description      :     scenes and scenarios for lighting, etc.
#####################################################################
homeassistant:
  customize_domain:
    scene:
      icon: mdi:play-circle

  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'scenes'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Scene
    ################################################
    scene.morning:
      icon: mdi:weather-sunset-up

    scene.evening:
      friendly_name: "Evening"
      icon: mdi:play-circle

    scene.cloudy:
      <<: *hidden
      friendly_name: "Cloudy"
      icon: mdi:play-circle

    scene.movie_time:
      friendly_name: "Movie Time"
      icon: mdi:play-circle

    scene.movie_paused:
      <<: *hidden
      icon: mdi:play-circle

    scene.movie_ended:
      <<: *hidden
      icon: mdi:play-circle


#####################################################################
### Scene
#####################################################################
scene:
  - name: Morning
    entities:
      light.foyer_lights_level:
        state: on
        brightness: 255
        transition: 5

  # turn on the master bedroom chandelier
      light.master_bedroom_chandelier_level:
        state: on
        brightness: 50

  # turn on the accent_lights
      group.accent_lights: on

  # turn on the living room lamp
      light.living_room_lamp:
        state: on
        brightness: 254
        transition: 600

  # turn on the hue entry_lights
      light.entryway:
        state: on
        brightness: 140
        transition: 600

  # turn on the hue living_room_ceiling lights
      light.lr_ceiling:
        state: on
        brightness: 140
        transition: 900

  # turn on the kitchen lights
      light.kitchen_lights_level:
        state: on
        brightness: 170


  - name: Bright
    entities:
      light.foyer_lights_level:
        state: on
        brightness: 255
        transition: 5

      group.entry_lights:
        state: on
        brightness: 255
        transition: 5

      light.living_room_lamp:
        state: on
        brightness: 255
        transition: 5

      light.lr_ceiling:
        state: on
        brightness: 255
        transition: 5

      light.kitchen_lights_level:
        state: on
        brightness: 255


  - name: Evening
    entities:
      light.foyer_lights_level:
        state: on
        brightness: 255
        transition: 5

      light.kitchen_entry:
        state: on
        brightness: 200
        transition: 30

      light.south_entry:
        state: on
        brightness: 160
        transition: 10

      light.center_entry:
        state: on
        brightness: 50
        transition: 10

      light.living_room_lamp:
        state: on
        brightness: 255
        transition: 10

      light.lr_ceiling:
        state: off
        transition: 10


  - name: Dim
    entities:
      light.foyer_lights_level:
        state: on
        brightness: 150
        transition: 5

      light.kitchen_entry:
        state: on
        brightness: 150
        transition: 30

      light.south_entry:
        state: on
        brightness: 75
        transition: 10

      light.center_entry:
        state: on
        brightness: 50
        transition: 10

      light.living_room_lamp:
        state: on
        brightness: 100
        transition: 15

      light.lr_ceiling:
        state: on
        brightness: 50
        transition: 20


  - name: Cloudy
    entities:
      light.foyer_lights_level:
        state: on
        brightness: 255
        transition: 5

      light.kitchen_entry:
        state: on
        brightness: 90
        transition: 10

      light.south_entry:
        state: on
        brightness: 90
        transition: 10

      light.center_entry:
        state: on
        brightness: 90
        transition: 10

      light.living_room_lamp:
        state: on
        brightness: 254
        transition: 30

      light.lr_ceiling:
        state: on
        brightness: 75
        transition: 10


#####################################################################
### Automation
#####################################################################
automation:
  ### Weekday Wakeup
  - alias: Morning Sequence
    initial_state: 'on'
    trigger:
      - platform: time
        at: '06:10:00'

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'

      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'

    action:
      - service: script.morning_sequence


  ### Bedtime Timer Finish
  - alias: Bedtime Timer Finish
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bedtime

    action:
      - service: script.bedtime


  ### Bedtime Timer Reset
  - alias: Bedtime Timer Reset
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: binary_sensor.front_entry_fibaro_multisensor_sensor
        to: 'on'

    condition:
      - condition: template
        value_template: "{{ states('timer.bedtime') != 'idle'}}"

    action:
      - service: timer.cancel
        entity_id: timer.bedtime

      - delay:
          seconds: 30
    ### reset the timer after short delay
      - service: timer.start
        entity_id: timer.bedtime
