#####################################################################
#    @package          :     scenes
#    @description      :     scenes and scenarios for lighting, etc.
#####################################################################
homeassistant:
  customize_domain:
    scene:
      icon: mdi:play-circle

  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'scenes'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true


    ################################################
    ## Script
    ################################################
    script.morning_sequence:
      <<: *hidden

    script.away:
      <<: *hidden

    script.company_mode:
      friendly_name: "Company Mode"
      icon: mdi:play-circle

    script.bedtime:
      friendly_name: "Bedtime"
      icon: mdi:hotel

    script.shutdown_lights:
      friendly_name: "Shutdown"
      icon: mdi:play-circle

    script.hue_lr_dimmed:
      friendly_name: "Dimmed"
      icon: mdi:play-circle

    script.hue_lr_nightlight:
      friendly_name: "Night Mode"
      icon: mdi:play-circle

    script.hue_lr_bright:
      friendly_name: "Bright"
      icon: mdi:play-circle

    script.hue_lr_christmas:
      friendly_name: "Christmas Time"
      icon: mdi:stocking

    script.hue_lr_movie:
      friendly_name: "Movie"
      icon: mdi:play-circle

    script.hue_lr_sunrise:
      friendly_name: "Sunrise"
      icon: mdi:play-circle

    script.hue_lr_sunset:
      friendly_name: "Sunset"
      icon: mdi:play-circle

    script.hue_lr_minty:
      friendly_name: "Minty"
      icon: mdi:play-circle

    script.hue_lr_daybreak:
      friendly_name: "Daybreak"
      icon: mdi:play-circle

    script.nap_time:
      friendly_name: "Nap Time"
      icon: mdi:play-circle

    script.hue_mbath_morning:
      friendly_name: "Bathroom Morning"
      icon: mdi:play-circle


    ################################################
    ## Scene
    ################################################
    scene.morning:
      icon: mdi:weather-sunset-up

    scene.evening:
      friendly_name: "Evening"
      icon: mdi:play-circle

    scene.cloudy:
      <<: *hidden
      friendly_name: "Cloudy"
      icon: mdi:play-circle

    scene.movie_time:
      friendly_name: "Movie Time"
      icon: mdi:play-circle

    scene.movie_paused:
      <<: *hidden
      icon: mdi:play-circle

    scene.movie_ended:
      <<: *hidden
      icon: mdi:play-circle


#####################################################################
### Group
#####################################################################
group:
  Operational Modes:
    control: hidden
    entities:
      - input_boolean.visitor_mode
      - input_boolean.holiday
      - script.company_mode

  Lighting Scenes:
    control: hidden
    entities:
      - scene.morning
      - script.nap_time
      - input_boolean.dinner_time
      - script.bedtime
      - scene.movie_time
      - scene.dim
      - scene.cloudy
      - scene.evening
      - scene.bright
      - script.shutdown_lights

  Hue Scenes:
    control: hidden
    entities:
      - script.hue_lr_dimmed
      - script.hue_lr_nightlight
      - script.hue_lr_bright
      - script.hue_lr_christmas
      - script.hue_lr_movie
      - script.hue_lr_sunrise
      - script.hue_lr_sunset
      - script.hue_lr_minty
      - script.hue_lr_daybreak


  Automation Override:
    control: hidden
    entities:
      - automation.away_mode_on
      - automation.south_door_unlock_on_arrival
      - automation.accent_lights_auto_off
      - automation.living_room_off_morning
      - automation.living_room_on_cloudy
      - automation.living_room_bright_morning


#####################################################################
### Scene
#####################################################################
scene:
  - name: Morning
    entities:
      light.foyer_lights_level:
        state: on
        brightness: 255
        transition: 5

  # turn on the master bedroom chandelier
      light.master_bedroom_chandelier_level:
        state: on
        brightness: 50

  # turn on the accent_lights
      group.accent_lights: on

  # turn on the living room lamp
      light.living_room_lamp:
        state: on
        brightness: 254
        transition: 600

  # turn on the hue entry_lights
      light.entryway:
        state: on
        brightness: 140
        transition: 600

  # turn on the hue living_room_ceiling lights
      light.lr_ceiling:
        state: on
        brightness: 140
        transition: 900

  # turn on the kitchen lights
      light.kitchen_lights_level:
        state: on
        brightness: 170


#####################################################################
### Script
#####################################################################
script:
  ### Morning Wakeup Sequence
  morning_sequence:
    sequence:
    - service: light.turn_on
      data:
        entity_id: light.foyer_lights_level
        brightness: 155
        transition: 30

    - service: hue.hue_activate_scene
      data:
        group_name: "Master Bathroom"
        scene_name: "Morning"

#    - service: light.turn_on
#      data:
#        entity_id: light.master_bedroom_chandelier_level
#        brightness: 40
#        transition: 30

    - service: homeassistant.turn_on
      entity_id: group.accent_lights

    - delay:
        minutes: 7

#    - service: light.turn_on
#      data:
#        entity_id: light.living_room_lamp
#        brightness: 255
#        transition: 30

    - service: hue.hue_activate_scene
      data:
        group_name: "Living Room"
        scene_name: "Sunrise"

    - service: light.turn_on
      data:
        entity_id: light.entryway
        brightness: 140
        transition: 30

    - delay:
        minutes: 7

    - service: light.turn_on
      data:
        entity_id: light.kitchen_lights_level
        brightness: 170


  ### Nap Time Sequence
  nap_time:
    sequence:
    - service: light.turn_off
      entity_id: light.living_room
      data:
        transition: 5

    - service: light.turn_off
      entity_id: light.entryway
      data:
        transition: 5

    - delay: '00:00:05'

    - service: light.turn_on
      entity_id: light.living_room_lamp
      data:
        brightness: 50
        transition: 10

    - service: light.turn_on
      entity_id: light.kitchen_entry
      data:
        brightness: 80

#      - service: hue.hue_activate_scene
#        data:
#          group_name: "Living Room"
#          scene_name: "Nap Time"
#
#      - service: hue.hue_activate_scene
#        data:
#          group_name: "Entryway"
#          scene_name: "Nightlight"


  ### Bedtime Mode Sequence
  bedtime:
    sequence:
    # lock up
    - service: lock.lock

#    - service: light.turn_on
#      data:
#        entity_id: light.gateway_light_7811dcb7da52
#        brightness: 50
#        hs_color: [180,100]

    # turn off the "outdoor speakers and downstairs wipe warmer"
    - service: switch.turn_off
      entity_id:
        - switch.outdoor_speakers
        - switch.switch_three

    - service: switch.turn_off
      entity_id: switch.living_room_fan

    - delay:
        minutes: 3

    - service: homeassistant.turn_off
      entity_id: group.interior_lights

    - delay:
        minutes: 2

    - service: light.turn_off
      entity_id: light.under_bed_lights

    - delay:
        seconds: 10

## hit the flux led strip light again ... flaky behavior
    - service: light.turn_off
      entity_id: light.under_bed_lights


  ### Company Mode Sequence
  company_mode:
    sequence:
    - service: switch.turn_on
      entity_id: 
        - switch.outdoor_speakers
        - switch.game_room_lights_switch
        - switch.pool_light_switch

    - service: scene.turn_on
      entity_id: scene.bright

    - service: lock.unlock

    - service: light.turn_on
      data:
        entity_id: light.kitchen_lights_level
        brightness: 130

    - service: light.turn_on
      data:
        entity_id: light.dining_room_chandelier_level
        brightness: 130


#####################################################################
### Script - Hue Scenes
#####################################################################
  hue_lr_dimmed:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Dimmed"

  hue_lr_nightlight:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Nightlight"

  hue_lr_bright:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Bright"

  hue_lr_christmas:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Christmas"

  hue_lr_movie:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Movie"

  hue_lr_sunrise:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Sunrise"

  hue_lr_sunset:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Sunset"

  hue_lr_minty:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Minty"

  hue_lr_daybreak:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Daybreak"

  hue_mbath_morning:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Master Bathroom"
          scene_name: "Morning"


#####################################################################
### Automation
#####################################################################
automation:
  ### Weekday Wakeup
  - alias: Morning Sequence
    initial_state: 'on'
    trigger:
      - platform: time
        at: '06:10:00'

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'

      - condition: state
        entity_id: input_boolean.holiday
        state: 'off'

      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'

    action:
      - service: script.morning_sequence


  ### Bedtime Timer Finish
  - alias: Bedtime Timer Finish
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bedtime

    action:
      - service: script.bedtime

  ### Bedtime Timer Reset
  - alias: Bedtime Timer Reset
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: binary_sensor.front_entry_fibaro_multisensor_sensor
        to: 'on'

    condition:
      - condition: template
        value_template: "{{ states('timer.bedtime') != 'idle'}}"

    action:
      - service: timer.cancel
        entity_id: timer.bedtime

      - delay:
          seconds: 30
    ### reset the timer after short delay
      - service: timer.start
        entity_id: timer.bedtime
