#####################################################################
#    @package          :     security_sensors
#    @description      :     security_sensors and associated automations, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'security_sensors'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true


    ################################################
    ## Sensor
    ################################################
    sensor.front_entry_motion:
      <<: *contained
      friendly_name: "Front Entry Motion"
      icon: mdi:run

    sensor.front_entry_fibaro_multisensor_luminance:
      <<: *contained
      friendly_name: "Front Entry Light Sensor"
      icon: mdi:white-balance-sunny

    sensor.front_door_tamper:
      <<: *contained
      friendly_name: "Front Door Tamper"
      #icon: mdi:home-outline

    sensor.south_door_tamper:
      <<: *contained
      friendly_name: "South Door Tamper"
      #icon: mdi:home-outline

    sensor.kitchen_door_tamper:
      <<: *contained
      friendly_name: "Kitchen Door Tamper"
      #icon: mdi:home-outline

    sensor.beach_door_tamper:
      <<: *contained
      friendly_name: "Beach Door Tamper"
      #icon: mdi:home-outline

    sensor.nursery_ptz_motion_detected:
      <<: *contained
      friendly_name: "Nursery PTZ Motion"
      icon: mdi:run

    sensor.nw_ptz_motion_detected:
      <<: *contained
      friendly_name: "NW PTZ Motion"
      icon: mdi:run

    sensor.nursery_ptz_preset:
      <<: *contained
      friendly_name: "Nursery PTZ Preset"
      icon: mdi:arrow-expand-all

    sensor.nw_ptz_preset:
      <<: *contained
      friendly_name: "NW PTZ Preset"
      icon: mdi:arrow-expand-all

    sensor.nursery_ptz_sd_used:
      <<: *contained
      friendly_name: "Nursery PTZ SD Card"
      icon: mdi:sd

    sensor.nw_ptz_sd_used:
      <<: *contained
      friendly_name: "NW PTZ SD Card"
      icon: mdi:sd

#    sensor.crime:
#      <<: *contained
#      icon: mdi:bomb

    sensor.entryway_occupancy:
      <<: *contained

    sensor.living_room_occupancy:
      <<: *contained

    sensor.office_occupancy:
      <<: *contained

    sensor.upstairs_occupancy:
      <<: *contained

    sensor.nursery_occupancy:
      <<: *contained

    sensor.guest_room_occupancy:
      <<: *contained

    sensor.downstairs_ac_leak_detector:
      <<: *contained
      friendly_name: "Downstairs AC Leak Detector"

    sensor.everspring_st812_flood_detector_flood:
      <<: *hidden

    sensor.everspring_st812_flood_detector_alarm_level:
      ignored: true

    sensor.everspring_st812_flood_detector_alarm_type:
      ignored: true


    ################################################
    ## Door State Icons
    ################################################
    sensor.front_door_state:
      <<: *contained

    sensor.kitchen_door_state:
      <<: *contained

    sensor.south_door_state:
      <<: *contained

    sensor.beach_door_state:
      <<: *contained




#####################################################################
### Group
#####################################################################
group:
  Sensors:
    entities:
      - binary_sensor.living_room_occupancy
      - binary_sensor.entryway_occupancy
      - binary_sensor.office_occupancy
      - binary_sensor.upstairs_occupancy
      - binary_sensor.nursery_occupancy
      - binary_sensor.guest_room_occupancy
      - sensor.kegerator_door_state
      - sensor.front_entry_motion
      - sensor.nursery_ptz_motion_detected
      - sensor.nw_ptz_motion_detected
      - sensor.front_entry_fibaro_multisensor_luminance
      - sensor.downstairs_ac_leak_detector
#      - sensor.crime

  Door Sensors:
    entities:
      - sensor.front_door_state
      - sensor.south_door_state
      - sensor.kitchen_door_state
      - sensor.beach_door_state

  Door Alarm Points:
    entities:
      - sensor.front_door_tamper
      - sensor.south_door_tamper
      - sensor.kitchen_door_tamper
      - sensor.beach_door_tamper


#####################################################################
### Sensor
#####################################################################
sensor:
### Amcrest Camera Sensors
  - platform: amcrest

### Fibaro Motion Detector status
  - platform: template
    sensors:
      front_entry_motion:
        value_template: >-
          {% set state = states('sensor.front_entry_fibaro_multisensor_burglar') %}
          {% if state == '0' %}
            Clear
          {% elif state == '8' %}
            Detected
          {% elif state == '3' %}
            Tamper
          {% elif state == '254' %}
            Sleeping
          {% else %}
            {{ state|title }}
          {% endif %}


### Front Door Status
  - platform: template
    sensors:
      front_door_state:
        value_template: >-
          {% set state = states('sensor.front_door_contact_access_control') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Front Door"
        icon_template: >-
          {% set state = states('sensor.front_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### Front Door Tamper
  - platform: template
    sensors:
      front_door_tamper:
        value_template: >-
          {% set state = states('sensor.front_door_contact_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


### South Door Status
  - platform: template
    sensors:
      south_door_state:
        value_template: >-
          {% set state = states('sensor.south_door_contact_access_control') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "South Door"
        icon_template: >-
          {% set state = states('sensor.south_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### South Door Tamper
  - platform: template
    sensors:
      south_door_tamper:
        value_template: >-
          {% set state = states('sensor.south_door_contact_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


### Kitchen Door Status
  - platform: template
    sensors:
      kitchen_door_state:
        value_template: >-
          {% set state = states('sensor.kitchen_door_contact_access_control') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Kitchen Door"
        icon_template: >-
          {% set state = states('sensor.kitchen_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### Kitchen Door Tamper
  - platform: template
    sensors:
      kitchen_door_tamper:
        value_template: >-
          {% set state = states('sensor.kitchen_door_contact_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


### Beach Door Status
  - platform: template
    sensors:
      beach_door_state:
        value_template: >-
          {% set state = states('sensor.beach_door_contact_access_control') %}
          {% if state == '22' %}
            Open
          {% elif state == '23' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Beach Door"
        icon_template: >-
          {% set state = states('sensor.beach_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### Beach Door Tamper
  - platform: template
    sensors:
      beach_door_tamper:
        value_template: >-
          {% set state = states('sensor.beach_door_contact_burglar') %}
          {% if state == '0' %}
            OK
          {% elif state == '3' %}
            Tamper
          {% else %}
            {{ state }}
          {% endif %}


### Kegerator Door Status
  - platform: template
    sensors:
      kegerator_door_state:
        value_template: >-
          {% set state = states('binary_sensor.door_window_sensor_158d0002332a6b') %}
          {% if state == 'on' %}
            Open
          {% elif state == 'off' %}
            Closed
          {% else %}
            {{ state|title }}
          {% endif %}
        friendly_name: "Kegerator Door"
        icon_template: >-
          {% set state = states('sensor.kegerator_door_state')|default('unknown') %}
          {% if state == 'unknown' %}
            mdi:door
          {% else %}
            {% if state == 'Open' %}
              mdi:door-open
            {% else %}
              mdi:door-closed
            {% endif %}
          {% endif %}


### Downstairs HVAC Leak Detector
  - platform: template
    sensors:
      downstairs_ac_leak_detector:
        value_template: >-
          {% set state = states('sensor.everspring_st812_flood_detector_flood') %}
          {% if state == '0' %}
            OK
          {% elif state == '255' %}
            Leak Detected!
          {% else %}
            {{ state|title }}
          {% endif %}


### Crime Reports
#  - platform: crimereports
#    name: Crime
#    radius: 4000
#    exclude:
#    - Disorder
#    - Drugs
#    - Other
#    - Pedestrian Stop
#    - Proactive Policing
#    - Quality of Life
#    - Traffic
#    - Vehicle Recovery
#    - Vehicle Stop


#####################################################################
### Automation
#####################################################################
automation:
  ### AC Leak Detector Alarm
  - alias: Downstairs AC Leak Detector Alarm
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.downstairs_ac_leak_detector
        to: 'Leak Detected!'

    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs
          operation_mode: 'off'

      - service: notify.notify
        data:
          title: "Leak Detected"
          message: "HVAC overflow detected - AC turned off!"


  ### Kegerator Door Alarm
  - alias: Kegerator Door Held Open
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.kegerator_door_state
        to: 'Open'
        for:
          minutes: 1

    action:
#      - service: climate.set_operation_mode
#        data:
#          entity_id: climate.downstairs
#          operation_mode: 'off'

      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.kitchen
          message: "Attention! Please close the beer fridge door."

      - service: notify.notify
        data:
          title: "Kegerator"
          message: "The Kegerator door is held open!"


