#####################################################################
#    @package          :     timers
#    @description      :     all timers and countdown values
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'timers'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true


    ################################################
    ## Script
    ################################################
    script.start_away_timer:
      <<: *contained
      icon: mdi:timer

    script.pause_away_timer:
      <<: *contained
      icon: mdi:timer

    script.cancel_away_timer:
      <<: *contained
      icon: mdi:timer

    script.finish_away_timer:
      <<: *contained
      icon: mdi:timer


    script.start_bedtime_timer:
      <<: *contained
      icon: mdi:timer

    script.pause_bedtime_timer:
      <<: *contained
      icon: mdi:timer

    script.cancel_bedtime_timer:
      <<: *contained
      icon: mdi:timer

    script.finish_bedtime_timer:
      <<: *contained
      icon: mdi:timer


  ################################################
  ## Customize Global
  ################################################
  customize_glob:
    "timer.*":
      <<: *contained
      icon: mdi:timer


#####################################################################
###  Timer
#####################################################################
timer:
  away_mode:
    duration: '00:15:00'

  bedtime:
    duration: '00:10:00'


#####################################################################
###  Script
#####################################################################
script:
  start_away_timer:
    alias: "Start Away"
    sequence:
      - service: timer.start
        entity_id: timer.away_mode

  pause_away_timer:
    alias: "Pause Away"
    sequence:
      - service: timer.pause
        entity_id: timer.away_mode

  cancel_away_timer:
    alias: "Cancel Away"
    sequence:
      - service: timer.cancel
        entity_id: timer.away_mode

  finish_away_timer:
    alias: "Finish Away"
    sequence:
      - service: timer.finish
        entity_id: timer.away_mode


  ### Bedtime Timers
  start_bedtime_timer:
    alias: "Start Bedtime"
    sequence:
      - service: timer.start
        entity_id: timer.bedtime

  pause_bedtime_timer:
    alias: "Pause Bedtime"
    sequence:
      - service: timer.pause
        entity_id: timer.bedtime

  cancel_bedtime_timer:
    alias: "Cancel Bedtime"
    sequence:
      - service: timer.cancel
        entity_id: timer.bedtime

  finish_bedtime_timer:
    alias: "Finish Bedtime"
    sequence:
      - service: timer.finish
        entity_id: timer.bedtime
