############################################################################
#    @package          :     views
#    @description      :     views visible on UI
############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'views'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## UI HOME VIEW
    ################################################
#    group.default_view:
##      icon: mdi:account-location
#
#
#    ################################################
#    ## UI SECURITY VIEW
#    ################################################
#    group.security:
##      icon: mdi:security-home
#
#
#    ################################################
#    ## UI CAMERAS VIEW
#    ################################################
#    group.cameras:
##      icon: mdi:cctv
#
#
#    ################################################
#    ## UI DOWNSTAIRS VIEW
#    ################################################
#    group.downstairs:
##      icon: mdi:arrow-down-bold-circle-outline
#
#
#    ################################################
#    ## UI UPSTAIRS VIEW
#    ################################################
#    group.upstairs:
##      icon: mdi:arrow-up-bold-circle-outline
#
#
#    ################################################
#    ## UI CLIMATE VIEW
#    ################################################
#    group.climate:
##      icon: mdi:air-conditioner
#
#
#    ################################################
#    ## UI SCENES VIEW
#    ################################################
#    group.scenes:
##      icon: mdi:creation
#
#
#    ################################################
#    ## UI EXTERIOR VIEW
#    ################################################
#    group.exterior:
##      icon: mdi:tree
#
#
#    ################################################
#    ## UI WEATHER VIEW
#    ################################################
#    group.weather:
##      icon: mdi:weather-sunny
#
#
#    ################################################
#    ## UI MEDIA VIEW
#    ################################################
#    group.media:
##      icon: mdi:theater
#
#
#    ################################################
#    ## UI SYSTEM VIEW
#    ################################################
#    group.system:
##      icon: mdi:server
#
#
#    ################################################
#    ## UI TEST LAB VIEW
#    ################################################
#    group.lab:
##      icon: mdi:test-tube
#
#
#####################################################################
### Group (comment out default_view and enable home for all entities
#####################################################################
group:
  home:
#  default_view:
#    name: Home
#    view: yes
#    entities:
#      - group.travel_megs
#      - group.travel_rick
#      - group.device_status
#      - group.traffic_report
#
#  security:
#    name: Security
#    view: yes
#    entities:
#      - group.door_locks
#      - group.sensors
#      - group.door_sensors
#
#  cameras:
#    name: Cameras
#    view: yes
#    entities:
#      - group.camera_front_porch
#      - group.camera_north_gate
#      - group.camera_nw_ptz
#      - group.camera_nursery_ptz
#      - group.camera_ring_doorbell
#
#  downstairs:
#    name: Downstairs
#    view: yes
#    entities:
#      - group.living_room_fan
#      - group.living_room_lights
#      - group.wine_room_lights
#      - group.accent_lights
#      - group.entry_lights
#      - group.kitchen
#      - group.dining_room
#      - group.game_room
#      - group.office
#      - group.downstairs_bath
#      - group.downstairs_outlets
#
#  upstairs:
#    name: Upstairs
#    view: yes
#    entities:
#      - group.nursery
#      - group.master_bedroom
#      - group.master_bedroom_fan
#      - group.bedframe_lights
#      - group.master_bath
#      - media_player.kodi_bedroom
#
#  climate:
#    name: Climate
#    view: yes
#    entities:
#      - group.downstairs_climate
#      - group.downstairs_ecobee
#      - group.upstairs_climate
#      - group.upstairs_ecobee
#
#  scenes:
#    name: Scenes
#    view: yes
#    entities:
#      - group.lighting_scenes
#      - group.operational_modes
#      - group.automation_override
#      - group.hue_scenes
#
#  exterior:
#    name: Exterior
#    view: yes
#    entities:
#      - group.porch
#      - group.yard
#      - group.pool
#      - group.irrigation
##      - group.sprinklers
##      - group.driplines
#
#  weather:
#    name: Weather
#    view: yes
#    entities:
#      - sun.sun
#      - sensor.moon
#      - group.weather_summary
#      - group.weather_details
#      - group.3_day_forecast
#      #- group.river_info
#
#  media:
#    name: Media
#    view: yes
#    entities:
#      - group.living_room_tv
#      - group.directv
#      - group.onkyo_amp
#      - media_player.kodi_living_room
#      - media_player.firetv
#      - media_player.apple_tv
#
#  system:
#    name: System
#    view: yes
#    entities:
#      - group.ha_status
#      - group.speedtest
#      - group.downloads
#
#  lab:
#    name: Lab
#    view: yes
#    entities:
#      - group.test_triggers
#      - group.test_conditions
