############################################################################
#    @package          :     views
#    @description      :     views visible on UI
############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'views'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## UI HOME VIEW
    ################################################
#    group.default_view:
#      <<: *contained
##      icon: mdi:account-location
#
#    group.travel_megs:
#      <<: *contained
##      order: 1
#
#    group.travel_rick:
#      <<: *contained
##      order: 2
#
#    group.device_status:
#      <<: *contained
##      order: 3
#
#    ################################################
#    ## UI SECURITY VIEW
#    ################################################
#    group.security:
#      <<: *contained
##      icon: mdi:security-home
#
#    group.door_locks:
#      <<: *contained
##      order: 1
#
#    group.sensors:
#      <<: *contained
##      order: 2
#
#    group.door_sensors:
#      <<: *contained
#      #order: 3
#
#    group.door_alarm_points:
#      <<: *contained
##      order: 4
#
#    ################################################
#    ## UI CAMERAS VIEW
#    ################################################
#    group.cameras:
#      <<: *contained
##      icon: mdi:cctv
#
#    group.camera_status:
#      <<: *contained
#
#    group.camera_front_door:
#      <<: *contained
##      order: 1
#
#    group.camera_north_gate:
#      <<: *contained
##      order: 2
#
#    group.camera_nw_ptz:
#      <<: *contained
##      order: 3
#
#    group.camera_nursery_ptz:
#      <<: *contained
##      order: 4
#
#    group.traffic_report:
#      <<: *contained
#
#    ################################################
#    ## UI DOWNSTAIRS VIEW
#    ################################################
#    group.downstairs:
#      <<: *contained
##      icon: mdi:arrow-down-bold-circle-outline
#
#    group.living_room_lights:
#      <<: *contained
##      order: 1
#
#    group.entry_lights:
#      <<: *contained
##      order: 2
#
#    group.living_room_fan:
#      <<: *contained
##      order: 3
#
#    group.accent_lights:
##      order: 4
#
#    group.kitchen:
#      <<: *contained
##      order: 5
#
#    group.dining_room:
#      <<: *contained
##      order: 6
#
#    group.wine_room_lights:
##      order: 7
#
#    group.billiards_room:
#      <<: *contained
##      order: 8
#
#    group.downstairs_bath:
#      <<: *contained
##      order: 9
#
#    group.office:
#      <<: *contained
##      order: 10
#
#    group.downstairs_outlets:
#      <<: *contained
##      order: 11
#
#
#    ################################################
#    ## UI UPSTAIRS VIEW
#    ################################################
#    group.upstairs:
#      <<: *contained
##      icon: mdi:arrow-up-bold-circle-outline
#
#    group.master_bedroom:
#      <<: *contained
##      order: 1
#
#    group.master_bedroom_fan:
#      <<: *contained
##      order: 2
#
#    group.bedframe_lights:
#      <<: *contained
##      order: 3
#
#    group.master_bath:
#      <<: *contained
##      order: 2
#
#    media_player.kodi_bedroom:
#      <<: *contained
##      order: 5
#
#    group.nursery:
#      <<: *contained
##      order: 6
#
##    group.upstairs_outlets:
##      <<: *contained
##      order: 7
#
#
#    ################################################
#    ## UI CLIMATE VIEW
#    ################################################
#    group.climate:
#      <<: *contained
##      icon: mdi:air-conditioner
#
#    group.downstairs_climate:
#      <<: *contained
##      order: 1
#
#    group.downstairs_ecobee:
#      <<: *contained
##      order: 2
#
#    group.upstairs_climate:
#      <<: *contained
##      order: 3
#
#    group.upstairs_ecobee:
#      <<: *contained
##      order: 4
#
#
#    ################################################
#    ## UI SCENES VIEW
#    ################################################
#    group.scenes:
#      <<: *contained
##      icon: mdi:creation
#
#    group.operational_modes:
#      <<: *contained
##      order: 1
#
#    group.lighting_scenes:
#      <<: *contained
##      order: 2
#
#    group.hue_scenes:
#      <<: *contained
##      order: 3
#
#    group.automation_override:
#      <<: *contained
##      order: 4
#
#
#    ################################################
#    ## UI EXTERIOR VIEW
#    ################################################
#    group.exterior:
#      <<: *contained
##      icon: mdi:tree
#
#    group.yard:
#      <<: *exposed
#      
##      order: 1
#
#    group.irrigation:
#      <<: *contained
##      order: 2
#
#
#    ################################################
#    ## UI WEATHER VIEW
#    ################################################
#    group.weather:
#      <<: *contained
##      icon: mdi:weather-sunny
#
#    group.weather_summary:
#      <<: *contained
##      order: 1
#
#    group.weather_details:
#      <<: *contained
##      order: 2
#
#    group.precipitation:
#      <<: *contained
##      order: 3
#
#    group.3_day_forecast:
#      <<: *contained
#
#
#    ################################################
#    ## UI MEDIA VIEW
#    ################################################
#    group.media:
#      <<: *contained
##      icon: mdi:theater
#
#    group.living_room_tv:
#      <<: *contained
##      order: 1
#
#    group.directv:
#      <<: *contained
##      order: 2
#
#    group.onkyo_amp:
#      <<: *contained
##      order: 3
#
#
#    ################################################
#    ## UI SYSTEM VIEW
#    ################################################
#    group.system:
#      <<: *contained
##      icon: mdi:server
#
#    group.ha_status:
#      <<: *contained
##      order: 1
#
#    group.downloads:
#      <<: *contained
#
#    group.speedtest:
#      <<: *contained
#
#
#    ################################################
#    ## UI TEST LAB VIEW
#    ################################################
#    group.lab:
#      <<: *contained
##      icon: mdi:test-tube
#
#    group.test_triggers:
#      <<: *contained
#
#    group.test_conditions:
#      <<: *contained
#
#
#  ################################################
#  ## Customize Global
#  ################################################
  customize_glob:
    "group.all_*":
      <<: *contained


#####################################################################
### Group (comment out default_view and enable home for all entities
#####################################################################
group:
  home:
#  default_view:
#    name: Home
#    view: yes
#    entities:
#      - group.travel_megs
#      - group.travel_rick
#      - group.device_status
#      - group.traffic_report
#
#  security:
#    name: Security
#    view: yes
#    entities:
#      - group.door_locks
#      - group.sensors
#      - group.door_sensors
#
#  cameras:
#    name: Cameras
#    view: yes
#    entities:
#      - group.camera_front_porch
#      - group.camera_north_gate
#      - group.camera_nw_ptz
#      - group.camera_nursery_ptz
#      - group.camera_ring_doorbell
#
#  downstairs:
#    name: Downstairs
#    view: yes
#    entities:
#      - group.living_room_fan
#      - group.living_room_lights
#      - group.wine_room_lights
#      - group.accent_lights
#      - group.entry_lights
#      - group.kitchen
#      - group.dining_room
#      - group.billiards_room
#      - group.office
#      - group.downstairs_bath
#      - group.downstairs_outlets
#
#  upstairs:
#    name: Upstairs
#    view: yes
#    entities:
#      - group.nursery
#      - group.master_bedroom
#      - group.master_bedroom_fan
#      - group.bedframe_lights
#      - group.master_bath
#      - media_player.kodi_bedroom
#
#  climate:
#    name: Climate
#    view: yes
#    entities:
#      - group.downstairs_climate
#      - group.downstairs_ecobee
#      - group.upstairs_climate
#      - group.upstairs_ecobee
#
#  scenes:
#    name: Scenes
#    view: yes
#    entities:
#      - group.lighting_scenes
#      - group.operational_modes
#      - group.automation_override
#      - group.hue_scenes
#
#  exterior:
#    name: Exterior
#    view: yes
#    entities:
#      - group.porch
#      - group.yard
#      - group.pool
#      - group.irrigation
##      - group.sprinklers
##      - group.driplines
#
#  weather:
#    name: Weather
#    view: yes
#    entities:
#      - sun.sun
#      - sensor.moon
#      - group.weather_summary
#      - group.weather_details
#      - group.3_day_forecast
#      #- group.river_info
#
#  media:
#    name: Media
#    view: yes
#    entities:
#      - group.living_room_tv
#      - group.directv
#      - group.onkyo_amp
#      - media_player.kodi_living_room
#      - media_player.firetv
#      - media_player.apple_tv
#
#  system:
#    name: System
#    view: yes
#    entities:
#      - group.ha_status
#      - group.speedtest
#      - group.downloads
#
#  lab:
#    name: Lab
#    view: yes
#    entities:
#      - group.test_triggers
#      - group.test_conditions
