############################################################################
#    @package          :     views
#    @description      :     views visible on UI
############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'views'

      hidden: &hidden
        <<: *customize
        hidden: true

group:
  home:

