#####################################################################
#    @package          :     weather
#    @description      :     weather sensors and associated automations, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'weather'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Weather - ecobee
    ################################################
    weather.downstairs:
      friendly_name: "Currently"


    ################################################
    ## Sensor - Darksky weather
    ################################################
    sensor.dark_sky_humidity:
      friendly_name: "Humidity"
      icon: mdi:water-percent

    sensor.dark_sky_dew_point:
      friendly_name: "Dew Point"
      icon: mdi:water

    sensor.dark_sky_daily_summary:
      friendly_name: "Outlook"

    sensor.dark_sky_hourly_summary:
      friendly_name: "Today"

    sensor.dark_sky_pressure:
      friendly_name: "Pressure"
      icon: mdi:nature

    sensor.dark_sky_temperature:
      friendly_name: "Temperature"
      icon: mdi:thermometer

    sensor.dark_sky_wind_speed:
      friendly_name: "Wind Speed"
      icon: mdi:weather-windy

    sensor.dark_sky_summary:
      friendly_name: "Current Conditions"
      icon: mdi:map-marker-radius

    sensor.dark_sky_precip_probability:
      friendly_name: "Chance of Rain"
      icon: mdi:weather-rainy

    sensor.dark_sky_precip_intensity:
      friendly_name: "Predicted Rain"
      icon: mdi:weather-rainy

    sensor.dark_sky_visibility:
      friendly_name: "Visibility"

    sensor.dark_sky_cloud_coverage:
      friendly_name: "Cloud Cover"
      icon: mdi:weather-partlycloudy

    sensor.dark_sky_wind_bearing:
      friendly_name: "Wind Bearing"
      icon: mdi:compass

    sensor.dark_sky_apparent_temperature:
      friendly_name: "Feels Like"

    sensor.dark_sky_nearest_storm_distance:
      friendly_name: "Nearest Storm"
      icon: mdi:weather-lightning-rainy

    sensor.dark_sky_daytime_high_temperature_0:
      friendly_name: "Today's High"

    sensor.dark_sky_overnight_low_temperature_0:
      friendly_name: "Tonight's Low"

    ## Tomorrow
    sensor.dark_sky_summary_1:
      friendly_name: "Tomorrow"

    sensor.dark_sky_daytime_high_temperature_1:
      friendly_name: "Tomorrow's High"

    sensor.dark_sky_overnight_low_temperature_1:
      friendly_name: "Tomorrow's Low"

    sensor.dark_sky_precip_probability_1:
      friendly_name: "Chance of Rain"
      icon: mdi:weather-rainy

    sensor.dark_sky_wind_speed_1:
      friendly_name: "Wind"

    sensor.dark_sky_wind_gust_1:
      friendly_name: "Wind Gusts"

    ## Day After
    sensor.dark_sky_summary_2:
      friendly_name: "Day 2"

    sensor.dark_sky_daytime_high_temperature_2:
      friendly_name: "Day 2 High"

    sensor.dark_sky_overnight_low_temperature_2:
      friendly_name: "Day 2 Low"

    sensor.dark_sky_precip_probability_2:
      friendly_name: "Chance of Rain"
      icon: mdi:weather-rainy

    sensor.dark_sky_wind_speed_2:
      friendly_name: "Wind"

    sensor.dark_sky_wind_gust_2:
      friendly_name: "Wind Gusts"

    ## Next Day
    sensor.dark_sky_summary_3:
      friendly_name: "Day 3"

    sensor.dark_sky_daytime_high_temperature_3:
      friendly_name: "Day 3 High"

    sensor.dark_sky_overnight_low_temperature_3:
      friendly_name: "Day 3 Low"

    sensor.dark_sky_precip_probability_3:
      friendly_name: "Chance of Rain"
      icon: mdi:weather-rainy

    sensor.dark_sky_wind_speed_3:
      friendly_name: "Wind"

    sensor.dark_sky_wind_gust_3:
      friendly_name: "Wind Gusts"


#####################################################################
### Input Boolean
#####################################################################
input_boolean:
  rain:
    name: Rain Sensor
    icon: mdi:weather-rainy

#####################################################################
### Input Number
#####################################################################
input_number:
  ### Summer Temp Threshold
  season_summer:
    name: "Summer"
    initial: 76
    min: 60
    max: 100
    step: 1
    mode: slider

  ### Winter Temp Threshold
  season_winter:
    name: "Winter"
    initial: 62
    min: 40
    max: 80
    step: 1
    mode: slider


#####################################################################
### Weather - Darksky
#####################################################################
weather:
  - platform: darksky
    api_key: !secret darksky_key

#####################################################################
### Sensor
#####################################################################
sensor:
### Seasons
  - platform: template
    sensors:
      season:
        friendly_name: "Seasonal Condition"
        value_template: >-
          {% set temperature = states('sensor.dark_sky_temperature')|float(none) %}
          {% set winter_temp = states.input_number.season_winter.state|default(62)|float %}
          {% set summer_temp = states.input_number.season_summer.state|default(76)|float %}
          {% if temperature is none %}
            {{ states('sensor.sensor.dark_sky_temperature') }}
          {% elif temperature < winter_temp %}
            Winter
          {% elif temperature > summer_temp %}
            Summer
          {% else %}
            Awesome
          {% endif %}


### Moon
  - platform: moon


### Darksky
  - platform: darksky
    api_key: !secret forecast_api_key
    forecast:
      - 0
      - 1
      - 2
      - 3

    monitored_conditions:
      - summary
      - icon
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - dew_point
      - wind_speed
      - wind_gust
      - wind_bearing
      - humidity
      - pressure
      - uv_index
      - nearest_storm_distance
      - cloud_cover
      - daily_summary
      - hourly_summary
      - minutely_summary
      - precip_probability
      - precip_intensity


#####################################################################
### Automation
#####################################################################
automation:
  - alias: rain sensor
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: weather.downstairs

    action:
      - service_template: >-
          {% if is_state('sensor.dark_sky_summary', 'Rain') %}
            homeassistant.turn_on
          {% elif is_state('sensor.dark_sky_summary', 'Light Rain') %}
            homeassistant.turn_on
          {% elif is_state('sensor.dark_sky_summary', 'Thunderstorm') %}
            homeassistant.turn_on
          {% elif is_state('sensor.dark_sky_summary', 'Showers') %}
            homeassistant.turn_on
          {% elif is_state('sensor.dark_sky_summary', 'Drizzle') %}
            homeassistant.turn_on
          {% else %}
            homeassistant.turn_off
          {% endif %}
        data:
          entity_id: input_boolean.rain
