
#####################################################################
### Automation
#####################################################################
automation:
  ### Test iOS
  - alias: Test notifications
    initial_state: 'on'
     
    trigger:
      - platform: state
        entity_id: input_boolean.state_change
#        from: 'off'
#        to: 'on'

    action:
#      ### WORKS!
#      - service: notify.alexa_media
#        data_template:
#          target: media_player.office
#          message: "The {{ trigger.to_state.attributes.friendly_name }} has triggered."
#          data:
#            type: announce


      ### working 0.97.2
#      - service: notify.mobile_app_rip8plus
#        data:
#          title: "Test Message"
#          message: "This is a test"
#          data:
#            push:
#              category: test
#              sound:
#                name: default

### test in progress 0.102.3
      - service: notify.mobile_app_rip8plus
        data:
          title: "Testing"
          message: "Test Started..."
          data:
            push:
              thread-id: "test"
              sound:
                name: default
            apns_headers:
              'apns-collapse-id': 'test'


#  - alias: test action desk light
#    initial_state: 'on'
#     
#    trigger:
#      platform: event
#      event_type: ios.notification_action_fired
#      event_data:
#        actionName: TEST_ACTION
#
#    action:
#      service: light.turn_on
#      entity_id: light.office_desk


#  ### Test Away Mode Trigger
#  - alias: Test Away Mode
#    initial_state: 'on'
#     
#    trigger:
#      - platform: state
#        entity_id: input_boolean.state_change
#        from: 'off'
#        to: 'on'

#    condition:
#      - condition: state
#        entity_id: input_boolean.condition_3
#        state: 'on'
#
#      - condition: or
#        conditions:
#          - condition: state
#            entity_id: input_boolean.condition_4
#            state: 'on'
#
#          - condition: state
#            entity_id: input_boolean.condition_5
#            state: 'on'
#
#      - condition: or
#        conditions:
#          - condition: state
#            entity_id: input_boolean.condition_1
#            state: 'on'
#
#          - condition: state
#            entity_id: input_boolean.condition_2
#            state: 'on'

#    action:
#      - service: homeassistant.turn_on
#        entity_id: input_boolean.state_change


#  ### Test Condition 1
#  - alias: Test Input Boolean Condition 1
#    initial_state: 'on'
#     
#    trigger:
#      - platform: state
#        entity_id: input_boolean.state_change
#        from: 'off'
#        to: 'on'
#
#    condition:
#      - condition: state
#        entity_id: input_boolean.condition_3
#        state: 'on'
#
#      - condition: or
#        conditions:
#          - condition: state
#            entity_id: input_boolean.condition_4
#            state: 'on'
#
#          - condition: state
#            entity_id: input_boolean.condition_5
#            state: 'on'
#
#      - condition: or
#        conditions:
#          - condition: state
#            entity_id: input_boolean.condition_1
#            state: 'on'
#
#          - condition: state
#            entity_id: input_boolean.condition_2
#            state: 'on'
#
#    action:
#      - service: input_select.select_option
#        data:
#          entity_id: input_select.rgb_light
#          option: "Red"
#
#
#  ### Test Condition 2
#  - alias: Test Input Boolean Condition 2
#    initial_state: 'on'
#     
#    trigger:
#      - platform: state
#        entity_id: input_boolean.state_change
#        from: 'off'
#        to: 'on'
#
#    condition:
#      - condition: state
#        entity_id: input_boolean.condition_1
#        state: 'on'
#
#      - condition: state
#        entity_id: input_boolean.condition_2
#        state: 'on'
#
#      - condition: state
#        entity_id: input_boolean.condition_3
#        state: 'off'
#
#      - condition: or
#        conditions:
#          - condition: state
#            entity_id: input_boolean.condition_4
#            state: 'off'
#
#          - condition: state
#            entity_id: input_boolean.condition_5
#            state: 'off'
#
#    action:
#      - service: input_select.select_option
#        data:
#          entity_id: input_select.rgb_light
#          option: "Blue"
#
#
#  ### Test Condition 3
#  - alias: Test Input Boolean Condition 3
#    initial_state: 'on'
#     
#    trigger:
#      - platform: state
#        entity_id: input_boolean.state_change
#        from: 'off'
#        to: 'on'
#
#    condition:
#      - condition: state
#        entity_id: input_boolean.condition_1
#        state: 'off'
#
#      - condition: state
#        entity_id: input_boolean.condition_2
#        state: 'off'
#
#      - condition: state
#        entity_id: input_boolean.condition_3
#        state: 'off'
#
#      - condition: or
#        conditions:
#          - condition: state
#            entity_id: input_boolean.condition_4
#            state: 'on'
#
#          - condition: state
#            entity_id: input_boolean.condition_5
#            state: 'on'
#
#    action:
#      - service: input_select.select_option
#        data:
#          entity_id: input_select.rgb_light
#          option: "Violet"


#  ### TEST --- Turn off the lights in the morning once sun is up high enough
#  - alias: Test Living Room Off Morning
#    initial_state: 'on'
#    trigger:
#      - platform: numeric_state
#        entity_id: sun.sun
#        value_template: '{{ state.attributes.elevation }}'
#        above: 9
#        for:
#          minutes: 5
#
#    action:
#      - service: notify.mobile_app_rip8plus
#        data:
#          title: "Sun Up Trigger OK"
#          message: "Sun is {{ states.sun.sun.attributes.elevation }} at {{ states.sensor.floorplan_time.state }}"


#  ### TEST --- Set away mode when weather is awesome
#  - alias: Test Climate Upstairs Away if Awesome Weather
#    initial_state: 'on'
#    trigger:
#      - platform: numeric_state
#        entity_id: sensor.us_avg_temp
#        above: 68
#        below: 81
#
#        for:
#          minutes: 15
#
#    action:
#      - service: notify.mobile_app_rip8plus
#        data:
#          title: "Awesome Weather Trigger OK"
#          message: "Awesome Weather Trigger OK"